import type {
  MissionActivityItem,
  MissionArtifact,
  MissionControlPrototypeModel,
  MissionExecution,
  MissionInitiative,
  MissionInitiativeStageState,
  MissionRunSummary,
  MissionWorkflowStageDefinition,
  MissionWorkflowTemplate,
} from "./types";

function stage(
  stageKey: MissionWorkflowStageDefinition["stageKey"],
  label: string,
  summary: string,
  ownerLabel: string,
  outputLabel: string,
): MissionWorkflowStageDefinition {
  return {
    stageKey,
    label,
    summary,
    ownerLabel,
    outputLabel,
  };
}

function stageState(
  stageKey: MissionInitiativeStageState["stageKey"],
  status: MissionInitiativeStageState["status"],
  summary: string,
  exitLabel: string,
  artifactIds: string[],
): MissionInitiativeStageState {
  return {
    stageKey,
    status,
    summary,
    exitLabel,
    artifactIds,
  };
}

function runSummary(total: number, running: number, waiting: number, failed: number): MissionRunSummary {
  return {
    total,
    running,
    waiting,
    failed,
  };
}

const workflows: MissionWorkflowTemplate[] = [
  {
    workflowId: "workflow-full-delivery",
    title: "Полный цикл инициативы",
    summary: "От intake до ops с обязательными артефактами по продукту, архитектуре и поставке.",
    kind: "system",
    launchSummary: "Подходит для новых платформенных инициатив и крупных изменений.",
    voiceHint: "Опишите идею, цель, ограничения и желаемый результат. Платформа разложит работу по стадиям.",
    policyBullets: [
      "На разрывах между стадиями создаются follow-up задачи.",
      "После design и qa возможны owner-гейты.",
      "PR не является единственным обязательным артефактом.",
    ],
    stages: [
      stage("intake", "Прием", "Фиксируем запрос и ожидаемый результат.", "Владелец", "Черновой бриф"),
      stage("vision", "Видение", "Определяем ценность, контур и целевое поведение.", "Владелец", "Vision note"),
      stage("prd", "PRD", "Формализуем требования и ограничения.", "Продуктовый агент", "PRD"),
      stage("arch", "Архитектура", "Выбираем контракты и границы систем.", "Архитектор", "Архитектурная записка"),
      stage("design", "Дизайн", "Собираем UX и структуру экранов.", "Дизайнер", "Схема экранов"),
      stage("plan", "План", "Фиксируем этапы реализации и handover.", "Планировщик", "План поставки"),
      stage("dev", "Разработка", "Делаем код и промежуточные артефакты.", "Разработчик", "Код + PR"),
      stage("qa", "Проверка", "Проверяем поведение и риски.", "QA-агент", "Сценарии проверки"),
      stage("release", "Релиз", "Готовим выпуск и контрольный список.", "Релиз-агент", "Пакет релиза"),
      stage("postdeploy", "После выкладки", "Подтверждаем работоспособность в среде.", "Оператор", "Отчет после выкладки"),
      stage("ops", "Сопровождение", "Наблюдаем и закрываем хвосты.", "Оператор", "Follow-up задачи"),
    ],
  },
  {
    workflowId: "workflow-short-delivery",
    title: "Короткий цикл поставки",
    summary: "Когда discovery уже есть и нужно быстро пройти путь от дизайна до релиза.",
    kind: "system",
    launchSummary: "Подходит для инкрементов в существующем продукте.",
    voiceHint: "Опишите изменение, желаемый эффект и что уже известно на входе.",
    policyBullets: [
      "Начинаем с design, без intake и vision.",
      "QA и release остаются обязательными.",
      "Если возникает новый риск, платформа создаёт follow-up задачу.",
    ],
    stages: [
      stage("design", "Дизайн", "Проверяем UX и контур решения.", "Дизайнер", "Схема изменений"),
      stage("plan", "План", "Разбиваем задачу на поставку.", "Планировщик", "План"),
      stage("dev", "Разработка", "Реализуем и собираем PR.", "Разработчик", "Код + PR"),
      stage("qa", "Проверка", "Проверяем поведение и риски.", "QA-агент", "Набор проверок"),
      stage("release", "Релиз", "Готовим выпуск.", "Релиз-агент", "Кандидат в релиз"),
    ],
  },
  {
    workflowId: "workflow-hotfix",
    title: "Горячее исправление",
    summary: "Короткий контур для срочного исправления в боевом процессе.",
    kind: "system",
    launchSummary: "Подходит для инцидентов и регрессий, когда нужен быстрый выпуск.",
    voiceHint: "Назовите симптом, влияние на пользователя и насколько срочно нужно исправление.",
    policyBullets: [
      "Сначала triage, затем fix и обязательная быстрая проверка.",
      "После релиза обязателен postdeploy-контроль.",
      "Follow-up по коренной причине выносится отдельной задачей.",
    ],
    stages: [
      stage("triage", "Разбор", "Уточняем масштаб и краткосрочную стратегию.", "Оператор", "План hotfix"),
      stage("fix", "Исправление", "Собираем минимальное изменение.", "Разработчик", "Код + PR"),
      stage("qa", "Проверка", "Проверяем базовый happy path.", "QA-агент", "Smoke сценарии"),
      stage("release", "Релиз", "Выпускаем hotfix.", "Релиз-агент", "Патч-релиз"),
      stage("postdeploy", "После выкладки", "Смотрим, ушел ли симптом.", "Оператор", "Проверка после выкладки"),
    ],
  },
  {
    workflowId: "workflow-owner-showcase",
    title: "Витрина для владельца",
    summary: "Проектный workflow для подготовки интерфейса, owner review и handover в backend.",
    kind: "project",
    projectId: "project-kodex",
    launchSummary: "Используется для экранов, которые сначала оттачиваются на fake data.",
    voiceHint: "Опишите, какой экран должен появиться, кому он нужен и какое решение должен ускорять.",
    policyBullets: [
      "Главный артефакт до backend-фазы — frontend prototype.",
      "После owner review автоматически готовится задача на backend-проработку.",
      "Runs скрыты, пока владелец не попросит диагностику.",
    ],
    stages: [
      stage("vision", "Видение", "Фиксируем сценарий владельца и ценность экрана.", "Владелец", "Owner narrative"),
      stage("design", "Дизайн", "Собираем UX и экранную структуру.", "Дизайнер", "Каркас экранов"),
      stage("plan", "План", "Уточняем границы frontend и backend.", "Планировщик", "План итераций"),
      stage("dev", "Разработка", "Собираем фронтенд-прототип и сценарии просмотра.", "Разработчик", "Прототип"),
      stage("qa", "Проверка", "Владелец проходит сценарии и оставляет замечания.", "Владелец", "Список замечаний"),
      stage("release", "Передача", "Фиксируем итоговый UX и создаём backend handover.", "Планировщик", "Handover-пакет"),
    ],
  },
];

const initiatives: MissionInitiative[] = [
  {
    initiativeId: "initiative-mission-control",
    projectId: "project-kodex",
    workflowId: "workflow-owner-showcase",
    title: "Панель управления инициативами и агентами",
    summary: "Собираем понятный Mission Control для владельца: обзор портфеля, workspace инициативы, studio workflow и executions.",
    ownerLabel: "Артем",
    currentStageKey: "design",
    nextAction: "Утвердить структуру экранов и собрать первую понятную витрину на fake data.",
    statusLabel: "Нужна ясная структура экранов",
    attentionLabel: "Нужно решение владельца по UX-каркасу",
    attentionTone: "warning",
    tags: ["голосовое управление", "Mission Control", "fake data"],
    artifactIds: [
      "artifact-mc-vision",
      "artifact-mc-design-map",
      "artifact-mc-prototype-task",
      "artifact-mc-review-pr",
      "artifact-mc-backend-followup",
    ],
    stageStates: [
      stageState("vision", "done", "Сценарии владельца и целевая модель экранов согласованы.", "Есть owner narrative", [
        "artifact-mc-vision",
      ]),
      stageState("design", "active", "Собираем новый UX-каркас и перерабатываем fake data.", "Нужен первый понятный walkthrough", [
        "artifact-mc-design-map",
        "artifact-mc-prototype-task",
      ]),
      stageState("plan", "pending", "После согласования UX зафиксируем backend handover.", "Понятны границы фронта и backend", [
        "artifact-mc-backend-followup",
      ]),
      stageState("dev", "pending", "Разработка backend начнется после фиксации UX.", "Есть итоговая витрина", []),
      stageState("qa", "pending", "Owner review пройдет на локальном preview.", "Владелец принял UX", [
        "artifact-mc-review-pr",
      ]),
      stageState("release", "pending", "Передаем backend-команде итоговую модель.", "Сформирован handover-пакет", []),
    ],
    blockedReason: "Нельзя уходить в backend, пока владелец не увидит удобную структуру экранов.",
    runSummary: runSummary(4, 1, 1, 0),
  },
  {
    initiativeId: "initiative-release-guard",
    projectId: "project-kodex",
    workflowId: "workflow-short-delivery",
    title: "Контур апрувов перед релизом",
    summary: "Упрощаем цепочку owner approve, чтобы релизный кандидат не терялся между QA и выпуском.",
    ownerLabel: "Артем",
    currentStageKey: "qa",
    nextAction: "Закрыть один блокер в сценарии подтверждения и повторно прогнать smoke.",
    statusLabel: "Есть блокер перед релизом",
    attentionLabel: "Один failed-run в проверке релиза",
    attentionTone: "error",
    tags: ["апрувы", "релиз", "owner review"],
    artifactIds: ["artifact-rg-design-note", "artifact-rg-release-task", "artifact-rg-release-pr", "artifact-rg-candidate"],
    stageStates: [
      stageState("design", "done", "Цепочка апрувов и статусы карточек обновлены.", "Есть схема статусов", [
        "artifact-rg-design-note",
      ]),
      stageState("plan", "done", "План поставки и состав smoke-проверки определены.", "Понятны риски и порядок выкатки", []),
      stageState("dev", "done", "PR собран и готов к итоговой проверке.", "Есть кандидат в релиз", [
        "artifact-rg-release-task",
        "artifact-rg-release-pr",
      ]),
      stageState("qa", "blocked", "Один сценарий перехода в release wait падает на повторной проверке.", "Smoke зелёный", [
        "artifact-rg-candidate",
      ]),
      stageState("release", "pending", "После повторной проверки пойдет релизный кандидат.", "Есть owner approval и smoke", []),
    ],
    blockedReason: "Сценарий ожидания owner approve еще нестабилен.",
    runSummary: runSummary(5, 0, 1, 1),
  },
  {
    initiativeId: "initiative-hotfix-login",
    projectId: "project-supplier-portal",
    workflowId: "workflow-hotfix",
    title: "Горячее исправление входа по email",
    summary: "Устраняем регрессию: часть пользователей не может войти после смены allowlist-политики.",
    ownerLabel: "Операционный дежурный",
    currentStageKey: "release",
    nextAction: "Подтвердить smoke после выкладки и создать follow-up по коренной причине.",
    statusLabel: "Готовим выпуск hotfix",
    attentionLabel: "Нужно решение по follow-up после релиза",
    attentionTone: "info",
    tags: ["hotfix", "авторизация", "support"],
    artifactIds: ["artifact-hf-triage", "artifact-hf-pr", "artifact-hf-smoke", "artifact-hf-release"],
    stageStates: [
      stageState("triage", "done", "Причина локализована: неверная проверка email после изменения allowlist.", "Есть стратегия hotfix", [
        "artifact-hf-triage",
      ]),
      stageState("fix", "done", "Исправление собрано и прошло code review.", "PR слит", [
        "artifact-hf-pr",
      ]),
      stageState("qa", "done", "Критичный happy path проверен вручную.", "Smoke подтвержден", [
        "artifact-hf-smoke",
      ]),
      stageState("release", "active", "Готовим патч-релиз и контрольный постдеплой.", "Патч выложен", [
        "artifact-hf-release",
      ]),
      stageState("postdeploy", "pending", "Нужно подтвердить вход в проде и открыть follow-up.", "Подтверждено снятие симптома", []),
    ],
    runSummary: runSummary(3, 1, 0, 0),
  },
  {
    initiativeId: "initiative-allowlist-onboarding",
    projectId: "project-supplier-portal",
    workflowId: "workflow-short-delivery",
    title: "Онбординг пользователей через allowlist",
    summary: "Делаем понятный поток приглашения пользователя, чтобы администратор видел, кого можно пускать в платформу.",
    ownerLabel: "Марина",
    currentStageKey: "dev",
    nextAction: "Доделать карточку пользователя и связать её с проектными ролями.",
    statusLabel: "Идет фронтенд-разработка",
    attentionLabel: "Нужно согласовать копирайтинг в карточке пользователя",
    attentionTone: "warning",
    tags: ["онбординг", "allowlist", "пользователи"],
    artifactIds: ["artifact-al-design", "artifact-al-task", "artifact-al-pr"],
    stageStates: [
      stageState("design", "done", "Флоу приглашения администратора и первого входа согласован.", "Есть схема экранов", [
        "artifact-al-design",
      ]),
      stageState("plan", "done", "Разбивка на фронтенд и backend уточнена.", "Понятен состав поставки", []),
      stageState("dev", "active", "Собираем интерфейс списка пользователей и allowlist-формы.", "Есть owner-ready demo", [
        "artifact-al-task",
        "artifact-al-pr",
      ]),
      stageState("qa", "pending", "После демо соберем список замечаний.", "Есть пройденный walkthrough", []),
      stageState("release", "pending", "Поставка пойдет после проверки owner-сценария.", "Есть QA и approve", []),
    ],
    runSummary: runSummary(2, 1, 0, 0),
  },
];

const artifacts: MissionArtifact[] = [
  {
    artifactId: "artifact-mc-vision",
    initiativeId: "initiative-mission-control",
    stageKey: "vision",
    kind: "doc",
    title: "Документ: сценарии владельца для Mission Control",
    summary: "Описывает, что владелец должен понимать и запускать с главного экрана.",
    status: "done",
    ownerLabel: "Владелец",
    badgeLabels: ["основа UX"],
    updatedAtLabel: "обновлен сегодня",
    runSummary: runSummary(0, 0, 0, 0),
  },
  {
    artifactId: "artifact-mc-design-map",
    initiativeId: "initiative-mission-control",
    stageKey: "design",
    kind: "doc",
    title: "Документ: карта экранов Mission Control",
    summary: "Каркас главного экрана, инициативы, редактора workflow и раздела исполнений.",
    status: "active",
    ownerLabel: "Дизайнер",
    badgeLabels: ["нужен walkthrough"],
    updatedAtLabel: "обновлен 20 минут назад",
    runSummary: runSummary(0, 0, 0, 0),
  },
  {
    artifactId: "artifact-mc-prototype-task",
    initiativeId: "initiative-mission-control",
    stageKey: "design",
    kind: "task",
    title: "Задача: собрать русскоязычный frontend-прототип",
    summary: "Собираем понятный интерфейс на fake data, чтобы владелец мог пройти сценарии и оставить замечания.",
    status: "active",
    ownerLabel: "Разработчик",
    badgeLabels: ["локальный preview", "voice FAB"],
    updatedAtLabel: "обновлен 5 минут назад",
    runSummary: runSummary(2, 1, 0, 0),
  },
  {
    artifactId: "artifact-mc-review-pr",
    initiativeId: "initiative-mission-control",
    stageKey: "qa",
    kind: "pr",
    title: "PR: owner walkthrough нового Mission Control",
    summary: "Рабочий PR для итеративного UX-review до начала backend-проработки.",
    status: "review",
    ownerLabel: "Владелец",
    badgeLabels: ["рабочий PR"],
    updatedAtLabel: "обновлен сегодня",
    runSummary: runSummary(2, 0, 1, 0),
  },
  {
    artifactId: "artifact-mc-backend-followup",
    initiativeId: "initiative-mission-control",
    stageKey: "plan",
    kind: "task",
    title: "Задача: проработать backend contract после фиксации UX",
    summary: "Follow-up на backend создается только после финального подтверждения структуры экранов.",
    status: "draft",
    ownerLabel: "Планировщик",
    badgeLabels: ["создать позже"],
    updatedAtLabel: "еще не запускалась",
    runSummary: runSummary(0, 0, 0, 0),
  },
  {
    artifactId: "artifact-rg-design-note",
    initiativeId: "initiative-release-guard",
    stageKey: "design",
    kind: "doc",
    title: "Документ: статусы owner approve перед релизом",
    summary: "Определяет состояния карточки и правила handover между QA и релизом.",
    status: "done",
    ownerLabel: "Дизайнер",
    badgeLabels: ["release flow"],
    updatedAtLabel: "вчера",
    runSummary: runSummary(0, 0, 0, 0),
  },
  {
    artifactId: "artifact-rg-release-task",
    initiativeId: "initiative-release-guard",
    stageKey: "dev",
    kind: "task",
    title: "Задача: собрать owner approve guard",
    summary: "Перестроить статусы и waiting-состояния без потери visibility.",
    status: "done",
    ownerLabel: "Разработчик",
    badgeLabels: ["release wait"],
    updatedAtLabel: "сегодня",
    runSummary: runSummary(1, 0, 0, 0),
  },
  {
    artifactId: "artifact-rg-release-pr",
    initiativeId: "initiative-release-guard",
    stageKey: "dev",
    kind: "pr",
    title: "PR: контур owner approve перед релизом",
    summary: "Готовый кандидат, который держит QA, wait queue и release summary в одной логике.",
    status: "review",
    ownerLabel: "Ревьюер",
    badgeLabels: ["кандидат в релиз"],
    updatedAtLabel: "1 час назад",
    runSummary: runSummary(2, 0, 1, 0),
  },
  {
    artifactId: "artifact-rg-candidate",
    initiativeId: "initiative-release-guard",
    stageKey: "qa",
    kind: "release",
    title: "Кандидат в релиз: owner approve guard",
    summary: "Повторный smoke показывает падение одного сценария ожидания подтверждения.",
    status: "blocked",
    ownerLabel: "QA-агент",
    badgeLabels: ["есть блокер"],
    updatedAtLabel: "15 минут назад",
    runSummary: runSummary(2, 0, 0, 1),
  },
  {
    artifactId: "artifact-hf-triage",
    initiativeId: "initiative-hotfix-login",
    stageKey: "triage",
    kind: "doc",
    title: "Разбор инцидента: вход по email после смены allowlist",
    summary: "Фиксируем симптом, влияние и краткосрочную стратегию hotfix.",
    status: "done",
    ownerLabel: "Оператор",
    badgeLabels: ["hotfix"],
    updatedAtLabel: "сегодня",
    runSummary: runSummary(0, 0, 0, 0),
  },
  {
    artifactId: "artifact-hf-pr",
    initiativeId: "initiative-hotfix-login",
    stageKey: "fix",
    kind: "pr",
    title: "PR: исправление проверки email при входе",
    summary: "Минимальный патч без расширения области изменений.",
    status: "done",
    ownerLabel: "Разработчик",
    badgeLabels: ["слит"],
    updatedAtLabel: "40 минут назад",
    runSummary: runSummary(1, 0, 0, 0),
  },
  {
    artifactId: "artifact-hf-smoke",
    initiativeId: "initiative-hotfix-login",
    stageKey: "qa",
    kind: "task",
    title: "Проверка: smoke по критичному happy path",
    summary: "Проверяем вход администратора и обычного пользователя.",
    status: "done",
    ownerLabel: "QA-агент",
    badgeLabels: ["smoke"],
    updatedAtLabel: "25 минут назад",
    runSummary: runSummary(1, 0, 0, 0),
  },
  {
    artifactId: "artifact-hf-release",
    initiativeId: "initiative-hotfix-login",
    stageKey: "release",
    kind: "release",
    title: "Патч-релиз: исправление входа по email",
    summary: "Релиз готовится к выкладке, postdeploy-проверка еще впереди.",
    status: "active",
    ownerLabel: "Релиз-агент",
    badgeLabels: ["нужен postdeploy"],
    updatedAtLabel: "10 минут назад",
    runSummary: runSummary(1, 1, 0, 0),
  },
  {
    artifactId: "artifact-al-design",
    initiativeId: "initiative-allowlist-onboarding",
    stageKey: "design",
    kind: "doc",
    title: "Документ: сценарий приглашения пользователя",
    summary: "Показывает, как администратор добавляет email и как пользователь проходит первый вход.",
    status: "done",
    ownerLabel: "Дизайнер",
    badgeLabels: ["onboarding"],
    updatedAtLabel: "вчера",
    runSummary: runSummary(0, 0, 0, 0),
  },
  {
    artifactId: "artifact-al-task",
    initiativeId: "initiative-allowlist-onboarding",
    stageKey: "dev",
    kind: "task",
    title: "Задача: карточка пользователя и allowlist-форма",
    summary: "Собираем UI для списка пользователей, прав и ручного допуска по email.",
    status: "active",
    ownerLabel: "Разработчик",
    badgeLabels: ["UI", "список пользователей"],
    updatedAtLabel: "12 минут назад",
    runSummary: runSummary(1, 1, 0, 0),
  },
  {
    artifactId: "artifact-al-pr",
    initiativeId: "initiative-allowlist-onboarding",
    stageKey: "dev",
    kind: "pr",
    title: "PR: onboarding через allowlist",
    summary: "PR для owner walkthrough сценария приглашения и первого входа.",
    status: "review",
    ownerLabel: "Владелец",
    badgeLabels: ["owner demo"],
    updatedAtLabel: "сегодня",
    runSummary: runSummary(1, 0, 0, 0),
  },
];

const activity: MissionActivityItem[] = [
  {
    itemId: "activity-mc-1",
    initiativeId: "initiative-mission-control",
    title: "Согласована долгосрочная модель Mission Control",
    summary: "Зафиксирован набор экранов: главная, инициатива, редактор workflow и исполнения.",
    happenedAtLabel: "сейчас",
    actorLabel: "Владелец",
    tone: "success",
  },
  {
    itemId: "activity-mc-2",
    initiativeId: "initiative-mission-control",
    title: "Прототип переведен на русскоязычные fake data",
    summary: "Убраны смешанные demo-сценарии и технические узлы первого уровня.",
    happenedAtLabel: "сегодня",
    actorLabel: "Разработчик",
    tone: "info",
  },
  {
    itemId: "activity-rg-1",
    initiativeId: "initiative-release-guard",
    title: "Smoke перед релизом упал на одном сценарии",
    summary: "Нужно уточнить поведение карточки при owner approve wait.",
    happenedAtLabel: "15 минут назад",
    actorLabel: "QA-агент",
    tone: "error",
  },
  {
    itemId: "activity-hf-1",
    initiativeId: "initiative-hotfix-login",
    title: "Hotfix готов к выкладке",
    summary: "После релиза требуется только postdeploy-подтверждение и follow-up.",
    happenedAtLabel: "10 минут назад",
    actorLabel: "Релиз-агент",
    tone: "warning",
  },
  {
    itemId: "activity-al-1",
    initiativeId: "initiative-allowlist-onboarding",
    title: "Нужен review по копирайтингу карточки пользователя",
    summary: "Смысл статусов allowlist должен быть понятен администратору без гайдов.",
    happenedAtLabel: "30 минут назад",
    actorLabel: "Марина",
    tone: "warning",
  },
];

const executions: MissionExecution[] = [
  {
    executionId: "execution-mc-shell",
    initiativeId: "initiative-mission-control",
    artifactId: "artifact-mc-prototype-task",
    title: "Сборка нового shell для Mission Control",
    summary: "Агент перестраивает page shell и route state под многорежимную модель.",
    status: "running",
    agentRoleLabel: "Разработчик",
    startedAtLabel: "5 минут назад",
    durationLabel: "идет 05:12",
  },
  {
    executionId: "execution-mc-preview",
    initiativeId: "initiative-mission-control",
    artifactId: "artifact-mc-review-pr",
    title: "Подготовка owner walkthrough",
    summary: "Локальный preview поднят, ожидается просмотр владельцем и список замечаний.",
    status: "waiting",
    agentRoleLabel: "Планировщик",
    startedAtLabel: "только что",
    durationLabel: "ждет подтверждения",
  },
  {
    executionId: "execution-rg-smoke",
    initiativeId: "initiative-release-guard",
    artifactId: "artifact-rg-candidate",
    title: "Повторный smoke релизного кандидата",
    summary: "Один сценарий ожидания owner approve завершился неуспешно.",
    status: "failed",
    agentRoleLabel: "QA-агент",
    startedAtLabel: "15 минут назад",
    durationLabel: "02:41",
  },
  {
    executionId: "execution-rg-summary",
    initiativeId: "initiative-release-guard",
    artifactId: "artifact-rg-release-pr",
    title: "Сбор release summary",
    summary: "Формируется карточка кандидата в релиз с owner approve статусами.",
    status: "waiting",
    agentRoleLabel: "Планировщик",
    startedAtLabel: "40 минут назад",
    durationLabel: "ждет smoke",
  },
  {
    executionId: "execution-hf-release",
    initiativeId: "initiative-hotfix-login",
    artifactId: "artifact-hf-release",
    title: "Выкладка hotfix",
    summary: "Патч-релиз уходит в среду, после чего нужен postdeploy-check.",
    status: "running",
    agentRoleLabel: "Релиз-агент",
    startedAtLabel: "10 минут назад",
    durationLabel: "идет 09:03",
  },
  {
    executionId: "execution-al-ui",
    initiativeId: "initiative-allowlist-onboarding",
    artifactId: "artifact-al-task",
    title: "Сборка списка пользователей и allowlist-формы",
    summary: "Агент обновляет карточку пользователя и состояние разрешенного входа.",
    status: "running",
    agentRoleLabel: "Разработчик",
    startedAtLabel: "12 минут назад",
    durationLabel: "идет 11:27",
  },
];

export const missionControlPrototypeModel: MissionControlPrototypeModel = {
  projects: [
    {
      projectId: "project-kodex",
      title: "Платформа КОДЕКС",
      summary: "Внутренний продукт для управления инициативами, агентами и поставкой через платформу.",
      accent: "amber",
    },
    {
      projectId: "project-supplier-portal",
      title: "Кабинет поставщика",
      summary: "Прикладной продукт с авторизацией, allowlist и пользовательскими сценариями входа.",
      accent: "teal",
    },
  ],
  workflows,
  initiatives,
  artifacts,
  activity,
  executions,
};
