import type { MissionCanvasScenario } from "./types";

const repositoryBaseUrl = "https://github.com/codex-k8s/kodex";

export const missionControlPrototypeScenarios: MissionCanvasScenario[] = [
  {
    scenarioId: "owner-walkthrough",
    title: "Owner walkthrough: canvas prototype + deferred backend seam",
    summary: "Три инициативы на одном полотне: Sprint S18 прототип, S17 continuity и quality gate без открытия backend scope.",
    defaultFocusInitiativeId: "initiative-s18",
    defaultViewport: {
      zoomLevel: 0.92,
      panX: 28,
      panY: 24,
      canvasWidth: 1660,
      canvasHeight: 980,
    },
    sourceRefs: [
      "docs/architecture/initiatives/s18_mission_control_frontend_first_canvas/design_doc.md",
      "docs/architecture/prompt_templates_policy.md",
      "services/jobs/agent-runner/internal/runner/templates/prompt_blocks/issue_contract_ru.tmpl",
      "services/jobs/agent-runner/internal/runner/templates/prompt_blocks/pr_contract_work_ru.tmpl",
    ],
    initiatives: [
      {
        initiativeId: "initiative-s18",
        label: "Sprint S18 · Canvas prototype",
        accentToken: "amber",
        focusOrder: 0,
        nodeIds: ["issue-581", "run-s18-demo", "pr-s18-owner-demo", "issue-563"],
      },
      {
        initiativeId: "initiative-s17",
        label: "Sprint S17 · Feedback continuity",
        accentToken: "teal",
        focusOrder: 1,
        nodeIds: ["issue-582", "run-s17-live-wait", "pr-s17-feedback"],
      },
      {
        initiativeId: "initiative-quality",
        label: "Quality gate · Deferred release evidence",
        accentToken: "rose",
        focusOrder: 2,
        nodeIds: ["issue-524", "run-quality-smoke"],
      },
    ],
    nodes: [
      {
        nodeId: "issue-581",
        nodeKind: "Issue",
        initiativeId: "initiative-s18",
        title: "Issue #581 · Isolated Mission Control canvas prototype",
        state: "working",
        stageLabel: "run:dev · fake data only",
        layoutX: 120,
        layoutY: 160,
        meta: ["S18 Day7", "owner-managed", "web-console"],
        badges: ["demo-ready"],
        detailId: "detail-issue-581",
        safeActionIds: ["action-open-581", "action-preview-workflow"],
      },
      {
        nodeId: "run-s18-demo",
        nodeKind: "Run",
        initiativeId: "initiative-s18",
        title: "Candidate demo assembly",
        state: "working",
        stageLabel: "demo evidence · local bundle",
        layoutX: 430,
        layoutY: 150,
        meta: ["Wave 2", "canvas + drawer", "owner walkthrough"],
        badges: ["needs-evidence"],
        detailId: "detail-run-s18-demo",
        safeActionIds: ["action-open-s18-doc", "action-preview-workflow"],
      },
      {
        nodeId: "pr-s18-owner-demo",
        nodeKind: "PR",
        initiativeId: "initiative-s18",
        title: "PR · Owner review package for Mission Control",
        state: "review",
        stageLabel: "PR package · pending owner feedback",
        layoutX: 760,
        layoutY: 170,
        meta: ["checks", "demo evidence", "traceability sync"],
        badges: ["owner-review"],
        detailId: "detail-pr-s18-owner-demo",
        safeActionIds: ["action-open-pr-demo", "action-open-s18-doc"],
      },
      {
        nodeId: "issue-563",
        nodeKind: "Issue",
        initiativeId: "initiative-s18",
        title: "Issue #563 · Backend rebuild handover",
        state: "waiting",
        stageLabel: "deferred boundary",
        layoutX: 1080,
        layoutY: 160,
        meta: ["after owner approval", "backend follow-up"],
        badges: ["deferred", "handover"],
        detailId: "detail-issue-563",
        safeActionIds: ["action-open-563", "action-open-s18-doc"],
      },
      {
        nodeId: "issue-582",
        nodeKind: "Issue",
        initiativeId: "initiative-s17",
        title: "Issue #582 · Unified owner feedback loop execution anchor",
        state: "blocked",
        stageLabel: "run:dev handover",
        layoutX: 210,
        layoutY: 520,
        meta: ["S17-E01..E07", "continuity chain"],
        badges: ["blocked", "live-wait"],
        detailId: "detail-issue-582",
        safeActionIds: ["action-open-582", "action-preview-workflow"],
      },
      {
        nodeId: "run-s17-live-wait",
        nodeKind: "Run",
        initiativeId: "initiative-s17",
        title: "Live wait recovery rehearsal",
        state: "waiting",
        stageLabel: "visibility + reconcile",
        layoutX: 520,
        layoutY: 500,
        meta: ["Telegram inbox", "staff fallback"],
        badges: ["live-wait"],
        detailId: "detail-run-s17-live-wait",
        safeActionIds: ["action-open-s17-doc", "action-preview-workflow"],
      },
      {
        nodeId: "pr-s17-feedback",
        nodeKind: "PR",
        initiativeId: "initiative-s17",
        title: "PR · Owner feedback loop integration",
        state: "review",
        stageLabel: "evidence pending",
        layoutX: 850,
        layoutY: 520,
        meta: ["worker visibility", "api-gateway", "staff UI"],
        badges: ["needs-evidence"],
        detailId: "detail-pr-s17-feedback",
        safeActionIds: ["action-open-s17-doc", "action-open-pr-feedback"],
      },
      {
        nodeId: "issue-524",
        nodeKind: "Issue",
        initiativeId: "initiative-quality",
        title: "Issue #524 · Quality governance owner approval gate",
        state: "blocked",
        stageLabel: "blocked until approved UX",
        layoutX: 1110,
        layoutY: 560,
        meta: ["quality gate", "owner approval"],
        badges: ["blocked"],
        detailId: "detail-issue-524",
        safeActionIds: ["action-open-524", "action-open-quality-doc"],
      },
      {
        nodeId: "run-quality-smoke",
        nodeKind: "Run",
        initiativeId: "initiative-quality",
        title: "Candidate evidence smoke",
        state: "waiting",
        stageLabel: "demo-only evidence",
        layoutX: 1410,
        layoutY: 540,
        meta: ["traceability", "quality checklist"],
        badges: ["needs-evidence"],
        detailId: "detail-run-quality-smoke",
        safeActionIds: ["action-open-quality-doc", "action-preview-workflow"],
      },
    ],
    relations: [
      {
        relationId: "rel-581-drives-demo",
        relationKind: "drives",
        sourceNodeId: "issue-581",
        targetNodeId: "run-s18-demo",
        label: "execution wave drives demo assembly",
        importance: "primary",
      },
      {
        relationId: "rel-demo-produces-pr",
        relationKind: "produces",
        sourceNodeId: "run-s18-demo",
        targetNodeId: "pr-s18-owner-demo",
        label: "owner-ready PR package",
        importance: "primary",
      },
      {
        relationId: "rel-581-tracks-pr",
        relationKind: "tracks",
        sourceNodeId: "issue-581",
        targetNodeId: "pr-s18-owner-demo",
        label: "issue stays continuity anchor",
        importance: "supporting",
      },
      {
        relationId: "rel-pr-blocks-563",
        relationKind: "blocks",
        sourceNodeId: "pr-s18-owner-demo",
        targetNodeId: "issue-563",
        label: "backend rebuild waits for approved UX",
        importance: "primary",
      },
      {
        relationId: "rel-582-drives-run",
        relationKind: "drives",
        sourceNodeId: "issue-582",
        targetNodeId: "run-s17-live-wait",
        label: "continuity anchor drives worker visibility",
        importance: "primary",
      },
      {
        relationId: "rel-run-produces-feedback-pr",
        relationKind: "produces",
        sourceNodeId: "run-s17-live-wait",
        targetNodeId: "pr-s17-feedback",
        label: "integration evidence package",
        importance: "primary",
      },
      {
        relationId: "rel-582-tracks-feedback-pr",
        relationKind: "tracks",
        sourceNodeId: "issue-582",
        targetNodeId: "pr-s17-feedback",
        label: "same dev continuity chain",
        importance: "supporting",
      },
      {
        relationId: "rel-524-blocks-pr",
        relationKind: "blocks",
        sourceNodeId: "issue-524",
        targetNodeId: "pr-s18-owner-demo",
        label: "quality evidence remains explicit gate",
        importance: "primary",
      },
      {
        relationId: "rel-524-drives-quality-run",
        relationKind: "drives",
        sourceNodeId: "issue-524",
        targetNodeId: "run-quality-smoke",
        label: "gate requires owner-ready evidence",
        importance: "supporting",
      },
    ],
    drawerRecords: [
      {
        detailId: "detail-issue-581",
        nodeId: "issue-581",
        overviewMarkdown:
          "Frontend-only delivery anchor для Sprint S18. Здесь фиксируется переход на новый canvas-first UX: route shell, prototype source/store, explicit relations, drawer и workflow preview без backend/API/schema зависимостей.",
        timelineItems: [
          {
            itemId: "timeline-581-plan",
            happenedAt: "2026-04-01T10:20:00Z",
            title: "Plan package approved for implementation",
            summary: "Issue #579 закрепила четыре execution waves и owner-managed continuity в #581.",
            tone: "positive",
            sourceRef: `${repositoryBaseUrl}/issues/579`,
          },
          {
            itemId: "timeline-581-wave2",
            happenedAt: "2026-04-09T13:20:00Z",
            title: "Canvas composition moved to fake-data source",
            summary: "Graph/list toggle и realtime/freshness surfaces исключены из нового baseline.",
            tone: "positive",
          },
          {
            itemId: "timeline-581-gate",
            happenedAt: "2026-04-09T14:10:00Z",
            title: "Owner review gate still explicit",
            summary: "PR package должен показать demo evidence, traceability sync и platform-safe actions only.",
            tone: "warning",
          },
        ],
        relatedNodeIds: ["run-s18-demo", "pr-s18-owner-demo", "issue-563"],
        safeActions: [
          {
            actionId: "action-open-581",
            kind: "link",
            label: "Открыть Issue #581",
            description: "GitHub issue с implementation scope и guardrails.",
            icon: "mdi-open-in-new",
            href: `${repositoryBaseUrl}/issues/581`,
          },
          {
            actionId: "action-preview-workflow",
            kind: "preview",
            label: "Открыть workflow preview",
            description: "Показать deterministic workflow-policy block для выбранного узла.",
            icon: "mdi-code-braces",
          },
        ],
        workflowPresetIds: ["preset-owner-demo", "preset-revise-loop"],
        sourceRefs: [
          "docs/architecture/initiatives/s18_mission_control_frontend_first_canvas/design_doc.md",
          "docs/delivery/epics/s18/epic-s18-day6-mission-control-frontend-first-canvas-plan.md",
        ],
      },
      {
        detailId: "detail-run-s18-demo",
        nodeId: "run-s18-demo",
        overviewMarkdown:
          "Локальная demo-сборка для owner walkthrough. Она существует только как UI evidence: canvas density, drawer readability, workflow preview, source refs и explicit relation routing без live mutation path.",
        timelineItems: [
          {
            itemId: "timeline-run-demo-1",
            happenedAt: "2026-04-09T13:40:00Z",
            title: "Prototype source hydrated",
            summary: "Fixture catalog loaded as bundle-local source contract.",
            tone: "positive",
          },
          {
            itemId: "timeline-run-demo-2",
            happenedAt: "2026-04-09T14:05:00Z",
            title: "Drawer and workflow tabs stabilized",
            summary: "Desktop sticky drawer and mobile fullscreen dialog share the same three tabs.",
            tone: "positive",
          },
        ],
        relatedNodeIds: ["issue-581", "pr-s18-owner-demo"],
        safeActions: [
          {
            actionId: "action-open-s18-doc",
            kind: "doc",
            label: "Открыть design package S18",
            description: "Design source of truth для canvas, drawer и workflow preview.",
            icon: "mdi-file-document-outline",
            href: `${repositoryBaseUrl}/blob/main/docs/architecture/initiatives/s18_mission_control_frontend_first_canvas/design_doc.md`,
          },
          {
            actionId: "action-preview-workflow",
            kind: "preview",
            label: "Показать workflow preview",
            description: "Открыть policy-preview без live mutation semantics.",
            icon: "mdi-code-braces",
          },
        ],
        workflowPresetIds: ["preset-owner-demo", "preset-evidence-gate"],
        sourceRefs: [
          "docs/architecture/initiatives/s18_mission_control_frontend_first_canvas/data_model.md",
          "docs/architecture/initiatives/s18_mission_control_frontend_first_canvas/api_contract.md",
        ],
      },
      {
        detailId: "detail-pr-s18-owner-demo",
        nodeId: "pr-s18-owner-demo",
        overviewMarkdown:
          "Owner-facing PR package: checks, traceability, local preview instructions и acceptance evidence. Здесь prototype остаётся frontend-only и не раскрывает deferred backend flow #563.",
        timelineItems: [
          {
            itemId: "timeline-pr-demo-1",
            happenedAt: "2026-04-09T15:00:00Z",
            title: "Traceability update prepared",
            summary: "Issue map и Sprint S18 history фиксируют run:dev evidence отдельно от backend follow-up.",
            tone: "positive",
          },
          {
            itemId: "timeline-pr-demo-2",
            happenedAt: "2026-04-09T15:20:00Z",
            title: "Local localhost preview attached",
            summary: "Owner review может пройти без candidate namespace и без Kubernetes runtime.",
            tone: "attention",
          },
        ],
        relatedNodeIds: ["issue-581", "issue-563", "issue-524"],
        safeActions: [
          {
            actionId: "action-open-pr-demo",
            kind: "link",
            label: "Открыть draft PR",
            description: "GitHub pull request с code + docs sync и owner-ready body.",
            icon: "mdi-source-pull",
          },
          {
            actionId: "action-open-s18-doc",
            kind: "doc",
            label: "Открыть Sprint S18 history",
            description: "Просмотреть delivery traceability для dev-stage evidence.",
            icon: "mdi-timeline-text-outline",
            href: `${repositoryBaseUrl}/blob/main/docs/delivery/traceability/s18_mission_control_frontend_first_canvas_history.md`,
          },
        ],
        workflowPresetIds: ["preset-owner-demo"],
        sourceRefs: [
          "services/jobs/agent-runner/internal/runner/templates/prompt_blocks/pr_contract_work_ru.tmpl",
          "docs/delivery/development_process_requirements.md",
        ],
      },
      {
        detailId: "detail-issue-563",
        nodeId: "issue-563",
        overviewMarkdown:
          "Deferred backend rebuild seam. Узел присутствует на canvas только для явного handover: он не открывает новых endpoints, не тянет схему БД и остаётся за пределами текущего prototype PR.",
        timelineItems: [
          {
            itemId: "timeline-563-1",
            happenedAt: "2026-04-01T09:00:00Z",
            title: "Deferred after UX approval",
            summary: "Backend rebuild стартует только после owner approval результата Sprint S18.",
            tone: "warning",
            sourceRef: `${repositoryBaseUrl}/issues/563`,
          },
        ],
        relatedNodeIds: ["issue-581", "pr-s18-owner-demo"],
        safeActions: [
          {
            actionId: "action-open-563",
            kind: "link",
            label: "Открыть Issue #563",
            description: "Отдельный backend follow-up без скрытого расширения текущего scope.",
            icon: "mdi-open-in-new",
            href: `${repositoryBaseUrl}/issues/563`,
          },
        ],
        workflowPresetIds: ["preset-handover-boundary"],
        sourceRefs: [
          "docs/architecture/initiatives/s18_mission_control_frontend_first_canvas/architecture.md",
          "docs/architecture/adr/ADR-0018-mission-control-frontend-first-prototype-and-backend-handover-boundary.md",
        ],
      },
      {
        detailId: "detail-issue-582",
        nodeId: "issue-582",
        overviewMarkdown:
          "Параллельная S17 continuity chain остаётся видимой на полотне как отдельная инициатива. Она нужна не для запуска live path здесь и сейчас, а чтобы owner видел соседний delivery stream и зависимость quality/evidence.",
        timelineItems: [
          {
            itemId: "timeline-582-1",
            happenedAt: "2026-04-01T08:30:00Z",
            title: "Run:dev anchor documented",
            summary: "Issue #582 создана как execution anchor для unified owner feedback loop.",
            tone: "positive",
          },
          {
            itemId: "timeline-582-2",
            happenedAt: "2026-04-09T12:55:00Z",
            title: "Still blocked by implementation depth",
            summary: "Worker visibility, adapter normalization и staff fallback требуют отдельного code flow.",
            tone: "warning",
          },
        ],
        relatedNodeIds: ["run-s17-live-wait", "pr-s17-feedback", "issue-524"],
        safeActions: [
          {
            actionId: "action-open-582",
            kind: "link",
            label: "Открыть Issue #582",
            description: "Execution anchor для S17-E01..S17-E07.",
            icon: "mdi-open-in-new",
            href: `${repositoryBaseUrl}/issues/582`,
          },
          {
            actionId: "action-open-s17-doc",
            kind: "doc",
            label: "Открыть design package S17",
            description: "Source of truth для unified owner feedback loop.",
            icon: "mdi-file-document-outline",
            href: `${repositoryBaseUrl}/blob/main/docs/architecture/initiatives/s17_unified_owner_feedback_loop/design_doc.md`,
          },
        ],
        workflowPresetIds: ["preset-revise-loop", "preset-handover-boundary"],
        sourceRefs: [
          "docs/architecture/initiatives/s17_unified_owner_feedback_loop/design_doc.md",
          "docs/architecture/adr/ADR-0017-unified-owner-feedback-loop-live-wait-primary-platform-owned-continuation.md",
        ],
      },
      {
        detailId: "detail-run-s17-live-wait",
        nodeId: "run-s17-live-wait",
        overviewMarkdown:
          "Fake-data mirror того, как live wait и owner inbox выглядели бы на общем полотне. Узел нужен для explicit relation story и не является live runtime truth в Sprint S18.",
        timelineItems: [
          {
            itemId: "timeline-run-s17-1",
            happenedAt: "2026-04-09T12:40:00Z",
            title: "Telegram + staff fallback remain paired",
            summary: "Prototype показывает continuity story, но не открывает новый runtime path.",
            tone: "neutral",
          },
        ],
        relatedNodeIds: ["issue-582", "pr-s17-feedback"],
        safeActions: [
          {
            actionId: "action-open-s17-doc",
            kind: "doc",
            label: "Открыть S17 traceability",
            description: "История delivery и ownership split для feedback loop.",
            icon: "mdi-timeline-text-outline",
            href: `${repositoryBaseUrl}/blob/main/docs/delivery/traceability/s17_unified_user_interaction_waits_and_owner_feedback_inbox_history.md`,
          },
        ],
        workflowPresetIds: ["preset-revise-loop"],
        sourceRefs: [
          "docs/delivery/traceability/s17_unified_user_interaction_waits_and_owner_feedback_inbox_history.md",
        ],
      },
      {
        detailId: "detail-pr-s17-feedback",
        nodeId: "pr-s17-feedback",
        overviewMarkdown:
          "Companion PR в соседнем stream. Здесь акцент не на merge, а на том, что canvas прототип умеет показывать cross-stream relation и quality impact без смешения owner-managed scope.",
        timelineItems: [
          {
            itemId: "timeline-pr-s17-1",
            happenedAt: "2026-04-09T12:50:00Z",
            title: "Companion PR remains evidence-only in this walkthrough",
            summary: "Нет live mutation CTA и нет cross-branch orchestration внутри prototype.",
            tone: "attention",
          },
        ],
        relatedNodeIds: ["issue-582", "issue-524"],
        safeActions: [
          {
            actionId: "action-open-pr-feedback",
            kind: "link",
            label: "Открыть feedback PR",
            description: "GitHub PR соседнего delivery stream.",
            icon: "mdi-source-pull",
            href: `${repositoryBaseUrl}/pull/584`,
          },
        ],
        workflowPresetIds: ["preset-revise-loop"],
        sourceRefs: ["services/jobs/agent-runner/internal/runner/templates/prompt_blocks/pr_contract_revise_ru.tmpl"],
      },
      {
        detailId: "detail-issue-524",
        nodeId: "issue-524",
        overviewMarkdown:
          "Quality governance gate отображается как отдельный блокирующий узел. Он удерживает release-safe semantics вне текущего prototype PR, но остаётся видимым для owner decision на одном полотне.",
        timelineItems: [
          {
            itemId: "timeline-524-1",
            happenedAt: "2026-03-25T09:00:00Z",
            title: "Blocked until owner approval of frontend baseline",
            summary: "Issue #524 intentionally remains outside the current run:dev scope.",
            tone: "warning",
          },
        ],
        relatedNodeIds: ["run-quality-smoke", "pr-s18-owner-demo"],
        safeActions: [
          {
            actionId: "action-open-524",
            kind: "link",
            label: "Открыть Issue #524",
            description: "Quality governance follow-up, который нельзя скрыто тянуть в Sprint S18 prototype.",
            icon: "mdi-open-in-new",
            href: `${repositoryBaseUrl}/issues/524`,
          },
          {
            actionId: "action-open-quality-doc",
            kind: "doc",
            label: "Открыть quality governance docs",
            description: "Контекст для release-safe evidence и owner approval gate.",
            icon: "mdi-file-document-outline",
            href: `${repositoryBaseUrl}/blob/main/docs/architecture/initiatives/s13_quality_governance_system/design_doc.md`,
          },
        ],
        workflowPresetIds: ["preset-evidence-gate"],
        sourceRefs: ["docs/architecture/initiatives/s13_quality_governance_system/design_doc.md"],
      },
      {
        detailId: "detail-run-quality-smoke",
        nodeId: "run-quality-smoke",
        overviewMarkdown:
          "Demo-only evidence lane: checklist, traceability и локальный localhost preview. Run существует, чтобы owner видел, как prototype удерживает quality gate без live release cockpit.",
        timelineItems: [
          {
            itemId: "timeline-quality-run-1",
            happenedAt: "2026-04-09T15:10:00Z",
            title: "Local preview prepared",
            summary: "Prototype can be reviewed on localhost via temporary .local/temp helper.",
            tone: "positive",
          },
        ],
        relatedNodeIds: ["issue-524", "pr-s18-owner-demo"],
        safeActions: [
          {
            actionId: "action-open-quality-doc",
            kind: "doc",
            label: "Открыть quality checklist context",
            description: "Сверить, что prototype сохранил explicit quality gate.",
            icon: "mdi-clipboard-check-outline",
            href: `${repositoryBaseUrl}/blob/main/docs/design-guidelines/common/check_list.md`,
          },
        ],
        workflowPresetIds: ["preset-evidence-gate"],
        sourceRefs: ["docs/design-guidelines/common/check_list.md"],
      },
    ],
    workflowPresets: [
      {
        presetId: "preset-owner-demo",
        label: "Owner demo lane",
        summary: "Показывает минимальный, но полный dev->review->owner handover без открытия backend scope.",
        defaultDraft: {
          stageSequenceVariant: "owner_demo",
          autoReviewPolicy: "required",
          followUpPolicy: "carry_to_next_stage",
          safeActionProfile: "github_links_only",
        },
        stageSequenceOptions: {
          full_delivery: ["run:dev", "need:reviewer", "state:in-review", "owner-review"],
          owner_demo: ["run:dev", "owner-demo", "approve-or-revise"],
          revise_loop: ["run:dev", "run:dev:revise", "owner-review"],
        },
        promptSeedRefs: [
          "services/jobs/agent-runner/internal/runner/templates/prompt_blocks/issue_contract_ru.tmpl",
          "services/jobs/agent-runner/internal/runner/templates/prompt_blocks/pr_contract_work_ru.tmpl",
        ],
        generatedBlockSeed: "mission-control-owner-demo",
        allowedOverrides: ["stageSequenceVariant", "autoReviewPolicy", "followUpPolicy", "safeActionProfile"],
      },
      {
        presetId: "preset-revise-loop",
        label: "Revise loop without drift",
        summary: "Оставляет route owner-managed, но добавляет явный revise path и continuity для PR feedback.",
        defaultDraft: {
          stageSequenceVariant: "revise_loop",
          autoReviewPolicy: "paired_reviewer",
          followUpPolicy: "owner_managed",
          safeActionProfile: "preview_only",
        },
        stageSequenceOptions: {
          full_delivery: ["run:dev", "need:reviewer", "run:dev:revise", "owner-review"],
          owner_demo: ["run:dev", "owner-review"],
          revise_loop: ["run:dev", "reviewer-pass", "run:dev:revise", "owner-review"],
        },
        promptSeedRefs: [
          "services/jobs/agent-runner/internal/runner/templates/prompt_blocks/pr_contract_revise_ru.tmpl",
          "docs/architecture/prompt_templates_policy.md",
        ],
        generatedBlockSeed: "mission-control-revise-loop",
        allowedOverrides: ["stageSequenceVariant", "autoReviewPolicy", "followUpPolicy"],
      },
      {
        presetId: "preset-evidence-gate",
        label: "Evidence gate",
        summary: "Подсвечивает checks, traceability и owner approval как явный quality gate.",
        defaultDraft: {
          stageSequenceVariant: "full_delivery",
          autoReviewPolicy: "required",
          followUpPolicy: "spawn_issue_on_gap",
          safeActionProfile: "candidate_readonly",
        },
        stageSequenceOptions: {
          full_delivery: ["run:dev", "need:reviewer", "need:qa", "owner-approval"],
          owner_demo: ["run:dev", "demo-evidence", "owner-approval"],
          revise_loop: ["run:dev", "traceability-fix", "owner-approval"],
        },
        promptSeedRefs: [
          "docs/delivery/development_process_requirements.md",
          "docs/design-guidelines/common/check_list.md",
        ],
        generatedBlockSeed: "mission-control-evidence-gate",
        allowedOverrides: ["stageSequenceVariant", "followUpPolicy", "safeActionProfile"],
      },
      {
        presetId: "preset-handover-boundary",
        label: "Deferred backend seam",
        summary: "Явно показывает, что backend rebuild остаётся follow-up и не раскрывается в этом prototype PR.",
        defaultDraft: {
          stageSequenceVariant: "owner_demo",
          autoReviewPolicy: "owner_only",
          followUpPolicy: "owner_managed",
          safeActionProfile: "github_links_only",
        },
        stageSequenceOptions: {
          full_delivery: ["owner-approval", "handover", "backend-rebuild"],
          owner_demo: ["owner-approval", "explicit-handover"],
          revise_loop: ["owner-approval", "revisit-boundary"],
        },
        promptSeedRefs: [
          "docs/architecture/initiatives/s18_mission_control_frontend_first_canvas/architecture.md",
          "docs/architecture/adr/ADR-0018-mission-control-frontend-first-prototype-and-backend-handover-boundary.md",
        ],
        generatedBlockSeed: "mission-control-deferred-seam",
        allowedOverrides: ["stageSequenceVariant", "safeActionProfile"],
      },
    ],
  },
  {
    scenarioId: "review-pressure",
    title: "Review pressure: owner feedback and revise loop",
    summary: "Более узкий сценарий для просмотра workflow preview и revision discipline без смены UX baseline.",
    defaultFocusInitiativeId: "initiative-review",
    defaultViewport: {
      zoomLevel: 1,
      panX: 10,
      panY: 10,
      canvasWidth: 1380,
      canvasHeight: 860,
    },
    sourceRefs: [
      "docs/delivery/development_process_requirements.md",
      "services/jobs/agent-runner/internal/runner/templates/prompt_blocks/pr_contract_revise_ru.tmpl",
      "docs/architecture/prompt_templates_policy.md",
    ],
    initiatives: [
      {
        initiativeId: "initiative-review",
        label: "Owner review loop",
        accentToken: "lime",
        focusOrder: 0,
        nodeIds: ["issue-581-review", "pr-581-review", "run-reviewer"],
      },
      {
        initiativeId: "initiative-handover",
        label: "Deferred handover",
        accentToken: "slate",
        focusOrder: 1,
        nodeIds: ["issue-563-review", "issue-524-review", "run-checklist"],
      },
    ],
    nodes: [
      {
        nodeId: "issue-581-review",
        nodeKind: "Issue",
        initiativeId: "initiative-review",
        title: "Issue #581 · revise-ready walkthrough",
        state: "working",
        stageLabel: "owner feedback loop",
        layoutX: 120,
        layoutY: 190,
        meta: ["route shell", "prototype store"],
        badges: ["handover"],
        detailId: "detail-issue-581-review",
        safeActionIds: ["action-open-581", "action-preview-workflow"],
      },
      {
        nodeId: "pr-581-review",
        nodeKind: "PR",
        initiativeId: "initiative-review",
        title: "PR · revise notes and owner comments",
        state: "review",
        stageLabel: "comment threads",
        layoutX: 470,
        layoutY: 180,
        meta: ["reviewer", "owner notes"],
        badges: ["owner-review"],
        detailId: "detail-pr-581-review",
        safeActionIds: ["action-open-pr-demo", "action-preview-workflow"],
      },
      {
        nodeId: "run-reviewer",
        nodeKind: "Run",
        initiativeId: "initiative-review",
        title: "Reviewer sweep",
        state: "waiting",
        stageLabel: "structured findings only",
        layoutX: 820,
        layoutY: 200,
        meta: ["findings", "owner handoff"],
        badges: ["needs-evidence"],
        detailId: "detail-run-reviewer",
        safeActionIds: ["action-open-s18-doc", "action-preview-workflow"],
      },
      {
        nodeId: "issue-563-review",
        nodeKind: "Issue",
        initiativeId: "initiative-handover",
        title: "Issue #563 · stays deferred",
        state: "waiting",
        stageLabel: "separate flow",
        layoutX: 270,
        layoutY: 540,
        meta: ["backend only"],
        badges: ["deferred"],
        detailId: "detail-issue-563-review",
        safeActionIds: ["action-open-563"],
      },
      {
        nodeId: "issue-524-review",
        nodeKind: "Issue",
        initiativeId: "initiative-handover",
        title: "Issue #524 · quality gate still visible",
        state: "blocked",
        stageLabel: "approval gate",
        layoutX: 650,
        layoutY: 520,
        meta: ["release-safe", "evidence"],
        badges: ["blocked"],
        detailId: "detail-issue-524-review",
        safeActionIds: ["action-open-524", "action-open-quality-doc"],
      },
      {
        nodeId: "run-checklist",
        nodeKind: "Run",
        initiativeId: "initiative-handover",
        title: "Checklist replay",
        state: "working",
        stageLabel: "local verification",
        layoutX: 1010,
        layoutY: 540,
        meta: ["build", "tests", "localhost"],
        badges: ["demo-ready"],
        detailId: "detail-run-checklist",
        safeActionIds: ["action-open-quality-doc", "action-preview-workflow"],
      },
    ],
    relations: [
      {
        relationId: "rel-review-issue-pr",
        relationKind: "tracks",
        sourceNodeId: "issue-581-review",
        targetNodeId: "pr-581-review",
        label: "issue stays continuity anchor",
        importance: "primary",
      },
      {
        relationId: "rel-review-pr-run",
        relationKind: "drives",
        sourceNodeId: "pr-581-review",
        targetNodeId: "run-reviewer",
        label: "review package triggers findings sweep",
        importance: "supporting",
      },
      {
        relationId: "rel-review-block-boundary",
        relationKind: "blocks",
        sourceNodeId: "issue-524-review",
        targetNodeId: "pr-581-review",
        label: "quality gate remains explicit",
        importance: "primary",
      },
      {
        relationId: "rel-review-pr-blocks-backend",
        relationKind: "blocks",
        sourceNodeId: "pr-581-review",
        targetNodeId: "issue-563-review",
        label: "owner approval before backend handover",
        importance: "primary",
      },
      {
        relationId: "rel-quality-run",
        relationKind: "drives",
        sourceNodeId: "issue-524-review",
        targetNodeId: "run-checklist",
        label: "checklist replay stays local",
        importance: "supporting",
      },
    ],
    drawerRecords: [
      {
        detailId: "detail-issue-581-review",
        nodeId: "issue-581-review",
        overviewMarkdown:
          "Сценарий для owner feedback. Здесь важно не то, сколько live данных на полотне, а насколько ясно workflow preview и revise discipline отделены от backend follow-up.",
        timelineItems: [
          {
            itemId: "timeline-review-1",
            happenedAt: "2026-04-09T15:40:00Z",
            title: "Route now speaks prototype semantics",
            summary: "Scenario, node and tab state живут отдельно от legacy realtime path.",
            tone: "positive",
          },
        ],
        relatedNodeIds: ["pr-581-review", "run-reviewer"],
        safeActions: [
          {
            actionId: "action-open-581",
            kind: "link",
            label: "Открыть Issue #581",
            description: "Вернуться к основному delivery anchor.",
            icon: "mdi-open-in-new",
            href: `${repositoryBaseUrl}/issues/581`,
          },
        ],
        workflowPresetIds: ["preset-revise-loop", "preset-owner-demo"],
        sourceRefs: ["docs/delivery/development_process_requirements.md"],
      },
      {
        detailId: "detail-pr-581-review",
        nodeId: "pr-581-review",
        overviewMarkdown:
          "PR в этом сценарии показывает comment-ready surface: findings, revise loop, owner summary и отсутствие скрытых mutation CTA.",
        timelineItems: [
          {
            itemId: "timeline-review-pr-1",
            happenedAt: "2026-04-09T15:45:00Z",
            title: "Workflow tab kept deterministic",
            summary: "Prompt free-text editor intentionally absent.",
            tone: "attention",
          },
        ],
        relatedNodeIds: ["issue-581-review", "issue-524-review"],
        safeActions: [
          {
            actionId: "action-open-pr-demo",
            kind: "link",
            label: "Открыть draft PR",
            description: "Посмотреть owner-ready PR package.",
            icon: "mdi-source-pull",
          },
        ],
        workflowPresetIds: ["preset-revise-loop"],
        sourceRefs: ["services/jobs/agent-runner/internal/runner/templates/prompt_blocks/pr_contract_revise_ru.tmpl"],
      },
      {
        detailId: "detail-run-reviewer",
        nodeId: "run-reviewer",
        overviewMarkdown:
          "Reviewer sweep — это локальная policy preview и findings discipline. В прототипе он не отправляет команды вовне и остаётся объясняющим узлом на полотне.",
        timelineItems: [
          {
            itemId: "timeline-review-run-1",
            happenedAt: "2026-04-09T15:50:00Z",
            title: "Structured findings only",
            summary: "Review UI держит risk-first wording и не размывает acceptance evidence.",
            tone: "neutral",
          },
        ],
        relatedNodeIds: ["pr-581-review"],
        safeActions: [
          {
            actionId: "action-preview-workflow",
            kind: "preview",
            label: "Открыть policy preview",
            description: "Сверить deterministic block для reviewer loop.",
            icon: "mdi-code-braces",
          },
        ],
        workflowPresetIds: ["preset-revise-loop"],
        sourceRefs: ["docs/architecture/prompt_templates_policy.md"],
      },
      {
        detailId: "detail-issue-563-review",
        nodeId: "issue-563-review",
        overviewMarkdown: "Backend seam остаётся видимым, но deferred. Этот узел специально не тянет никаких transport или schema prerequisites в текущий PR.",
        timelineItems: [],
        relatedNodeIds: ["pr-581-review"],
        safeActions: [
          {
            actionId: "action-open-563",
            kind: "link",
            label: "Открыть Issue #563",
            description: "Отдельный backend follow-up.",
            icon: "mdi-open-in-new",
            href: `${repositoryBaseUrl}/issues/563`,
          },
        ],
        workflowPresetIds: ["preset-handover-boundary"],
        sourceRefs: ["docs/architecture/initiatives/s18_mission_control_frontend_first_canvas/architecture.md"],
      },
      {
        detailId: "detail-issue-524-review",
        nodeId: "issue-524-review",
        overviewMarkdown: "Quality gate сохраняется как явный блокирующий слой. Он удерживает owner approval semantics вне canvas prototype implementation scope.",
        timelineItems: [],
        relatedNodeIds: ["pr-581-review", "run-checklist"],
        safeActions: [
          {
            actionId: "action-open-524",
            kind: "link",
            label: "Открыть Issue #524",
            description: "Просмотреть blocked governance stream.",
            icon: "mdi-open-in-new",
            href: `${repositoryBaseUrl}/issues/524`,
          },
        ],
        workflowPresetIds: ["preset-evidence-gate"],
        sourceRefs: ["docs/architecture/initiatives/s13_quality_governance_system/design_doc.md"],
      },
      {
        detailId: "detail-run-checklist",
        nodeId: "run-checklist",
        overviewMarkdown: "Локальный checklist replay нужен для owner demo и проверки PR package: build, unit tests и localhost preview.",
        timelineItems: [],
        relatedNodeIds: ["issue-524-review"],
        safeActions: [
          {
            actionId: "action-open-quality-doc",
            kind: "doc",
            label: "Открыть check list",
            description: "Сверить общие quality gates перед PR.",
            icon: "mdi-clipboard-check-outline",
            href: `${repositoryBaseUrl}/blob/main/docs/design-guidelines/common/check_list.md`,
          },
        ],
        workflowPresetIds: ["preset-evidence-gate"],
        sourceRefs: ["docs/design-guidelines/common/check_list.md"],
      },
    ],
    workflowPresets: [],
  },
];
