apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-gateway
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: integration-gateway
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 1Gi
        - name: internal-rpc-authority-issuer
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
