// Code generated by normalize-control-api-gateway-asyncapi.sh. DO NOT EDIT.

package generated

import (
	"encoding/json"
	"errors"
)

func (value SnapshotItems) MarshalJSON() ([]byte, error) {
	switch {
	case value.Resources != nil && value.Incidents == nil && value.ConfigurationChanges == nil:
		return json.Marshal(map[string]any{"resources": value.Resources})
	case value.Resources == nil && value.Incidents != nil && value.ConfigurationChanges == nil:
		return json.Marshal(map[string]any{"incidents": value.Incidents})
	case value.Resources == nil && value.Incidents == nil && value.ConfigurationChanges != nil:
		return json.Marshal(map[string]any{"configurationChanges": value.ConfigurationChanges})
	default:
		return nil, errors.New("snapshot items must contain exactly one projection")
	}
}
