apiVersion: v1
kind: ConfigMap
metadata:
  name: internal-rpc-authority-database-credential-reconciler
  labels:
    app.kubernetes.io/name: internal-rpc-authority
    app.kubernetes.io/component: database-credential-reconciler
data:
  INTERNAL_RPC_AUTHORITY_RECONCILER_LISTEN: ":8443"
  INTERNAL_RPC_AUTHORITY_TECHNICAL_LISTEN: ":9090"
  INTERNAL_RPC_AUTHORITY_RECONCILER_CALLER_SPIFFE_ID: "spiffe://mattercodex.local/ns/mattercodex-system/sa/internal-rpc-authority-publisher"
  INTERNAL_RPC_AUTHORITY_POSTGRES_TLS_SERVER_NAME: "internal-rpc-authority-postgresql.mattercodex-system.svc.cluster.local"
  INTERNAL_RPC_AUTHORITY_POSTGRES_EXPECTED_SESSION_USER: "ira_database_credential_reconciler"
  INTERNAL_RPC_AUTHORITY_VAULT_ADDRESS: "https://vault.mattercodex-system.svc:8200"
  INTERNAL_RPC_AUTHORITY_VAULT_TLS_SERVER_NAME: "vault.mattercodex-system.svc.cluster.local"
  INTERNAL_RPC_AUTHORITY_VAULT_AUTH_ROLE: "internal-rpc-authority-database-credential-reconciler"
  INTERNAL_RPC_AUTHORITY_REGISTERED_SET_SOURCE_REVISION: "1"
  INTERNAL_RPC_AUTHORITY_REGISTERED_SET_SOURCE_DIGEST_SHA256: "6af05d7699ab82ecaf2295ea4abf0164e81c2e5b5fe731f89f2a801c12163664"
