apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kodex-system
resources:
  - serviceaccount.yaml
  - configmap.yaml
  - vault-secret-provider-class.yaml
  - deployment.yaml
  - service.yaml
  - poddisruptionbudget.yaml
  - networkpolicy.yaml
  - credential-rollout-rbac.yaml
  - prometheusrule.yaml
  - dashboard.yaml
  - servicemonitor.yaml
