apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: internal-rpc-authority-database-credential-reconciler
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: internal-rpc-authority
      app.kubernetes.io/component: database-credential-reconciler
