apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-rpc-authority-database-credential-reconciler
  labels:
    app.kubernetes.io/name: internal-rpc-authority
    app.kubernetes.io/component: database-credential-reconciler
automountServiceAccountToken: false
