package service

const (
	projectEventProjectCreated           = "project.project.created"
	projectEventProjectUpdated           = "project.project.updated"
	projectEventProjectArchived          = "project.project.archived"
	projectEventProjectDisabled          = "project.project.disabled"
	projectEventRepositoryAttached       = "project.repository.attached"
	projectEventRepositoryUpdated        = "project.repository.updated"
	projectEventRepositoryDetached       = "project.repository.detached"
	projectEventServicesPolicyImported   = "project.services_policy.imported"
	projectEventPolicyOverrideCreated    = "project.policy_override.created"
	projectEventPolicyOverrideCancelled  = "project.policy_override.cancelled"
	projectEventDocumentationCreated     = "project.documentation_source.created"
	projectEventDocumentationUpdated     = "project.documentation_source.updated"
	projectEventDocumentationDisabled    = "project.documentation_source.disabled"
	projectEventBranchRulesCreated       = "project.branch_rules.created"
	projectEventBranchRulesUpdated       = "project.branch_rules.updated"
	projectEventBranchRulesDisabled      = "project.branch_rules.disabled"
	projectEventReleasePolicyCreated     = "project.release_policy.created"
	projectEventReleasePolicyUpdated     = "project.release_policy.updated"
	projectEventReleasePolicyArchived    = "project.release_policy.archived"
	projectEventReleasePolicyDisabled    = "project.release_policy.disabled"
	projectEventReleaseLineCreated       = "project.release_line.created"
	projectEventReleaseLineUpdated       = "project.release_line.updated"
	projectEventReleaseLineArchived      = "project.release_line.archived"
	projectEventReleaseLineDisabled      = "project.release_line.disabled"
	projectEventPlacementPolicyCreated   = "project.placement_policy.created"
	projectEventPlacementPolicyUpdated   = "project.placement_policy.updated"
	projectEventPlacementPolicyDisabled  = "project.placement_policy.disabled"
	projectAggregateProject              = "project"
	projectAggregateRepository           = "repository"
	projectAggregateServicesPolicy       = "services_policy"
	projectAggregatePolicyOverride       = "policy_override"
	projectAggregateDocumentationSource  = "documentation_source"
	projectAggregateBranchRules          = "branch_rules"
	projectAggregateReleasePolicy        = "release_policy"
	projectAggregateReleaseLine          = "release_line"
	projectAggregatePlacementPolicy      = "placement_policy"
	projectOperationCreateProject        = "domain.Service.CreateProject"
	projectOperationUpdateProject        = "domain.Service.UpdateProject"
	projectOperationAttachRepository     = "domain.Service.AttachRepository"
	projectOperationUpdateRepository     = "domain.Service.UpdateRepository"
	projectOperationDetachRepository     = "domain.Service.DetachRepository"
	projectOperationImportServicesPolicy = "domain.Service.ImportServicesPolicy"
	projectOperationPolicyEditProposal   = "domain.Service.CreatePolicyEditProposal"
	projectOperationPolicyOverride       = "domain.Service.CreatePolicyOverride"
	projectOperationCancelPolicyOverride = "domain.Service.CancelPolicyOverride"
	projectOperationPutDocumentation     = "domain.Service.PutDocumentationSource"
	projectOperationPutBranchRules       = "domain.Service.PutBranchRules"
	projectOperationPutReleasePolicy     = "domain.Service.PutReleasePolicy"
	projectOperationPutReleaseLine       = "domain.Service.PutReleaseLine"
	projectOperationPutPlacementPolicy   = "domain.Service.PutPlacementPolicy"
	projectActionCreate                  = "project.create"
	projectActionUpdate                  = "project.update"
	projectActionRead                    = "project.read"
	projectActionList                    = "project.list"
	projectActionRepositoryAttach        = "repository.attach"
	projectActionRepositoryUpdate        = "repository.update"
	projectActionRepositoryDetach        = "repository.detach"
	projectActionRepositoryRead          = "repository.read"
	projectActionRepositoryList          = "repository.list"
	projectActionPolicyImport            = "project.policy.import"
	projectActionPolicyRead              = "project.policy.read"
	projectActionPolicyPropose           = "project.policy.propose"
	projectActionPolicyOverride          = "project.policy.override"
	projectActionPolicyOverrideRead      = "project.policy.override.read"
	projectActionPolicyOverrideCancel    = "project.policy.override.cancel"
	projectActionDocsUpdate              = "project.docs.update"
	projectActionDocsRead                = "project.docs.read"
	projectActionWorkspaceRead           = "project.workspace.read"
	projectActionBranchRulesUpdate       = "project.branch_rules.update"
	projectActionBranchRulesRead         = "project.branch_rules.read"
	projectActionReleasePolicyUpdate     = "project.release_policy.update"
	projectActionReleasePolicyRead       = "project.release_policy.read"
	projectActionReleaseLineUpdate       = "project.release_line.update"
	projectActionReleaseLineRead         = "project.release_line.read"
	projectActionPlacementPolicyUpdate   = "project.placement_policy.update"
	projectActionPlacementPolicyRead     = "project.placement_policy.read"
	projectProposalStatusPending         = "pending"
)

const schemaVersionProjectEventV1 = 1

type resourceRef struct {
	Type      string
	ID        string
	ScopeType string
	ScopeID   string
}
