apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: interaction-gateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: interaction-gateway
      app.kubernetes.io/component: external-gateway
