apiVersion: v1
kind: Service
metadata:
  name: interaction-gateway
  labels:
    app.kubernetes.io/name: interaction-gateway
    app.kubernetes.io/component: interaction-adapter
spec:
  selector:
    app.kubernetes.io/name: interaction-gateway
    app.kubernetes.io/component: interaction-adapter
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
    - name: auth-metrics
      port: 9091
      targetPort: auth-metrics
      protocol: TCP
