apiVersion: v1
kind: ServiceAccount
metadata:
  name: interaction-gateway
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: interaction-gateway-migrator
automountServiceAccountToken: true
