apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kodex-system
resources:
  - ../../../base/integration-synthetic
labels:
  - pairs:
      kodex.dev/local-profile: hot-reload
      kodex.dev/profile: e2e
    includeSelectors: false
    includeTemplates: true
