apiVersion: v1
kind: ConfigMap
metadata:
  name: ${MATTERCODEX_BOT_SERVICE_CONFIG_CONFIGMAP}
  namespace: ${MATTERCODEX_NAMESPACE}
  labels:
    app.kubernetes.io/name: matter-codex-bot-service
    app.kubernetes.io/component: bot-service-config
data:
  MATTERCODEX_BOT_SERVICE_HTTP_ADDR: "${MATTERCODEX_BOT_SERVICE_HTTP_ADDR}"
  MATTERCODEX_BOT_SERVICE_SITE_URL: "${MATTERCODEX_BOT_SERVICE_SITE_URL}"
  MATTERCODEX_BOT_SERVICE_INTERNAL_URL: "${MATTERCODEX_BOT_SERVICE_INTERNAL_URL}"
  MATTERCODEX_MATTERMOST_SITE_URL: "${MATTERCODEX_MATTERMOST_SITE_URL}"
  MATTERCODEX_MATTERMOST_INTERNAL_URL: "${MATTERCODEX_MATTERMOST_INTERNAL_URL}"
  MATTERCODEX_LOCALE: "${MATTERCODEX_LOCALE}"
  MATTERCODEX_DEFAULT_TEAM_NAME: "${MATTERCODEX_DEFAULT_TEAM_NAME}"
  MATTERCODEX_DEFAULT_CHANNELS: "${MATTERCODEX_DEFAULT_CHANNELS}"
  MATTERCODEX_RUNTIME_ENABLED: "${MATTERCODEX_RUNTIME_ENABLED}"
  MATTERCODEX_RUNTIME_NAMESPACE: "${MATTERCODEX_RUNTIME_NAMESPACE}"
  MATTERCODEX_RUNTIME_SMOKE_IMAGE: "${MATTERCODEX_RUNTIME_SMOKE_IMAGE}"
  MATTERCODEX_AGENT_RUNNER_IMAGE: "${MATTERCODEX_AGENT_RUNNER_IMAGE}"
  MATTERCODEX_CODEX_PACKAGE: "${MATTERCODEX_CODEX_PACKAGE}"
  MATTERCODEX_RUNTIME_WORKSPACE_STORAGE_SIZE: "${MATTERCODEX_RUNTIME_WORKSPACE_STORAGE_SIZE}"
  MATTERCODEX_RUNTIME_JOB_TTL_SECONDS: "${MATTERCODEX_RUNTIME_JOB_TTL_SECONDS}"
  MATTERCODEX_RUNTIME_LOG_TAIL_LINES: "${MATTERCODEX_RUNTIME_LOG_TAIL_LINES}"
  MATTERCODEX_AGENT_RUNNER_SERVICE_ACCOUNT: "${MATTERCODEX_AGENT_RUNNER_SERVICE_ACCOUNT}"
  MATTERCODEX_CODEX_AUTH_SECRET: "${MATTERCODEX_CODEX_AUTH_SECRET}"
  MATTERCODEX_GITHUB_SECRET: "${MATTERCODEX_GITHUB_SECRET}"
  MATTERCODEX_STORAGE_MIGRATIONS_ENABLED: "${MATTERCODEX_STORAGE_MIGRATIONS_ENABLED}"
  MATTERCODEX_BOT_SERVICE_MAX_GITHUB_WEBHOOK_BYTES: "${MATTERCODEX_BOT_SERVICE_MAX_GITHUB_WEBHOOK_BYTES}"
