apiVersion: v1
kind: ConfigMap
metadata:
  name: ${MATTERCODEX_BOT_SERVICE_CONFIG_CONFIGMAP}
  namespace: ${MATTERCODEX_NAMESPACE}
  labels:
    app.kubernetes.io/name: matter-codex-bot-service
    app.kubernetes.io/component: bot-service-config
data:
  MATTERCODEX_BOT_SERVICE_HTTP_ADDR: "${MATTERCODEX_BOT_SERVICE_HTTP_ADDR}"
  MATTERCODEX_BOT_SERVICE_SITE_URL: "${MATTERCODEX_BOT_SERVICE_SITE_URL}"
  MATTERCODEX_MATTERMOST_SITE_URL: "${MATTERCODEX_MATTERMOST_SITE_URL}"
  MATTERCODEX_DEFAULT_TEAM_NAME: "${MATTERCODEX_DEFAULT_TEAM_NAME}"
  MATTERCODEX_DEFAULT_CHANNELS: "${MATTERCODEX_DEFAULT_CHANNELS}"
