apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: control-api-gateway
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  ingressClassName: nginx
  tls:
    - hosts: [control-api.kodex.local]
  rules:
    - host: control-api.kodex.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: {name: control-api-gateway, port: {name: https}}
