apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: {name: control-api-gateway}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: control-api-gateway
      app.kubernetes.io/component: external-gateway
