apiVersion: v1
kind: Service
metadata:
  name: control-api-gateway
  labels: {app.kubernetes.io/name: control-api-gateway}
spec:
  selector:
    app.kubernetes.io/name: control-api-gateway
    app.kubernetes.io/component: external-gateway
  ports:
    - {name: https, port: 8443, targetPort: https, protocol: TCP}
    - {name: metrics, port: 9090, targetPort: metrics, protocol: TCP}
