apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mattercodex-image-signer
spec:
  provider: vault
  parameters:
    roleName: mattercodex-image-admission
    objects: |
      - objectName: cosign.key
        secretPath: kv/data/mattercodex/image-admission/signing
        secretKey: private_key
      - objectName: cosign.pub
        secretPath: kv/data/mattercodex/image-admission/signing
        secretKey: public_key
      - objectName: cosign.password
        secretPath: kv/data/mattercodex/image-admission/signing
        secretKey: password
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mattercodex-image-admission-owner
spec:
  provider: vault
  parameters:
    roleName: mattercodex-image-admission
    objects: |
      - objectName: admission.key
        secretPath: kv/data/mattercodex/image-admission/admission
        secretKey: private_key
      - objectName: admission.pub
        secretPath: kv/data/mattercodex/image-admission/admission
        secretKey: public_key
      - objectName: admission.password
        secretPath: kv/data/mattercodex/image-admission/admission
        secretKey: password
      - objectName: cosign.pub
        secretPath: kv/data/mattercodex/image-admission/signing
        secretKey: public_key
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mattercodex-image-promotion-verifier
spec:
  provider: vault
  parameters:
    roleName: mattercodex-image-admission
    objects: |
      - objectName: admission.pub
        secretPath: kv/data/mattercodex/image-admission/admission
        secretKey: public_key
