apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mattercodex-buildkit-tls
spec:
  provider: vault
  parameters:
    roleName: mattercodex-buildkit
    objects: |
      - objectName: server.crt
        secretPath: pki/issue/mattercodex-buildkit-server
        secretKey: certificate
        method: PUT
        secretArgs:
          common_name: mattercodex-buildkit.mattercodex-system.svc.cluster.local
          alt_names: mattercodex-buildkit,mattercodex-buildkit.mattercodex-system.svc,mattercodex-buildkit.mattercodex-system.svc.cluster.local
          ttl: 1h
      - objectName: server.key
        secretPath: pki/issue/mattercodex-buildkit-server
        secretKey: private_key
        method: PUT
        secretArgs:
          common_name: mattercodex-buildkit.mattercodex-system.svc.cluster.local
          alt_names: mattercodex-buildkit,mattercodex-buildkit.mattercodex-system.svc,mattercodex-buildkit.mattercodex-system.svc.cluster.local
          ttl: 1h
      - objectName: probe.crt
        secretPath: pki/issue/mattercodex-buildkit-probe
        secretKey: certificate
        method: PUT
        secretArgs:
          common_name: mattercodex-buildkit-probe
          alt_names: mattercodex-buildkit-probe.mattercodex-system.svc
          ttl: 30m
      - objectName: probe.key
        secretPath: pki/issue/mattercodex-buildkit-probe
        secretKey: private_key
        method: PUT
        secretArgs:
          common_name: mattercodex-buildkit-probe
          alt_names: mattercodex-buildkit-probe.mattercodex-system.svc
          ttl: 30m
      - objectName: ca.pem
        secretPath: pki/cert/ca
        secretKey: certificate
      - objectName: base-registry-client.crt
        secretPath: pki/issue/mattercodex-buildkit-base-pull
        secretKey: certificate
        method: PUT
        secretArgs:
          common_name: mattercodex-buildkit-base-pull
          ttl: 30m
      - objectName: base-registry-client.key
        secretPath: pki/issue/mattercodex-buildkit-base-pull
        secretKey: private_key
        method: PUT
        secretArgs:
          common_name: mattercodex-buildkit-base-pull
          ttl: 30m
      - objectName: staging-registry-client.crt
        secretPath: pki/issue/mattercodex-buildkit-staging-push
        secretKey: certificate
        method: PUT
        secretArgs:
          common_name: mattercodex-buildkit-staging-push
          ttl: 30m
      - objectName: staging-registry-client.key
        secretPath: pki/issue/mattercodex-buildkit-staging-push
        secretKey: private_key
        method: PUT
        secretArgs:
          common_name: mattercodex-buildkit-staging-push
          ttl: 30m
