debug = false
root = "/var/lib/buildkit"

[grpc]
  address = ["tcp://0.0.0.0:1234"]
  [grpc.tls]
    ca = "/var/run/secrets/kodex/buildkit/tls/ca.pem"
    cert = "/var/run/secrets/kodex/buildkit/tls/server.crt"
    key = "/var/run/secrets/kodex/buildkit/tls/server.key"

[cdi]
  disabled = true

[worker.oci]
  enabled = true
  snapshotter = "overlayfs"
  rootless = false

[registry."kodex-image-registry-push.kodex-system.svc.cluster.local:5001"]
  ca = ["/var/run/secrets/kodex/buildkit/tls/push-ca.pem"]
  [[registry."kodex-image-registry-push.kodex-system.svc.cluster.local:5001".keypair]]
    cert = "/var/run/secrets/kodex/buildkit/tls/staging-registry-client.crt"
    key = "/var/run/secrets/kodex/buildkit/tls/staging-registry-client.key"

[registry."kodex-image-registry.kodex-system.svc.cluster.local:5000"]
  ca = ["/var/run/secrets/kodex/buildkit/tls/pull-ca.pem"]
  [[registry."kodex-image-registry.kodex-system.svc.cluster.local:5000".keypair]]
    cert = "/var/run/secrets/kodex/buildkit/tls/base-registry-client.crt"
    key = "/var/run/secrets/kodex/buildkit/tls/base-registry-client.key"
