debug = false
root = "/var/lib/buildkit"

[grpc]
  address = ["tcp://0.0.0.0:1234"]
  ca = "/var/run/secrets/mattercodex/buildkit/tls/ca.pem"
  cert = "/var/run/secrets/mattercodex/buildkit/tls/server.crt"
  key = "/var/run/secrets/mattercodex/buildkit/tls/server.key"

[worker.oci]
  enabled = true
  snapshotter = "overlayfs"
  rootless = true

[registry."mattercodex-image-registry-push.mattercodex-system.svc.cluster.local:5001"]
  ca = ["/var/run/secrets/mattercodex/buildkit/tls/push-ca.pem"]
  [[registry."mattercodex-image-registry-push.mattercodex-system.svc.cluster.local:5001".keypair]]
    cert = "/var/run/secrets/mattercodex/buildkit/tls/staging-registry-client.crt"
    key = "/var/run/secrets/mattercodex/buildkit/tls/staging-registry-client.key"

[registry."mattercodex-image-registry.mattercodex-system.svc.cluster.local:5000"]
  ca = ["/var/run/secrets/mattercodex/buildkit/tls/pull-ca.pem"]
  [[registry."mattercodex-image-registry.mattercodex-system.svc.cluster.local:5000".keypair]]
    cert = "/var/run/secrets/mattercodex/buildkit/tls/base-registry-client.crt"
    key = "/var/run/secrets/mattercodex/buildkit/tls/base-registry-client.key"
