apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mattercodex-buildkit-tls
spec:
  provider: vault
  parameters:
    roleName: mattercodex-buildkit
    objects: |
      - objectName: server.crt
        secretPath: pki/issue/mattercodex-buildkit-server
        secretKey: certificate
      - objectName: server.key
        secretPath: pki/issue/mattercodex-buildkit-server
        secretKey: private_key
      - objectName: probe.crt
        secretPath: pki/issue/mattercodex-buildkit-probe
        secretKey: certificate
      - objectName: probe.key
        secretPath: pki/issue/mattercodex-buildkit-probe
        secretKey: private_key
      - objectName: ca.pem
        secretPath: pki/issue/mattercodex-buildkit-server
        secretKey: issuing_ca
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mattercodex-role-image-builder-tls
spec:
  provider: vault
  parameters:
    roleName: mattercodex-role-image-builder
    objects: |
      - objectName: client.crt
        secretPath: pki/issue/mattercodex-buildkit-client
        secretKey: certificate
      - objectName: client.key
        secretPath: pki/issue/mattercodex-buildkit-client
        secretKey: private_key
      - objectName: ca.pem
        secretPath: pki/issue/mattercodex-buildkit-server
        secretKey: issuing_ca
