apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kodex-system
resources:
  - admission-policy.yaml
  - admission-policy-parameters.yaml
  - image-admission-controller.yaml
  - image-admission-controller-policy.yaml
  - role-environments.yaml
  - serviceaccount.yaml
  - registry.yaml
  - registry-ingress-route.yaml
  - staging-read-registry.yaml
  - evidence-registry.yaml
  - buildkit.yaml
  - cleanup.yaml
  - release-artifact-materializer.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: kodex-buildkit-config
    files:
      - buildkitd.toml
  - name: kodex-registry-cleanup
    files:
      - cleanup.sh
  - name: kodex-image-admission
    files:
      - image-admission.sh
      - provenance-policy.jq
      - vulnerability-policy.jq
  - name: kodex-registry-readiness
    files:
      - registry-readiness.sh
  - name: kodex-release-artifact-materializer
    files:
      - release-artifact-materializer.sh
generatorOptions:
  disableNameSuffixHash: true
