apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mattercodex-image-registry-pull
  annotations:
    mattercodex.dev/registry-pull-host: registry-pull.invalid
spec:
  provider: vault
  secretObjects:
    - secretName: mattercodex-image-pull
      type: kubernetes.io/dockerconfigjson
      data:
        - objectName: pull-dockerconfigjson
          key: .dockerconfigjson
  parameters:
    roleName: mattercodex-image-registry-pull
    objects: |
      - objectName: tls.crt
        secretPath: pki-public/issue/mattercodex-image-registry-pull
        secretKey: certificate
        method: PUT
        secretArgs:
          common_name: mattercodex-image-registry-pull.mattercodex-system.svc.cluster.local
          alt_names: mattercodex-image-registry-pull,mattercodex-image-registry-pull.mattercodex-system.svc,mattercodex-image-registry-pull.mattercodex-system.svc.cluster.local
          ttl: 1h
      - objectName: tls.key
        secretPath: pki-public/issue/mattercodex-image-registry-pull
        secretKey: private_key
        method: PUT
        secretArgs:
          common_name: mattercodex-image-registry-pull.mattercodex-system.svc.cluster.local
          alt_names: mattercodex-image-registry-pull,mattercodex-image-registry-pull.mattercodex-system.svc,mattercodex-image-registry-pull.mattercodex-system.svc.cluster.local
          ttl: 1h
      - objectName: auth.htpasswd
        secretPath: kv/data/mattercodex/image-registry/pull
        secretKey: htpasswd
      - objectName: pull-dockerconfigjson
        secretPath: kv/data/mattercodex/image-registry/pull
        secretKey: dockerconfigjson
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mattercodex-image-registry-push
spec:
  provider: vault
  secretObjects:
    - secretName: mattercodex-image-registry-ca
      type: Opaque
      data:
        - objectName: ca.pem
          key: ca.pem
    - secretName: mattercodex-image-push
      type: kubernetes.io/dockerconfigjson
      data:
        - objectName: push-dockerconfigjson
          key: .dockerconfigjson
    - secretName: mattercodex-image-push-client
      type: Opaque
      data:
        - objectName: push.username
          key: username
        - objectName: push.password
          key: password
  parameters:
    roleName: mattercodex-image-registry-push
    objects: |
      - objectName: tls.crt
        secretPath: pki/issue/mattercodex-image-registry-push
        secretKey: certificate
        method: PUT
        secretArgs:
          common_name: mattercodex-image-registry-push.mattercodex-system.svc.cluster.local
          alt_names: mattercodex-image-registry-push,mattercodex-image-registry-push.mattercodex-system.svc,mattercodex-image-registry-push.mattercodex-system.svc.cluster.local
          ttl: 1h
      - objectName: tls.key
        secretPath: pki/issue/mattercodex-image-registry-push
        secretKey: private_key
        method: PUT
        secretArgs:
          common_name: mattercodex-image-registry-push.mattercodex-system.svc.cluster.local
          alt_names: mattercodex-image-registry-push,mattercodex-image-registry-push.mattercodex-system.svc,mattercodex-image-registry-push.mattercodex-system.svc.cluster.local
          ttl: 1h
      - objectName: ca.pem
        secretPath: pki/cert/ca
        secretKey: certificate
      - objectName: auth.htpasswd
        secretPath: kv/data/mattercodex/image-registry/push
        secretKey: htpasswd
      - objectName: push-dockerconfigjson
        secretPath: kv/data/mattercodex/image-registry/push
        secretKey: dockerconfigjson
      - objectName: push.username
        secretPath: kv/data/mattercodex/image-registry/push
        secretKey: username
      - objectName: push.password
        secretPath: kv/data/mattercodex/image-registry/push
        secretKey: password
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mattercodex-image-registry-admin
spec:
  provider: vault
  secretObjects:
    - secretName: mattercodex-image-registry-admin
      type: Opaque
      data:
        - objectName: admin.username
          key: username
        - objectName: admin.password
          key: password
  parameters:
    roleName: mattercodex-image-registry-admin
    objects: |
      - objectName: tls.crt
        secretPath: pki/issue/mattercodex-image-registry-admin
        secretKey: certificate
        method: PUT
        secretArgs:
          common_name: mattercodex-image-registry-admin.mattercodex-system.svc.cluster.local
          alt_names: mattercodex-image-registry-admin,mattercodex-image-registry-admin.mattercodex-system.svc,mattercodex-image-registry-admin.mattercodex-system.svc.cluster.local
          ttl: 1h
      - objectName: tls.key
        secretPath: pki/issue/mattercodex-image-registry-admin
        secretKey: private_key
        method: PUT
        secretArgs:
          common_name: mattercodex-image-registry-admin.mattercodex-system.svc.cluster.local
          alt_names: mattercodex-image-registry-admin,mattercodex-image-registry-admin.mattercodex-system.svc,mattercodex-image-registry-admin.mattercodex-system.svc.cluster.local
          ttl: 1h
      - objectName: auth.htpasswd
        secretPath: kv/data/mattercodex/image-registry/admin
        secretKey: htpasswd
      - objectName: admin.username
        secretPath: kv/data/mattercodex/image-registry/admin
        secretKey: username
      - objectName: admin.password
        secretPath: kv/data/mattercodex/image-registry/admin
        secretKey: password
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mattercodex-image-registry-promotion
spec:
  provider: vault
  secretObjects:
    - secretName: mattercodex-image-promotion
      type: kubernetes.io/dockerconfigjson
      data:
        - objectName: promotion-dockerconfigjson
          key: .dockerconfigjson
    - secretName: mattercodex-image-promotion-client
      type: Opaque
      data:
        - objectName: promotion.username
          key: username
        - objectName: promotion.password
          key: password
  parameters:
    roleName: mattercodex-image-registry-promotion
    objects: |
      - objectName: tls.crt
        secretPath: pki/issue/mattercodex-image-registry-promotion
        secretKey: certificate
        method: PUT
        secretArgs:
          common_name: mattercodex-image-registry-promotion.mattercodex-system.svc.cluster.local
          alt_names: mattercodex-image-registry-promotion,mattercodex-image-registry-promotion.mattercodex-system.svc,mattercodex-image-registry-promotion.mattercodex-system.svc.cluster.local
          ttl: 1h
      - objectName: tls.key
        secretPath: pki/issue/mattercodex-image-registry-promotion
        secretKey: private_key
        method: PUT
        secretArgs:
          common_name: mattercodex-image-registry-promotion.mattercodex-system.svc.cluster.local
          alt_names: mattercodex-image-registry-promotion,mattercodex-image-registry-promotion.mattercodex-system.svc,mattercodex-image-registry-promotion.mattercodex-system.svc.cluster.local
          ttl: 1h
      - objectName: auth.htpasswd
        secretPath: kv/data/mattercodex/image-registry/promotion
        secretKey: htpasswd
      - objectName: promotion-dockerconfigjson
        secretPath: kv/data/mattercodex/image-registry/promotion
        secretKey: dockerconfigjson
      - objectName: promotion.username
        secretPath: kv/data/mattercodex/image-registry/promotion
        secretKey: username
      - objectName: promotion.password
        secretPath: kv/data/mattercodex/image-registry/promotion
        secretKey: password
