apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mattercodex-image-registry-credentials
  annotations:
    mattercodex.dev/registry-pull-host: registry-pull.invalid
spec:
  provider: vault
  secretObjects:
    - secretName: mattercodex-image-registry-ca
      type: Opaque
      data:
        - objectName: internal-ca.pem
          key: ca.pem
    - secretName: mattercodex-image-pull
      type: kubernetes.io/dockerconfigjson
      data:
        - objectName: pull-dockerconfigjson
          key: .dockerconfigjson
    - secretName: mattercodex-image-push
      type: kubernetes.io/dockerconfigjson
      data:
        - objectName: push-dockerconfigjson
          key: .dockerconfigjson
    - secretName: mattercodex-image-registry-admin
      type: Opaque
      data:
        - objectName: admin.username
          key: username
        - objectName: admin.password
          key: password
  parameters:
    roleName: mattercodex-image-registry
    objects: |
      - objectName: pull.crt
        secretPath: pki-public/issue/mattercodex-image-registry-pull
        secretKey: certificate
      - objectName: pull.key
        secretPath: pki-public/issue/mattercodex-image-registry-pull
        secretKey: private_key
      - objectName: internal.crt
        secretPath: pki/issue/mattercodex-image-registry-internal
        secretKey: certificate
      - objectName: internal.key
        secretPath: pki/issue/mattercodex-image-registry-internal
        secretKey: private_key
      - objectName: internal-ca.pem
        secretPath: pki/issue/mattercodex-image-registry-internal
        secretKey: issuing_ca
      - objectName: pull.htpasswd
        secretPath: kv/data/mattercodex/image-registry/pull
        secretKey: htpasswd
      - objectName: push.htpasswd
        secretPath: kv/data/mattercodex/image-registry/push
        secretKey: htpasswd
      - objectName: admin.htpasswd
        secretPath: kv/data/mattercodex/image-registry/admin
        secretKey: htpasswd
      - objectName: pull-dockerconfigjson
        secretPath: kv/data/mattercodex/image-registry/pull
        secretKey: dockerconfigjson
      - objectName: push-dockerconfigjson
        secretPath: kv/data/mattercodex/image-registry/push
        secretKey: dockerconfigjson
      - objectName: admin.username
        secretPath: kv/data/mattercodex/image-registry/admin
        secretKey: username
      - objectName: admin.password
        secretPath: kv/data/mattercodex/image-registry/admin
        secretKey: password
