apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: legacy-data-migration-backup
  labels:
    app.kubernetes.io/name: legacy-data-migration
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
