apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mattercodex-system
resources:
  - serviceaccount.yaml
  - backup-pvc.yaml
  - vault-secret-provider-class.yaml
  - vault-restore-secret-provider-class.yaml
  - vault-issuer-secret-provider-classes.yaml
  - job.yaml
  - service.yaml
  - servicemonitor.yaml
  - networkpolicy.yaml
  - prometheusrule.yaml
  - owner-evidence-configmap.yaml
