apiVersion: v1
kind: ConfigMap
metadata:
  name: kodex-platform-endpoints
data:
  publicOrigin: __KODEX_PUBLIC_ORIGIN__
  oidcIssuer: __KODEX_OIDC_ISSUER__
  oidcJwksUrl: __KODEX_OIDC_JWKS_URL__
  oidcConnectAddress: __KODEX_OIDC_CONNECT_ADDRESS__
  oidcTlsServerName: __KODEX_OIDC_TLS_SERVER_NAME__
