apiVersion: v1
kind: Service
metadata:
  name: control-plane
  labels:
    app.kubernetes.io/name: control-plane
spec:
  selector:
    app.kubernetes.io/name: control-plane
  ports:
    - name: grpc
      port: 8443
      targetPort: grpc
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
