import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync } from 'node:fs';
import { execFileSync,spawnSync } from 'node:child_process';
import { join } from 'node:path';
import { fingerprint } from './scoped-release.mjs';
import { mailboxMaintenancePlan } from './control-plane-mailbox-maintenance.mjs';
const fixture=(path)=>({kind:'Deployment',metadata:{name:'control-plane',namespace:'kodex-system',uid:'cp-uid',resourceVersion:'1',labels:{'kodex.dev/environment':'staging','kodex.dev/local-profile':'hot-reload'}},spec:{replicas:2,template:{metadata:{},spec:{containers:[{name:'control-plane',image:'go@sha256:'+'a'.repeat(64),volumeMounts:[{name:'dev-source',mountPath:'/workspace',readOnly:true}]},{name:'authority',image:'sidecar@sha256:'+'b'.repeat(64)}],volumes:[{name:'dev-source',hostPath:{path}}]}}},status:{availableReplicas:2}});
test('plan preserves sidecars/security and limits all transitions to exact CP source/replicas',()=>{const before=fixture('/fixture/old');const p=mailboxMaintenancePlan(before,{path:'/fixture/new',revision:'c'.repeat(40)},()=>({revision:'c'.repeat(40)}));assert.equal(p.specs.stopped.replicas,0);assert.equal(p.specs.replaced.replicas,0);assert.equal(p.specs.resumed.replicas,2);assert.deepEqual(p.specs.resumed.template.spec.containers[1],before.spec.template.spec.containers[1]);for(const mutate of [b=>b.metadata.namespace='other',b=>b.metadata.labels['kodex.dev/environment']='production',b=>b.status.availableReplicas=1]){const b=structuredClone(before);mutate(b);assert.throws(()=>mailboxMaintenancePlan(b,p.source,()=>({revision:p.source.revision})));}});
function cli(t){const dir=mkdtempSync('/tmp/cpmail-');t.after(()=>rmSync(dir,{recursive:true,force:true}));const source=join(dir,'source');mkdirSync(source,{mode:0o755});writeFileSync(join(source,'fixture.txt'),'source');const git=(...a)=>execFileSync('git',['-C',source,...a],{stdio:'pipe'}).toString().trim();git('init','-q');git('remote','add','origin','https://github.com/codex-k8s/kodex.git');git('add','.');git('-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-qm','Оснастка');const revision=git('rev-parse','HEAD');const state=join(dir,'state.json'),plan=join(dir,'plan.json'),evidence=join(dir,'evidence.jsonl'),migration=join(dir,'migration.json');const cp=fixture(source);const m={version:1,kind:'CONTROL_PLANE_MIGRATION',profile:'mailbox-observation',migrationVersion:'20260908000500',source:{path:source,revision},context:'staging',clusterUID:'cluster',job:{metadata:{name:'migration',namespace:'kodex-system'},spec:{template:{spec:{containers:[]}}}}};const job={...m.job,metadata:{...m.job.metadata,uid:'job-uid',annotations:{'kodex.dev/cp-mailbox-migration-plan':fingerprint(m)}},status:{conditions:[{type:'Complete',status:'True'}]}};writeFileSync(migration,JSON.stringify(m),{mode:0o600});writeFileSync(state,JSON.stringify({cp,pods:[],job,calls:[],mode:''}),{mode:0o600});
 writeFileSync(join(dir,'kubectl'),`#!/usr/bin/env node
const fs=require('fs');const file=${JSON.stringify(state)};const s=JSON.parse(fs.readFileSync(file));const a=process.argv.slice(2);s.calls.push(a);const save=()=>fs.writeFileSync(file,JSON.stringify(s));const out=v=>{save();console.log(JSON.stringify(v));};
if(a.includes('patch')){const ops=JSON.parse(fs.readFileSync(0,'utf8'));if(s.mode==='cas'){save();process.exit(1);}for(const op of ops){const keys=op.path.slice(1).split('/');let x=s.cp;for(const key of keys.slice(0,-1))x=x[key];const key=keys.at(-1);if(op.op==='test'&&JSON.stringify(x[key])!==JSON.stringify(op.value)){save();process.exit(1);}if(op.op==='replace')x[key]=op.value;}s.cp.metadata.resourceVersion=String(Number(s.cp.metadata.resourceVersion)+1);save();if(s.mode==='lost-ack')process.exit(1);out(s.cp);}
else if(a.includes('namespace'))out({metadata:{uid:'cluster'}});else if(a.includes('pods'))out({items:s.pods});else if(a.includes('deployment'))out(s.cp);else if(a.includes('logs')){save();console.log('goose: current version: '+(s.mode==='wrong-migration'?'20260908000300':'20260908000500'));}else if(a.includes('job'))out(s.job);else process.exit(1);
`,{mode:0o700});
 const edit=fn=>{const s=JSON.parse(readFileSync(state));fn(s);writeFileSync(state,JSON.stringify(s));};const run=(phase,extra=[])=>spawnSync(process.execPath,[new URL('./control-plane-mailbox-maintenance.mjs',import.meta.url).pathname,phase,'--context','staging','--plan',plan,...(phase==='plan'?['--source',source,'--revision',revision]:['--evidence',evidence]),...(['stop','replace','resume'].includes(phase)?['--confirm','APPLY-STAGING-CP-MAILBOX-MAINTENANCE']:[]),...(phase==='resume'?['--migration-plan',migration]:[]),...extra],{encoding:'utf8',env:{...process.env,PATH:dir+':'+process.env.PATH},timeout:10000});const pass=phase=>{const r=run(phase);assert.equal(r.status,0,r.stderr);return JSON.parse(r.stdout);};return{run,pass,edit,read:()=>JSON.parse(readFileSync(state)),evidence};}
test('public CLI plan → stop/drain → replace → exact migration → resume; no repeated patches',t=>{const f=cli(t);f.pass('plan');f.edit(s=>s.pods=[{status:{phase:'Running'}}]);assert.equal(f.pass('stop').status,'DRAINING');assert.notEqual(f.run('replace').status,0);f.edit(s=>s.pods=[]);f.pass('inspect');f.pass('replace');f.edit(s=>s.mode='wrong-migration');assert.notEqual(f.run('resume').status,0);f.edit(s=>s.mode='');f.pass('resume');f.pass('resume');assert.equal(f.read().calls.filter(a=>a.includes('patch')).length,3);assert.equal(f.read().cp.spec.replicas,2);});
test('public CLI lost stop ACK resolves authoritative state, without duplicate PATCH',t=>{const f=cli(t);f.pass('plan');f.edit(s=>s.mode='lost-ack');assert.notEqual(f.run('stop').status,0);assert.equal(f.pass('inspect').stage,'stopped');f.pass('stop');f.edit(s=>s.mode='');f.pass('replace');f.pass('resume');assert.equal(f.read().calls.filter(a=>a.includes('patch')).length,3);assert.match(readFileSync(f.evidence,'utf8'),/UNKNOWN/);});
test('public CLI CAS UNKNOWN-before-apply and foreign drift reject mutation retry',t=>{const f=cli(t);f.pass('plan');f.edit(s=>s.mode='cas');assert.notEqual(f.run('stop').status,0);assert.equal(f.pass('inspect').stage,'before');f.edit(s=>s.mode='');assert.notEqual(f.run('stop').status,0);assert.equal(f.read().calls.filter(a=>a.includes('patch')).length,1);f.edit(s=>s.cp.spec.replicas=7);assert.notEqual(f.run('inspect').status,0);});
