import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { chmodSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { planControlPlaneMigration, migrationReadback } from './control-plane-migration.mjs';
import { fingerprint } from './scoped-release.mjs';
const revision = 'a'.repeat(40), source = {path:'/fixture/source',revision};
function fixture(path = source.path) { return {apiVersion:'batch/v1',kind:'Job',metadata:{name:'control-plane-migrate',namespace:'kodex-system',uid:'base-uid',resourceVersion:'1',labels:{'app.kubernetes.io/name':'control-plane','app.kubernetes.io/component':'migration','app.kubernetes.io/part-of':'kodex','kodex.dev/environment':'staging','kodex.dev/local-profile':'hot-reload'}},spec:{selector:{matchLabels:{'controller-uid':'old'}},template:{metadata:{labels:{'controller-uid':'old','job-name':'control-plane-migrate'},annotations:{'kodex.dev/source-content-sha256':'old'}},spec:{serviceAccountName:'control-plane-migrator',automountServiceAccountToken:false,restartPolicy:'Never',containers:[{name:'migrate',image:`golang@sha256:${'b'.repeat(64)}`,command:['/workspace/tools/dev/run-go-command.sh'],args:['services/internal/control-plane','./cmd/cli','up'],securityContext:{readOnlyRootFilesystem:true,allowPrivilegeEscalation:false},env:[{name:'CONTROL_PLANE_POSTGRES_ADMIN_DSN_FILE',value:'/var/run/secrets/kodex/control-plane/postgres-migration/dsn'}],volumeMounts:[{name:'dev-source',mountPath:'/workspace',readOnly:true}]}],volumes:[{name:'dev-source',hostPath:{path}},{name:'postgres-migration',secret:{secretName:'control-plane-postgres-migration'}}]}}},status:{succeeded:1,conditions:[{type:'Complete',status:'True'}]}}; }
const inspect = () => ({revision});
test('migration clones exact owner boundary, replaces only source and bounded Job lifecycle', () => {
 const before=fixture(), snapshot=structuredClone(before), plan=planControlPlaneMigration(before,source,inspect,'fixture'); assert.deepEqual(before,snapshot); assert.equal(plan.job.spec.backoffLimit,0); assert.equal(plan.job.spec.selector,undefined); assert.deepEqual(plan.job.spec.template.metadata.labels,{}); assert.equal(plan.job.spec.template.metadata.annotations['kodex.dev/source-content-sha256'],undefined); assert.deepEqual(plan.job.spec.template.spec.containers[0].env,before.spec.template.spec.containers[0].env); assert.deepEqual(plan.job.spec.template.spec.volumes[1],before.spec.template.spec.volumes[1]);
});
test('foreign profile, active predecessor, command and credential changes reject', () => {
 for (const mutate of [j=>j.metadata.namespace='foreign',j=>j.metadata.labels['kodex.dev/environment']='production',j=>j.status.active=1,j=>j.spec.template.spec.serviceAccountName='admin',j=>j.spec.template.spec.containers[0].args=['down'],j=>j.spec.template.spec.containers[0].env[0].value='/foreign',j=>j.spec.template.spec.containers[0].securityContext.readOnlyRootFilesystem=false]) {const j=fixture();mutate(j);assert.throws(()=>planControlPlaneMigration(j,source,inspect));}
});
test('terminal proof needs exact Job, source and actual goose version', () => {
 const plan=planControlPlaneMigration(fixture(),source,inspect,'fixture');const job=structuredClone(plan.job);job.metadata.uid='created';job.metadata.annotations={'kodex.dev/cp-migration-plan':fingerprint(plan)};job.status={succeeded:1,conditions:[{type:'Complete',status:'True'}]};assert.equal(migrationReadback(job,plan,'goose: successfully migrated database to version: 20260908000300\n').status,'PASS');assert.equal(migrationReadback(job,plan,'goose: current version: 20260908000299').status,'READBACK_UNCONFIRMED');job.spec.template.spec.containers[0].image='foreign';assert.throws(()=>migrationReadback(job,plan,''),/SPEC_CHANGED/);
});
function cliFixture(t, profile = 'legacy') {
 const dir=mkdtempSync('/tmp/cpm-');t.after(()=>rmSync(dir,{recursive:true,force:true}));const repo=join(dir,'source');mkdirSync(repo,{mode:0o755});const migration='services/internal/control-plane/cmd/cli/migrations/20260908000300_email_legacy_package_admission.sql';mkdirSync(join(repo,'services/internal/control-plane/cmd/cli/migrations'),{recursive:true});writeFileSync(join(repo,migration),'-- Синтетическая миграция CLI fixture\n');writeFileSync(join(repo,'services/internal/control-plane/cmd/cli/migrations/20260908000500_email_mailbox_observation_receipts.sql'),'-- Синтетическая additive миграция\n');
 const git=(...a)=>execFileSync('git',['-C',repo,...a],{stdio:['ignore','pipe','pipe']}).toString().trim();git('init','-q');git('remote','add','origin','https://github.com/codex-k8s/kodex.git');git('add','.');git('-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-qm','Оснастка');const rev=git('rev-parse','HEAD');
 const state=join(dir,'state.json'), plan=join(dir,'plan.json'), evidence=join(dir,'evidence.jsonl');writeFileSync(state,JSON.stringify({base:fixture(repo),calls:[],mode:'',profile,replicas:0,pods:[]}),{mode:0o600});const executable=join(dir,'kubectl');writeFileSync(executable,`#!/usr/bin/env node
const fs=require('fs'),path=${JSON.stringify(state)},s=JSON.parse(fs.readFileSync(path)),a=process.argv.slice(2);s.calls.push(a);const save=()=>fs.writeFileSync(path,JSON.stringify(s));const out=x=>{save();process.stdout.write(JSON.stringify(x));};
if(a.includes('namespace'))out({metadata:{uid:'cluster'}});
else if(a.includes('patch')){const p=JSON.parse(a[a.indexOf('-p')+1]);if(s.mode==='cas'){save();process.exit(1);}if(p[0].value!==s.base.metadata.uid||p[1].value!==s.base.metadata.resourceVersion)process.exit(2);s.base.metadata.annotations=p[2].value;s.base.metadata.resourceVersion='2';if(s.mode==='reservation-lost-ack'){save();process.exit(1);}out(s.base);}
else if(a.includes('create')){s.job=JSON.parse(fs.readFileSync(0,'utf8'));s.job.metadata.uid='created';s.job.status={succeeded:1,conditions:[{type:'Complete',status:'True'}]};save();if(s.mode==='lost-ack')process.exit(1);out(s.job);}
else if(a.includes('logs')){save();process.stdout.write('goose: successfully migrated database to version: '+(s.profile==='mailbox-observation'?'20260908000500':'20260908000300')+'\\n');}
else if(a.includes('deployment'))out({spec:{replicas:s.replicas}});
else if(a.includes('pods'))out({items:s.pods});
else if(a.includes('jobs'))out({items:[s.base,...(s.job?[s.job]:[])]});
else if(a.includes('control-plane-migrate'))out(s.base);
else if(s.job)out(s.job);else{save();if(!a.includes('--ignore-not-found=true'))process.exit(1);}
`,{mode:0o700});chmodSync(executable,0o700);
 const run=(phase,extra=[])=>spawnSync(process.execPath,[new URL('./control-plane-migration.mjs',import.meta.url).pathname,phase,'--context','staging','--plan',plan,...(profile==='legacy'?[]:['--profile',profile]),...(phase==='plan'?['--source',repo,'--revision',rev]:['--evidence',evidence]),...(phase==='apply'?['--confirm','APPLY-STAGING-CP-MIGRATION']:[]),...extra],{env:{...process.env,PATH:`${dir}:${process.env.PATH}`},encoding:'utf8',timeout:15000});
 return {run,read:()=>JSON.parse(readFileSync(state)),edit:(fn)=>{const s=JSON.parse(readFileSync(state));fn(s);writeFileSync(state,JSON.stringify(s));},evidence};
}
test('public CLI plan → CAS reserve → create → inspect; repeated apply never creates again',t=>{const f=cliFixture(t);for(const phase of ['plan','apply','inspect','apply']){const r=f.run(phase);assert.equal(r.status,0,r.stderr);assert.equal(JSON.parse(r.stdout).status,phase==='plan'?'PLANNED':'PASS');}assert.equal(f.read().calls.filter(a=>a.includes('create')).length,1);assert.equal(f.read().calls.filter(a=>a.includes('patch')).length,1);});
test('public CLI lost create ACK recovers only readback, no second Job',t=>{const f=cliFixture(t);assert.equal(f.run('plan').status,0);f.edit(s=>s.mode='lost-ack');assert.notEqual(f.run('apply').status,0);assert.equal(f.run('inspect').status,0);assert.equal(f.run('apply').status,0);assert.equal(f.read().calls.filter(a=>a.includes('create')).length,1);assert.match(readFileSync(f.evidence,'utf8'),/UNKNOWN/);});
test('public CLI CAS failure and malformed flags never create',t=>{const f=cliFixture(t);assert.equal(f.run('plan').status,0);f.edit(s=>s.mode='cas');assert.notEqual(f.run('apply').status,0);assert.notEqual(f.run('apply').status,0);assert.equal(f.read().calls.filter(a=>a.includes('create')).length,0);assert.notEqual(f.run('inspect',['--confirm','APPLY-STAGING-CP-MIGRATION']).status,0);});

test('public CLI lost reservation ACK: inspect and same-plan resume do not PATCH again',t=>{const f=cliFixture(t);assert.equal(f.run('plan').status,0);f.edit(s=>s.mode='reservation-lost-ack');assert.notEqual(f.run('apply').status,0);let result=f.run('inspect');assert.equal(result.status,0,result.stderr);assert.equal(JSON.parse(result.stdout).status,'RESERVED_NOT_CREATED');assert.equal(f.read().calls.filter(a=>a.includes('create')).length,0);result=f.run('apply');assert.equal(result.status,0,result.stderr);assert.equal(JSON.parse(result.stdout).status,'PASS');assert.equal(f.read().calls.filter(a=>a.includes('patch')).length,1);assert.equal(f.read().calls.filter(a=>a.includes('create')).length,1);assert.match(readFileSync(f.evidence,'utf8'),/UNKNOWN/);});
test('public CLI reservation not applied is observable; foreign marker cannot resume',t=>{const f=cliFixture(t);assert.equal(f.run('plan').status,0);f.edit(s=>s.mode='cas');assert.notEqual(f.run('apply').status,0);const result=f.run('inspect');assert.equal(result.status,0,result.stderr);assert.equal(JSON.parse(result.stdout).status,'RESERVATION_NOT_APPLIED');assert.notEqual(f.run('apply').status,0);f.edit(s=>s.base.metadata.annotations={'kodex.dev/cp-migration-plan':'foreign'});assert.notEqual(f.run('inspect').status,0);assert.notEqual(f.run('apply').status,0);assert.equal(f.read().calls.filter(a=>a.includes('patch')).length,1);assert.equal(f.read().calls.filter(a=>a.includes('create')).length,0);});

test('public CLI mailbox observation profile requires stopped CP/publisher and exact new migration',t=>{const f=cliFixture(t,'mailbox-observation');assert.equal(f.run('plan').status,0);f.edit(s=>s.replicas=2);assert.notEqual(f.run('apply').status,0);f.edit(s=>{s.replicas=0;s.pods=[{status:{phase:'Running'}}];});assert.notEqual(f.run('apply').status,0);assert.equal(f.read().calls.filter(a=>a.includes('create')).length,0);f.edit(s=>s.pods=[]);const result=f.run('apply');assert.equal(result.status,0,result.stderr);assert.equal(JSON.parse(result.stdout).status,'PASS');assert.equal(f.read().job.metadata.name,'control-plane-migrate-20260908000500');});
