import test from "node:test";
import assert from "node:assert/strict";
import { planDefaultRunner, requirePublishedNodeReadback, requireRuntimeBinding } from "./default-runner-transition.mjs";

const oldRef=`pull.kodex.works/kodex/agent-runner@sha256:${"a".repeat(64)}`,nextRef=`pull.kodex.works/kodex/agent-runner@sha256:${"b".repeat(64)}`;
function deployment(name){const key=name==="control-plane"?"CONTROL_PLANE_DEFAULT_ROLE_IMAGE_REFERENCE":"RUNTIME_CONTROLLER_DEFAULT_ROLE_IMAGE_REFERENCE",env=[{name:key,value:oldRef}];if(name==="control-plane")env.push({name:"CONTROL_PLANE_TRUSTED_ROLE_BASE_DIGEST",value:`sha256:${"b".repeat(64)}`});return{apiVersion:"apps/v1",kind:"Deployment",metadata:{name,namespace:"kodex-system",uid:name==="control-plane"?"11111111-1111-4111-8111-111111111111":"22222222-2222-4222-8222-222222222222",resourceVersion:"1",generation:1,labels:{"app.kubernetes.io/part-of":"kodex","kodex.dev/local-profile":"hot-reload"}},spec:{replicas:2,strategy:{type:"RollingUpdate",rollingUpdate:{maxUnavailable:0,maxSurge:1}},template:{metadata:{annotations:{kept:"yes"}},spec:{containers:[{name,env},{name:"sidecar",env:[{name:"SECRET",valueFrom:{secretKeyRef:{name:"kept",key:"value"}}}]}]}}},status:{observedGeneration:1,availableReplicas:2,updatedReplicas:2,replicas:2}};}

test("план меняет только default runner двух приложений и сохраняет sidecar",()=>{const values=[deployment("control-plane"),deployment("runtime-controller")],before=structuredClone(values),plan=planDefaultRunner(values,nextRef,"33333333-3333-4333-8333-333333333333");assert.deepEqual(values,before);assert.deepEqual(plan.operations.map(x=>x.name),["runtime-controller","control-plane"]);for(const operation of plan.operations){const spec=operation.patch.at(-1).value;assert.equal(spec.template.spec.containers.find(x=>x.name===operation.name).env.find(x=>x.name===operation.key).value,nextRef);assert.deepEqual(spec.template.spec.containers.find(x=>x.name==="sidecar"),before.find(x=>x.metadata.name===operation.name).spec.template.spec.containers[1]);if(operation.name==="control-plane"){assert.equal(operation.stabilizedAfter.template.metadata.annotations["kodex.dev/default-runner-transition-stabilized"],plan.id);assert.notEqual(operation.stabilizedAfterSpecSHA256,operation.afterSpecSHA256);}else{assert.equal(operation.stabilizedAfter,undefined);}}});

test("план закрыто отклоняет чужой профиль, разные predecessor и недоверенный digest",()=>{for(const mutate of [v=>delete v[0].metadata.labels["kodex.dev/local-profile"],v=>v[0].status.availableReplicas=1,v=>v[1].spec.template.spec.containers[0].env[0].value=nextRef,v=>v[0].spec.template.spec.containers[0].env.find(x=>x.name==="CONTROL_PLANE_TRUSTED_ROLE_BASE_DIGEST").value=`sha256:${"c".repeat(64)}`]){const values=[deployment("control-plane"),deployment("runtime-controller")];mutate(values);assert.throws(()=>planDefaultRunner(values,nextRef,"33333333-3333-4333-8333-333333333333"));}});

test("переход требует опубликованный exact node readback runner",()=>{const policy={apiVersion:"v1",kind:"ConfigMap",metadata:{namespace:"kodex-system",labels:{"app.kubernetes.io/part-of":"kodex","kodex.dev/owner-intent":"true"}},immutable:true,data:{nodeReadbackImage:nextRef}};assert.doesNotThrow(()=>requirePublishedNodeReadback(policy,nextRef));policy.data.nodeReadbackImage=oldRef;assert.throws(()=>requirePublishedNodeReadback(policy,nextRef),/NOT_PUBLISHED/);});

test("переход требует заранее переключённый закрытый runtime binding",()=>{const policy={metadata:{name:"policy-next"},data:{nodeReadbackImage:nextRef}},binding={apiVersion:"admissionregistration.k8s.io/v1",kind:"ValidatingAdmissionPolicyBinding",metadata:{name:"runtime-role-pod-exact-secret-projection"},spec:{policyName:"runtime-role-pod-exact-secret-projection",validationActions:["Deny"],paramRef:{name:"policy-next",namespace:"kodex-system",parameterNotFoundAction:"Deny"}}};assert.doesNotThrow(()=>requireRuntimeBinding(policy,binding,nextRef));binding.spec.paramRef.name="policy-old";assert.throws(()=>requireRuntimeBinding(policy,binding,nextRef),/NOT_TRANSITIONED/);});
