import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdtempSync,writeFileSync,readFileSync,rmSync,statSync,readdirSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {spawnSync} from 'node:child_process';
import {runtimePodTarget,validateRuntimeCRI,observeRuntimePod,validateRuntimeObservation,writeRuntimeEvidence} from './runtime-pod-observe.mjs';
import {runtimePodFixture,runtimeCRIFixture} from './runtime-pod-observe-fixture.mjs';
const sha=x=>createHash('sha256').update(x).digest('hex');
const hash='a'.repeat(64),binary=Buffer.from('Synthetic runner bytes, no executable provider');
function fixture(){const binding={version:1,kind:'COMBINED_RUNTIME_BINDING',status:'BOUND',clusterUID:'33333333-3333-4333-8333-333333333333',namespaceUID:'44444444-4444-4444-8444-444444444444',planSHA256:hash,runRef:'run_fixture',projectRef:'prj_fixture',agentRef:'agt_fixture',sessionRef:'ses_fixture',turnRef:'turn_fixture',attempt:1,revisionRef:'rtvr_fixture',revisionVersion:1,revisionDigest:hash,projectHash:sha('prj_fixture').slice(0,16),sessionHash:sha('ses_fixture').slice(0,16),turnHash:sha('turn_fixture').slice(0,16),image:`pull.fixture.invalid/role@sha256:${hash}`,imageManifestDigest:`sha256:${hash}`,runnerProvenance:{sourceRevision:'b'.repeat(40),baseImage:`registry.fixture.invalid/runner@sha256:${hash}`,binaryPath:'/usr/local/bin/kodex-agent-runner',binarySHA256:sha(binary),bytesSHA256:hash}};const pod=runtimePodFixture(binding);return {binding,pod,cri:runtimeCRIFixture(pod),process:{pid:20,initPID:10,startTicks:'100',device:'1',inode:'2',binarySHA256:sha(binary)}};}
test('actual target→CRI→before/after process/POD→closed proof binds exact expected provenance',()=>{const f=fixture();const proof=observeRuntimePod(f.binding,f.pod,{readCRI:()=>f.cri,readProcess:()=>f.process,readPod:()=>f.pod});validateRuntimeObservation(proof,f.binding);assert.equal(proof.imageID,f.binding.image);assert.equal(proof.process.binarySHA256,sha(binary));});
for(const [name,mutate] of Object.entries({tenant:f=>f.pod.metadata.annotations['runtime.kodex.dev/project-hash']='b'.repeat(16),turn:f=>f.pod.metadata.annotations['runtime.kodex.dev/turn-hash']='b'.repeat(16),attempt:f=>f.pod.metadata.annotations['runtime.kodex.dev/attempt']='2',image:f=>f.pod.status.containerStatuses[0].imageID='foreign',restart:f=>f.pod.status.containerStatuses[0].restartCount=1,command:f=>f.pod.spec.containers[0].args=['other'],namespace:f=>f.pod.metadata.namespace='other'}))test(`target rejects ${name}`,()=>{const f=fixture();mutate(f);assert.throws(()=>runtimePodTarget(f.pod,f.binding));});
for(const [name,mutate] of Object.entries({pod:f=>f.cri.status.labels['io.kubernetes.pod.uid']='foreign',container:f=>f.cri.status.id='b'.repeat(64),entrypoint:f=>f.cri.info.runtimeSpec.process.args=['sh'],image:f=>f.cri.status.imageRef='foreign'}))test(`CRI rejects ${name}`,()=>{const f=fixture();const target=runtimePodTarget(f.pod,f.binding);mutate(f);assert.throws(()=>validateRuntimeCRI(target,f.cri));});
test('binary self-approval and replacement between reads fail',()=>{const f=fixture();assert.throws(()=>observeRuntimePod(f.binding,f.pod,{readCRI:()=>f.cri,readProcess:()=>({...f.process,binarySHA256:'f'.repeat(64)}),readPod:()=>f.pod}),/RUNNER_BINARY_MISMATCH/);let n=0;assert.throws(()=>observeRuntimePod(f.binding,f.pod,{readCRI:()=>f.cri,readProcess:()=>({...f.process,startTicks:String(++n)}),readPod:()=>f.pod}),/RUNNER_PROCESS_CHANGED/);assert.throws(()=>observeRuntimePod(f.binding,f.pod,{readCRI:()=>f.cri,readProcess:()=>f.process,readPod:()=>({...f.pod,metadata:{...f.pod.metadata,uid:'22222222-2222-4222-8222-222222222222'}})}),/RUNTIME_POD_CHANGED/);});
test('atomic private output is 0600 and never overwrites prior evidence',t=>{const dir=mkdtempSync(join(tmpdir(),'runtime-out-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const path=join(dir,'proof');writeRuntimeEvidence(path,{version:1});assert.equal(statSync(path).mode&0o777,0o600);assert.throws(()=>writeRuntimeEvidence(path,{version:2}));assert.equal(JSON.parse(readFileSync(path)).version,1);assert.deepEqual(readdirSync(dir),['proof']);});
function publicCLI(t,mode=''){
 const dir=mkdtempSync(join(tmpdir(),'runtime-cli-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const f=fixture(),data=join(dir,'data.json'),binding=join(dir,'binding.json'),output=join(dir,'proof.json'),exe=join(dir,'binary'),loader=join(dir,'loader.mjs');writeFileSync(data,JSON.stringify(f),{mode:0o600});writeFileSync(binding,JSON.stringify(f.binding),{mode:0o600});writeFileSync(exe,binary,{mode:0o600});
 writeFileSync(loader,`import fs from 'node:fs';import cp from 'node:child_process';import {syncBuiltinESMExports} from 'node:module';
 const f=JSON.parse(fs.readFileSync(${JSON.stringify(data)}));const mode=${JSON.stringify(mode)};let reads=0;process.getuid=()=>mode==='nonroot'?1000:0;
 const original={...fs};const executable='/usr/local/bin/kodex-agent-runner';
 cp.execFileSync=(cmd,args)=>{if(cmd!=='k3s')throw Error('UNEXPECTED_COMMAND');if(args[0]==='crictl')return JSON.stringify(f.cri);if(args.includes('current-context'))return 'fixture';if(args.includes('namespace'))return JSON.stringify({metadata:{uid:args.includes('kube-system')?f.binding.clusterUID:f.binding.namespaceUID,labels:{'kodex.dev/environment':'staging'}}});if(args.includes('pods'))return JSON.stringify({items:[f.pod]});if(args.includes('pod')){if(mode==='pod-drift')f.pod.metadata.uid='22222222-2222-4222-8222-222222222222';return JSON.stringify(f.pod);}throw Error('UNEXPECTED_COMMAND');};
 fs.readdirSync=(p,...a)=>p==='/proc'?['10','20']:original.readdirSync(p,...a);
 fs.readlinkSync=(p,...a)=>String(p).startsWith('/proc/')?(p.endsWith('/ns/pid')?'pid:[fixture]':p==='/proc/20/exe'?executable:'/usr/local/bin/kodex-init'):original.readlinkSync(p,...a);
 fs.readFileSync=(p,...a)=>typeof p==='string'&&p.startsWith('/proc/')?(p.endsWith('/stat')?'20 (runner) '+Array.from({length:25},(_,i)=>i===19?'100':'0').join(' '):p.endsWith('/cmdline')?Buffer.from(executable+'\\0runtime-session\\0'):Buffer.alloc(0)):original.readFileSync(p,...a);
 fs.openSync=(p,...a)=>original.openSync(p==='/proc/20/exe'?${JSON.stringify(exe)}:p,...a);if(mode==='bad-binary')f.binding.runnerProvenance.binarySHA256='f'.repeat(64);
 if(mode==='bad-binary')original.writeFileSync(${JSON.stringify(binding)},JSON.stringify(f.binding));syncBuiltinESMExports();`,{mode:0o600});
 const run=()=>spawnSync(process.execPath,['--import',loader,new URL('./runtime-pod-observe.mjs',import.meta.url).pathname,'--context','fixture','--binding',binding,'--output',output,'--timeout-ms','1000'],{encoding:'utf8',timeout:5000});return {run,output};
}
test('public observer CLI performs controlled kubectl/CRI/proc path and writes only safe proof',t=>{const f=publicCLI(t);const r=f.run();assert.equal(r.status,0,r.stderr);const proof=JSON.parse(readFileSync(f.output));assert.equal(proof.process.binarySHA256,sha(binary));assert.equal(proof.podUID,'11111111-1111-4111-8111-111111111111');assert(!readFileSync(f.output,'utf8').includes('Synthetic runner bytes'));assert.equal(f.run().status,1);});
for(const mode of ['nonroot','bad-binary','pod-drift'])test(`public observer CLI refuses ${mode}`,t=>{const f=publicCLI(t,mode);const r=f.run();assert.equal(r.status,1,r.stdout);assert.throws(()=>readFileSync(f.output));});
