apiVersion: builtin
kind: PatchTransformer
metadata:
  name: web-with-mattermost-bundle-cluster-scope
patch: |-
  - op: remove
    path: /metadata/namespace
target:
  group: trust.cert-manager.io
  version: v1alpha1
  kind: Bundle
