apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: internal-rpc-authority-interaction-gateway-database
spec:
  address: https://vault.kodex-system.svc:8200
  tlsServerName: vault.kodex-system.svc.cluster.local
  skipTLSVerify: false
  caCertSecretRef: internal-rpc-authority-interaction-gateway-workload-tls
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: internal-rpc-authority-interaction-gateway-database
spec:
  vaultConnectionRef: internal-rpc-authority-interaction-gateway-database
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: internal-rpc-authority-interaction-gateway
    serviceAccount: interaction-gateway
    audiences: [vault]
    tokenExpirationSeconds: 600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: internal-rpc-authority-interaction-gateway-issuer-postgresql
spec:
  vaultAuthRef: internal-rpc-authority-interaction-gateway-database
  mount: database
  path: static-creds/interaction-gateway-issuer-g1
  allowStaticCreds: true
  refreshAfter: 1m
  revoke: false
  rolloutRestartTargets:
    - {kind: Deployment, name: interaction-gateway}
  destination:
    create: true
    name: internal-rpc-authority-interaction-gateway-issuer-postgresql
    overwrite: false
    transformation:
      excludeRaw: true
      excludes: [".*"]
      templates:
        username: {text: '{{ get .Secrets "username" }}'}
        dsn:
          text: >-
            postgresql://{{ get .Secrets "username" }}:{{ get .Secrets "password" }}@internal-rpc-authority-postgresql-rw.kodex-system.svc.cluster.local:5432/internal_rpc_authority?sslmode=verify-full&sslrootcert=/var/run/config/kodex/internal-rpc-authority/postgresql/ca.pem
