DatabaseDirectory /var/lib/clamav
DatabaseMirror database.clamav.net
DNSDatabaseInfo current.cvd.clamav.net
HTTPProxyServer clamav-egress-gateway.kodex-system.svc.cluster.local
HTTPProxyPort 8080
ConnectTimeout 10
ReceiveTimeout 120
ScriptedUpdates yes
TestDatabases yes
LogVerbose no
