apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clamav-database
  labels:
    app.kubernetes.io/name: clamav-db-updater
    app.kubernetes.io/component: malware-signature-updater
spec:
  accessModes: [ReadWriteMany]
  resources:
    requests:
      storage: 1Gi
