apiVersion: v1
kind: ServiceAccount
metadata:
  name: clamav-db-updater
  labels:
    app.kubernetes.io/name: clamav-db-updater
    app.kubernetes.io/component: malware-signature-updater
automountServiceAccountToken: false
