-- name: platform__runtime_claimexecution_2 :many
SELECT n.id::text,n.ref,n.run_id::text,r.ref,r.root_run_id::text,COALESCE(r.project_id::text,''),COALESCE(p.ref,''),r.session_id::text,s.ref,r.task,a.ref,a.runtime_key,rp.runtime_revision,rp.provider,rp.model,iv.ref,iv.digest,iv.content||CASE WHEN a.system_key='system-assistant' AND COALESCE(ar.owner_instructions,'')<>'' THEN E'\n\nДополнительные инструкции владельца:\n'||ar.owner_instructions ELSE '' END,a.capabilities,a.knowledge_artifact_refs,r.input,n.attempt,COALESCE(t.ref,''),COALESCE(a.system_key,''),
		COALESCE((SELECT jsonb_agg(jsonb_build_object('ref',g.ref,'connectionRef',c.ref,'definitionKey',c.definition_key,'connectionName',c.name,'capabilityKey',g.capability_key,'capabilityName',capability.value->>'name','capabilityDescription',capability.value->>'description','risk',capability.value->>'risk') ORDER BY c.name,g.capability_key) FROM control_plane.integration_grants g JOIN control_plane.integration_connections c ON c.id=g.connection_id JOIN control_plane.integration_definitions d ON d.stable_key=c.definition_key JOIN LATERAL jsonb_array_elements(d.capabilities) capability(value) ON capability.value->>'key'=g.capability_key WHERE g.organization_id=r.organization_id AND g.target_kind='AGENT' AND g.target_ref=a.ref AND g.enabled AND c.enabled AND c.state='CONNECTED'),'[]'::jsonb),
		COALESCE((SELECT jsonb_agg(jsonb_build_object('ref',candidate.ref,'name',candidate.name,'purpose',candidate.purpose,'roleDescription',candidate.role_description) ORDER BY candidate.name) FROM control_plane.agents candidate WHERE candidate.organization_id=r.organization_id AND candidate.project_id=r.project_id AND candidate.id<>a.id AND candidate.enabled AND candidate.state='READY'),'[]'::jsonb),
		COALESCE((SELECT edge.ref FROM control_plane.run_edges edge WHERE edge.source_node_id=n.id AND edge.type='CALLBACK_TO' ORDER BY edge.created_at LIMIT 1),''),
		COALESCE((SELECT jsonb_agg(jsonb_build_object('role',history.actor_kind,'content',history.content) ORDER BY history.turn_number) FROM (SELECT previous.actor_kind,left(previous.content,4000) AS content,previous.turn_number FROM control_plane.session_turns previous WHERE previous.session_id=r.session_id AND previous.id<>COALESCE(n.turn_id,'00000000-0000-0000-0000-000000000000'::uuid) AND previous.state='COMPLETED' ORDER BY previous.turn_number DESC LIMIT 20) history),'[]'::jsonb)
		FROM control_plane.run_nodes n JOIN control_plane.runs r ON r.id=n.run_id LEFT JOIN control_plane.projects p ON p.id=r.project_id JOIN control_plane.sessions s ON s.id=r.session_id JOIN control_plane.agents a ON a.id=n.agent_id JOIN control_plane.runtime_profiles rp ON rp.stable_key=a.runtime_key JOIN LATERAL(SELECT i.ref,i.digest,i.content FROM control_plane.instruction_versions i WHERE i.agent_id=a.id AND i.state='PUBLISHED' ORDER BY i.version_number DESC LIMIT 1)iv ON true LEFT JOIN control_plane.assistant_runtime ar ON ar.agent_id=a.id LEFT JOIN control_plane.session_turns t ON t.id=n.turn_id
		WHERE n.organization_id=$1::uuid AND n.type='AGENT_EXECUTION' AND n.state='QUEUED' AND r.state IN('RUNNING','QUEUED')
		AND NOT EXISTS(SELECT 1 FROM control_plane.run_edges e JOIN control_plane.run_nodes dependency ON dependency.id=e.source_node_id WHERE e.target_node_id=n.id AND e.type='WAITING_FOR' AND dependency.state<>'SUCCEEDED')
		AND NOT EXISTS(SELECT 1 FROM control_plane.run_nodes earlier JOIN control_plane.runs earlier_run ON earlier_run.id=earlier.run_id WHERE earlier_run.session_id=r.session_id AND earlier.created_at<n.created_at AND earlier.type='AGENT_EXECUTION' AND earlier.state IN('QUEUED','RUNNING','WAITING'))
		ORDER BY CASE WHEN a.system_key='system-assistant' THEN 0 ELSE 1 END,n.created_at FOR UPDATE OF n SKIP LOCKED LIMIT $2
