// Code generated by cmd/asyncapi-event-contracts from specs/asyncapi/interaction-hub.v1.yaml; DO NOT EDIT.

package interaction

const SchemaVersion = 1

const (
	EventThreadCreated           = "interaction.thread.created"
	EventMessageRecorded         = "interaction.message.recorded"
	EventFeedbackRequested       = "interaction.feedback.requested"
	EventApprovalRequested       = "interaction.approval.requested"
	EventHumanGateRequested      = "interaction.human_gate.requested"
	EventNotificationRequested   = "interaction.notification.requested"
	EventSubscriptionUpdated     = "interaction.subscription.updated"
	EventDeliveryRequested       = "interaction.delivery.requested"
	EventDeliveryAccepted        = "interaction.delivery.accepted"
	EventDeliveryFailed          = "interaction.delivery.failed"
	EventCallbackReceived        = "interaction.callback.received"
	EventRequestResponseRecorded = "interaction.request.response_recorded"
	EventRequestExpired          = "interaction.request.expired"
	EventRequestCancelled        = "interaction.request.cancelled"
)

const (
	AggregateCallback     = "callback"
	AggregateDelivery     = "delivery"
	AggregateMessage      = "message"
	AggregateNotification = "notification"
	AggregateRequest      = "request"
	AggregateSubscription = "subscription"
	AggregateThread       = "thread"
)

// Payload is the generated common payload envelope for domain events.
type Payload struct {
	ActorRef             string `json:"actor_ref,omitempty"`
	AgentRunRef          string `json:"agent_run_ref,omitempty"`
	AttemptNumber        int64  `json:"attempt_number,omitempty"`
	CallbackID           string `json:"callback_id,omitempty"`
	CancelledByRef       string `json:"cancelled_by_ref,omitempty"`
	ChannelMessageRef    string `json:"channel_message_ref,omitempty"`
	CorrelationID        string `json:"correlation_id,omitempty"`
	DeadlineAt           string `json:"deadline_at,omitempty"`
	DeliveryAttemptID    string `json:"delivery_attempt_id,omitempty"`
	DeliveryID           string `json:"delivery_id,omitempty"`
	ErrorClass           string `json:"error_class,omitempty"`
	ErrorCode            string `json:"error_code,omitempty"`
	IngressKind          string `json:"ingress_kind,omitempty"`
	MessageID            string `json:"message_id,omitempty"`
	NextRetryAt          string `json:"next_retry_at,omitempty"`
	NotificationID       string `json:"notification_id,omitempty"`
	NotificationKind     string `json:"notification_kind,omitempty"`
	OwnerDecisionRef     string `json:"owner_decision_ref,omitempty"`
	OwnerRequestRef      string `json:"owner_request_ref,omitempty"`
	OwnerService         string `json:"owner_service,omitempty"`
	Priority             string `json:"priority,omitempty"`
	ProcessingStatus     string `json:"processing_status,omitempty"`
	ProviderOperationRef string `json:"provider_operation_ref,omitempty"`
	RequestID            string `json:"request_id,omitempty"`
	RequestKind          string `json:"request_kind,omitempty"`
	ResponseAction       string `json:"response_action,omitempty"`
	ResponseID           string `json:"response_id,omitempty"`
	RiskClass            string `json:"risk_class,omitempty"`
	RouteID              string `json:"route_id,omitempty"`
	ScopeRef             string `json:"scope_ref,omitempty"`
	ScopeType            string `json:"scope_type,omitempty"`
	SourceKind           string `json:"source_kind,omitempty"`
	SourceOwnerKind      string `json:"source_owner_kind,omitempty"`
	SourceOwnerRef       string `json:"source_owner_ref,omitempty"`
	Status               string `json:"status,omitempty"`
	SubscriberRef        string `json:"subscriber_ref,omitempty"`
	SubscriptionID       string `json:"subscription_id,omitempty"`
	ThreadID             string `json:"thread_id,omitempty"`
	Version              int64  `json:"version,omitempty"`
}
