apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mattercodex-system
resources:
  - ../../../base/internal-rpc-authority
  - ../../../base/internal-rpc-authority-publisher
  - ../../../base/internal-rpc-authority-readback-attestor
  - ../../../base/internal-rpc-authority-restore
  - ../../../base/internal-rpc-authority-data
patches:
  - path: deployment-patch.yaml
  - path: migration-job-patch.yaml
labels:
  - pairs:
      mattercodex.dev/environment: staging
    includeSelectors: false
    includeTemplates: true
