apiVersion: v1
kind: Service
metadata:
  name: role-image-builder
  labels: {app.kubernetes.io/name: role-image-builder}
spec:
  selector: {app.kubernetes.io/name: role-image-builder}
  ports: [{name: metrics, port: 9090, targetPort: metrics, protocol: TCP}]
