apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: role-image-builder
  labels: {app.kubernetes.io/name: role-image-builder}
spec:
  selector:
    matchLabels: {app.kubernetes.io/name: role-image-builder}
  endpoints: [{port: metrics, path: /metrics, interval: 30s, scrapeTimeout: 10s}]
