apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-rpc-authority-migrator
  labels:
    app.kubernetes.io/name: internal-rpc-authority
    app.kubernetes.io/component: migrator
automountServiceAccountToken: false
