apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: internal-rpc-authority-postgres-migration
spec:
  provider: vault
  parameters:
    roleName: internal-rpc-authority-migrator
    audience: vault
    objects: |
      - objectName: "dsn"
        secretPath: "kv/data/internal-rpc-authority/postgres-migration"
        secretKey: "dsn"
        filePermission: 292
