apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: internal-rpc-authority-readback-trust
spec:
  provider: vault
  parameters:
    roleName: internal-rpc-authority-readback-attestor
    audience: vault
    objects: |
      - objectName: "manifest-root.jws"
        secretPath: "secret/data/internal-rpc-authority/readback/trust"
        secretKey: "manifest-root.jws"
        filePermission: 288
      - objectName: "credential-trust.jws"
        secretPath: "secret/data/internal-rpc-authority/readback/trust"
        secretKey: "credential-trust.jws"
        filePermission: 288
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: internal-rpc-authority-readback-database-g3
spec:
  provider: vault
  parameters:
    roleName: internal-rpc-authority-readback-attestor
    audience: vault
    objects: |
      - objectName: "username"
        secretPath: "database/static-creds/internal-rpc-authority-readback-attestor-g3"
        secretKey: "username"
        filePermission: 288
      - objectName: "password"
        secretPath: "database/static-creds/internal-rpc-authority-readback-attestor-g3"
        secretKey: "password"
        filePermission: 288
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: internal-rpc-authority-readback-database-g4
spec:
  provider: vault
  parameters:
    roleName: internal-rpc-authority-readback-attestor
    audience: vault
    objects: |
      - objectName: "username"
        secretPath: "database/static-creds/internal-rpc-authority-readback-attestor-g4"
        secretKey: "username"
        filePermission: 288
      - objectName: "password"
        secretPath: "database/static-creds/internal-rpc-authority-readback-attestor-g4"
        secretKey: "password"
        filePermission: 288
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: internal-rpc-authority-readback-database-g5
spec:
  provider: vault
  parameters:
    roleName: internal-rpc-authority-readback-attestor
    audience: vault
    objects: |
      - objectName: "username"
        secretPath: "database/static-creds/internal-rpc-authority-readback-attestor-g5"
        secretKey: "username"
        filePermission: 288
      - objectName: "password"
        secretPath: "database/static-creds/internal-rpc-authority-readback-attestor-g5"
        secretKey: "password"
        filePermission: 288
