package platform

import _ "embed"

var (
	//go:embed sql/queries_getbootstrapstate_1.sql
	queryQueriesGetbootstrapstate1 string
	//go:embed sql/queries_getoverview_1.sql
	queryQueriesGetoverview1 string
	//go:embed sql/queries_listcapabilities_1.sql
	queryQueriesListcapabilities1 string
	//go:embed sql/queries_listprojects_1.sql
	queryQueriesListprojects1 string
	//go:embed sql/queries_getproject_1.sql
	queryQueriesGetproject1 string
	//go:embed sql/queries_listmemberships_1.sql
	queryQueriesListmemberships1 string
	//go:embed sql/queries_listagents_1.sql
	queryQueriesListagents1 string
	//go:embed sql/queries_getagent_1.sql
	queryQueriesGetagent1 string
	//go:embed sql/queries_attachinstructions_1.sql
	queryQueriesAttachinstructions1 string
	//go:embed sql/queries_attachagentgrants_1.sql
	queryQueriesAttachagentgrants1 string
	//go:embed sql/queries_listworkflows_1.sql
	queryQueriesListworkflows1 string
	//go:embed sql/queries_getworkflow_1.sql
	queryQueriesGetworkflow1 string
	//go:embed sql/queries_listruns_1.sql
	queryQueriesListruns1 string
	//go:embed sql/queries_getrun_1.sql
	queryQueriesGetrun1 string
	//go:embed sql/queries_getrungraph_1.sql
	queryQueriesGetrungraph1 string
	//go:embed sql/queries_getrungraph_2.sql
	queryQueriesGetrungraph2 string
	//go:embed sql/queries_listrunevents_1.sql
	queryQueriesListrunevents1 string
	//go:embed sql/queries_listownergates_1.sql
	queryQueriesListownergates1 string
	//go:embed sql/queries_getownergate_1.sql
	queryQueriesGetownergate1 string
	//go:embed sql/queries_listartifacts_1.sql
	queryQueriesListartifacts1 string
	//go:embed sql/queries_getartifact_1.sql
	queryQueriesGetartifact1 string
	//go:embed sql/queries_listschedules_1.sql
	queryQueriesListschedules1 string
	//go:embed sql/queries_listintegrationdefinitions_1.sql
	queryQueriesListintegrationdefinitions1 string
	//go:embed sql/queries_listintegrationconnections_1.sql
	queryQueriesListintegrationconnections1 string
	//go:embed sql/queries_getintegrationconnection_1.sql
	queryQueriesGetintegrationconnection1 string
	//go:embed sql/queries_attachconnection_1.sql
	queryQueriesAttachconnection1 string
	//go:embed sql/queries_getassistant_1.sql
	queryQueriesGetassistant1 string
	//go:embed sql/queries_listassistantconversations_1.sql
	queryQueriesListassistantconversations1 string
	//go:embed sql/queries_attachconversation_1.sql
	queryQueriesAttachconversation1 string
	//go:embed sql/queries_attachconversation_2.sql
	queryQueriesAttachconversation2 string
	//go:embed sql/queries_listauditevents_1.sql
	queryQueriesListauditevents1 string
)
