package platform

import _ "embed"

var (
	//go:embed sql/commands_getrunforgraph_1.sql
	queryCommandsGetrunforgraph1 string
	//go:embed sql/commands_execute_1.sql
	queryCommandsExecute1 string
	//go:embed sql/commands_execute_2.sql
	queryCommandsExecute2 string
	//go:embed sql/commands_execute_3.sql
	queryCommandsExecute3 string
	//go:embed sql/commands_completeonboarding_1.sql
	queryCommandsCompleteonboarding1 string
	//go:embed sql/commands_createproject_1.sql
	queryCommandsCreateproject1 string
	//go:embed sql/commands_createproject_2.sql
	queryCommandsCreateproject2 string
	//go:embed sql/commands_updateproject_1.sql
	queryCommandsUpdateproject1 string
	//go:embed sql/commands_changemembership_1.sql
	queryCommandsChangemembership1 string
	//go:embed sql/commands_changemembership_2.sql
	queryCommandsChangemembership2 string
	//go:embed sql/commands_changemembership_3.sql
	queryCommandsChangemembership3 string
	//go:embed sql/commands_createagent_1.sql
	queryCommandsCreateagent1 string
	//go:embed sql/commands_createagent_2.sql
	queryCommandsCreateagent2 string
	//go:embed sql/commands_mustprojectid_1.sql
	queryCommandsMustprojectid1 string
	//go:embed sql/commands_changeagent_1.sql
	queryCommandsChangeagent1 string
	//go:embed sql/commands_changeagent_2.sql
	queryCommandsChangeagent2 string
	//go:embed sql/commands_changeagent_3.sql
	queryCommandsChangeagent3 string
	//go:embed sql/commands_changeagent_4.sql
	queryCommandsChangeagent4 string
	//go:embed sql/commands_changeinstructions_1.sql
	queryCommandsChangeinstructions1 string
	//go:embed sql/commands_changeinstructions_2.sql
	queryCommandsChangeinstructions2 string
	//go:embed sql/commands_changeinstructions_3.sql
	queryCommandsChangeinstructions3 string
	//go:embed sql/commands_changeinstructions_4.sql
	queryCommandsChangeinstructions4 string
	//go:embed sql/commands_changeinstructions_5.sql
	queryCommandsChangeinstructions5 string
	//go:embed sql/commands_changeinstructions_6.sql
	queryCommandsChangeinstructions6 string
	//go:embed sql/commands_changeinstructions_7.sql
	queryCommandsChangeinstructions7 string
	//go:embed sql/commands_changeinstructions_8.sql
	queryCommandsChangeinstructions8 string
	//go:embed sql/commands_changeinstructions_9.sql
	queryCommandsChangeinstructions9 string
	//go:embed sql/commands_changeinstructions_10.sql
	queryCommandsChangeinstructions10 string
	//go:embed sql/commands_changeagentbinding_1.sql
	queryCommandsChangeagentbinding1 string
	//go:embed sql/commands_changeagentbinding_2.sql
	queryCommandsChangeagentbinding2 string
	//go:embed sql/commands_changeagentbinding_3.sql
	queryCommandsChangeagentbinding3 string
	//go:embed sql/commands_changeagentbinding_4.sql
	queryCommandsChangeagentbinding4 string
	//go:embed sql/commands_changeagentbinding_5.sql
	queryCommandsChangeagentbinding5 string
	//go:embed sql/commands_changeagentbinding_6.sql
	queryCommandsChangeagentbinding6 string
	//go:embed sql/commands_changeworkflow_1.sql
	queryCommandsChangeworkflow1 string
	//go:embed sql/commands_changeworkflow_2.sql
	queryCommandsChangeworkflow2 string
	//go:embed sql/commands_changeworkflow_3.sql
	queryCommandsChangeworkflow3 string
	//go:embed sql/commands_changeworkflow_4.sql
	queryCommandsChangeworkflow4 string
	//go:embed sql/commands_changeworkflow_5.sql
	queryCommandsChangeworkflow5 string
	//go:embed sql/commands_changeworkflow_6.sql
	queryCommandsChangeworkflow6 string
	//go:embed sql/commands_changeworkflow_7.sql
	queryCommandsChangeworkflow7 string
	//go:embed sql/commands_changeworkflow_8.sql
	queryCommandsChangeworkflow8 string
	//go:embed sql/commands_changeworkflow_9.sql
	queryCommandsChangeworkflow9 string
	//go:embed sql/commands_launchrun_1.sql
	queryCommandsLaunchrun1 string
	//go:embed sql/commands_launchrun_2.sql
	queryCommandsLaunchrun2 string
	//go:embed sql/commands_launchrun_3.sql
	queryCommandsLaunchrun3 string
	//go:embed sql/commands_launchrun_4.sql
	queryCommandsLaunchrun4 string
	//go:embed sql/commands_launchrun_5.sql
	queryCommandsLaunchrun5 string
	//go:embed sql/commands_launchrun_6.sql
	queryCommandsLaunchrun6 string
	//go:embed sql/commands_launchrun_7.sql
	queryCommandsLaunchrun7 string
	//go:embed sql/commands_launchrun_8.sql
	queryCommandsLaunchrun8 string
	//go:embed sql/commands_launchrun_9.sql
	queryCommandsLaunchrun9 string
	//go:embed sql/commands_launchrun_10.sql
	queryCommandsLaunchrun10 string
	//go:embed sql/commands_launchrun_11.sql
	queryCommandsLaunchrun11 string
	//go:embed sql/commands_launchrun_12.sql
	queryCommandsLaunchrun12 string
	//go:embed sql/commands_insertagentnode_1.sql
	queryCommandsInsertagentnode1 string
	//go:embed sql/commands_insertagentnode_2.sql
	queryCommandsInsertagentnode2 string
	//go:embed sql/commands_insertagentnode_3.sql
	queryCommandsInsertagentnode3 string
	//go:embed sql/commands_emitplatformevent_1.sql
	queryCommandsEmitplatformevent1 string
	//go:embed sql/commands_emitplatformevent_2.sql
	queryCommandsEmitplatformevent2 string
	//go:embed sql/commands_emitrunevent_1.sql
	queryCommandsEmitrunevent1 string
	//go:embed sql/commands_emitrunevent_2.sql
	queryCommandsEmitrunevent2 string
	//go:embed sql/commands_emitrunevent_3.sql
	queryCommandsEmitrunevent3 string
	//go:embed sql/commands_emitrunevent_4.sql
	queryCommandsEmitrunevent4 string
	//go:embed sql/commands_readrungraphtx_1.sql
	queryCommandsReadrungraphtx1 string
	//go:embed sql/commands_readrungraphtx_2.sql
	queryCommandsReadrungraphtx2 string
	//go:embed sql/commands_addsessionturn_1.sql
	queryCommandsAddsessionturn1 string
	//go:embed sql/commands_addsessionturn_2.sql
	queryCommandsAddsessionturn2 string
	//go:embed sql/commands_addsessionturn_3.sql
	queryCommandsAddsessionturn3 string
	//go:embed sql/commands_addsessionturn_4.sql
	queryCommandsAddsessionturn4 string
	//go:embed sql/commands_addsessionturn_5.sql
	queryCommandsAddsessionturn5 string
	//go:embed sql/commands_addsessionturn_6.sql
	queryCommandsAddsessionturn6 string
	//go:embed sql/commands_changerun_1.sql
	queryCommandsChangerun1 string
	//go:embed sql/commands_changerun_2.sql
	queryCommandsChangerun2 string
	//go:embed sql/commands_changerun_3.sql
	queryCommandsChangerun3 string
	//go:embed sql/commands_changerun_4.sql
	queryCommandsChangerun4 string
	//go:embed sql/commands_changerun_5.sql
	queryCommandsChangerun5 string
	//go:embed sql/commands_changerun_6.sql
	queryCommandsChangerun6 string
	//go:embed sql/commands_changerun_7.sql
	queryCommandsChangerun7 string
	//go:embed sql/commands_changerun_8.sql
	queryCommandsChangerun8 string
	//go:embed sql/commands_changerun_9.sql
	queryCommandsChangerun9 string
	//go:embed sql/commands_changerun_10.sql
	queryCommandsChangerun10 string
	//go:embed sql/commands_changerun_11.sql
	queryCommandsChangerun11 string
	//go:embed sql/commands_resolvegate_1.sql
	queryCommandsResolvegate1 string
	//go:embed sql/commands_resolvegate_2.sql
	queryCommandsResolvegate2 string
	//go:embed sql/commands_resolvegate_3.sql
	queryCommandsResolvegate3 string
	//go:embed sql/commands_resolvegate_4.sql
	queryCommandsResolvegate4 string
	//go:embed sql/commands_mustrunref_1.sql
	queryCommandsMustrunref1 string
)
