package platform

import _ "embed"

var (
	//go:embed sql/repository_ready_1.sql
	queryRepositoryReady1 string
	//go:embed sql/repository_bootstrap_1.sql
	queryRepositoryBootstrap1 string
	//go:embed sql/repository_bootstrap_2.sql
	queryRepositoryBootstrap2 string
	//go:embed sql/repository_bootstrap_3.sql
	queryRepositoryBootstrap3 string
	//go:embed sql/repository_bootstrap_4.sql
	queryRepositoryBootstrap4 string
	//go:embed sql/bootstrap_create_system_membership.sql
	queryRepositoryBootstrapSystemMembership string
	//go:embed sql/repository_bootstrap_5.sql
	queryRepositoryBootstrap5 string
	//go:embed sql/repository_bootstrap_6.sql
	queryRepositoryBootstrap6 string
	//go:embed sql/repository_bootstrap_7.sql
	queryRepositoryBootstrap7 string
	//go:embed sql/repository_bootstrap_8.sql
	queryRepositoryBootstrap8 string
	//go:embed sql/repository_bootstrap_9.sql
	queryRepositoryBootstrap9 string
	//go:embed sql/repository_bootstrap_10.sql
	queryRepositoryBootstrap10 string
	//go:embed sql/repository_bootstrap_11.sql
	queryRepositoryBootstrap11 string
	//go:embed sql/repository_bootstrap_12.sql
	queryRepositoryBootstrap12 string
	//go:embed sql/principal_resolve_verified_identity.sql
	queryRepositoryResolveprincipal1 string
	//go:embed sql/proof_owner_lock_installation.sql
	queryRepositoryResolveProofAuthorityOwner1 string
	//go:embed sql/proof_owner_find_subject.sql
	queryRepositoryResolveProofAuthorityOwner2 string
	//go:embed sql/proof_owner_create_subject.sql
	queryRepositoryResolveProofAuthorityOwner3 string
	//go:embed sql/proof_owner_create_membership.sql
	queryRepositoryResolveProofAuthorityOwner4 string
	//go:embed sql/proof_owner_claim_installation.sql
	queryRepositoryResolveProofAuthorityOwner5 string
	//go:embed sql/proof_owner_check_membership.sql
	queryRepositoryResolveProofAuthorityOwner6 string
	//go:embed sql/proof_system_resolve_identity.sql
	queryRepositoryResolveProofAuthoritySystem1 string
	//go:embed sql/proof_project_authorize_membership.sql
	queryRepositoryResolveProofAuthorityProject1 string
	//go:embed sql/proof_next_revision.sql
	queryRepositoryNextProofRevision1 string
	//go:embed sql/repository_resolvescope_1.sql
	queryRepositoryResolvescope1 string
)
