package platform

import _ "embed"

var (
	//go:embed sql/runtime_claimexecution_1.sql
	queryRuntimeClaimexecution1 string
	//go:embed sql/runtime_claimexecution_2.sql
	queryRuntimeClaimexecution2 string
	//go:embed sql/runtime_claimexecution_3.sql
	queryRuntimeClaimexecution3 string
	//go:embed sql/runtime_claimexecution_4.sql
	queryRuntimeClaimexecution4 string
	//go:embed sql/runtime_claimexecution_5.sql
	queryRuntimeClaimexecution5 string
	//go:embed sql/runtime_lease_1.sql
	queryRuntimeLease1 string
	//go:embed sql/runtime_lease_for_update_1.sql
	queryRuntimeLeaseForUpdate1 string
	//go:embed sql/runtime_renewexecution_1.sql
	queryRuntimeRenewexecution1 string
	//go:embed sql/runtime_reportprogress_1.sql
	queryRuntimeReportprogress1 string
	//go:embed sql/runtime_completeexecution_1.sql
	queryRuntimeCompleteexecution1 string
	//go:embed sql/runtime_completeexecution_2.sql
	queryRuntimeCompleteexecution2 string
	//go:embed sql/runtime_completeexecution_3.sql
	queryRuntimeCompleteexecution3 string
	//go:embed sql/runtime_completeexecution_4.sql
	queryRuntimeCompleteexecution4 string
	//go:embed sql/runtime_completeexecution_5.sql
	queryRuntimeCompleteexecution5 string
	//go:embed sql/runtime_completeexecution_6.sql
	queryRuntimeCompleteexecution6 string
	//go:embed sql/runtime_completeexecution_7.sql
	queryRuntimeCompleteexecution7 string
	//go:embed sql/runtime_completeexecution_8.sql
	queryRuntimeCompleteexecution8 string
	//go:embed sql/runtime_completeexecution_9.sql
	queryRuntimeCompleteexecution9 string
	//go:embed sql/runtime_completeexecution_10.sql
	queryRuntimeCompleteexecution10 string
	//go:embed sql/runtime_completeexecution_11.sql
	queryRuntimeCompleteexecution11 string
	//go:embed sql/runtime_completeexecution_12.sql
	queryRuntimeCompleteexecution12 string
	//go:embed sql/runtime_completeexecution_13.sql
	queryRuntimeCompleteexecution13 string
	//go:embed sql/runtime_completeexecution_14.sql
	queryRuntimeCompleteexecution14 string
	//go:embed sql/runtime_completeexecution_15.sql
	queryRuntimeCompleteexecution15 string
	//go:embed sql/runtime_completeexecution_16.sql
	queryRuntimeCompleteexecution16 string
	//go:embed sql/runtime_completeexecution_17.sql
	queryRuntimeCompleteexecution17 string
	//go:embed sql/runtime_completeexecution_18.sql
	queryRuntimeCompleteexecution18 string
	//go:embed sql/runtime_completeexecution_19.sql
	queryRuntimeCompleteexecution19 string
	//go:embed sql/runtime_completeexecution_20.sql
	queryRuntimeCompleteexecution20 string
	//go:embed sql/runtime_completeexecution_21.sql
	queryRuntimeCompleteexecution21 string
	//go:embed sql/runtime_completeexecution_22.sql
	queryRuntimeCompleteexecution22 string
	//go:embed sql/runtime_completeexecution_23.sql
	queryRuntimeCompleteexecution23 string
	//go:embed sql/runtime_delegateexecution_1.sql
	queryRuntimeDelegateexecution1 string
	//go:embed sql/runtime_delegateexecution_2.sql
	queryRuntimeDelegateexecution2 string
	//go:embed sql/runtime_delegateexecution_3.sql
	queryRuntimeDelegateexecution3 string
	//go:embed sql/runtime_delegateexecution_4.sql
	queryRuntimeDelegateexecution4 string
	//go:embed sql/runtime_delegateexecution_5.sql
	queryRuntimeDelegateexecution5 string
	//go:embed sql/runtime_delegateexecution_6.sql
	queryRuntimeDelegateexecution6 string
	//go:embed sql/runtime_delegateexecution_7.sql
	queryRuntimeDelegateexecution7 string
	//go:embed sql/runtime_delegateexecution_8.sql
	queryRuntimeDelegateexecution8 string
	//go:embed sql/runtime_delegateexecution_9.sql
	queryRuntimeDelegateexecution9 string
	//go:embed sql/runtime_delegateexecution_10.sql
	queryRuntimeDelegateexecution10 string
	//go:embed sql/runtime_delivercallback_1.sql
	queryRuntimeDelivercallback1 string
	//go:embed sql/runtime_delivercallback_2.sql
	queryRuntimeDelivercallback2 string
	//go:embed sql/runtime_delivercallback_3.sql
	queryRuntimeDelivercallback3 string
)
