apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kodex-system
resources:
  - runtime.yaml
  - networkpolicy.yaml
  - rbac.yaml
  - vault-secret-provider-classes.yaml
  - snapshot-secret.yaml
configMapGenerator:
  - name: internal-rpc-authority-publisher-target-registry
    files:
      - key-delivery-targets.yaml
      - authority-policy.json
generatorOptions:
  disableNameSuffixHash: true
