apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/interaction-gateway
configMapGenerator:
  - name: interaction-gateway-runtime
    behavior: merge
    literals:
      - INTERACTION_GATEWAY_S3_PUBLIC_DOWNLOAD_ENDPOINT=https://artifacts.mattercodex.dev
patches:
  - path: deployment-patch.yaml
  - path: poddisruptionbudget-patch.yaml
labels:
  - pairs: {mattercodex.dev/environment: production}
    includeSelectors: false
    includeTemplates: true
