apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/interaction-gateway
configMapGenerator:
  - name: interaction-gateway-runtime
    behavior: merge
    literals:
      - INTERACTION_GATEWAY_ARTIFACT_DOWNLOAD_BASE_URL=https://interaction-artifacts.mattercodex.dev
      - INTERACTION_GATEWAY_MATTERMOST_MAPPING_EXPECTED_REVISION=production-r1
patches:
  - path: deployment-patch.yaml
  - path: poddisruptionbudget-patch.yaml
labels:
  - pairs: {mattercodex.dev/environment: production}
    includeSelectors: false
    includeTemplates: true
