// Package emailbridgeapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package emailbridgeapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	BridgeTokenScopes bridgeTokenContextKey = "bridgeToken.Scopes"
)

// Defines values for ConfigurationManagedBy.
const (
	Git ConfigurationManagedBy = "git"
	Ui  ConfigurationManagedBy = "ui"
)

// Valid indicates whether the value is a known member of the ConfigurationManagedBy enum.
func (e ConfigurationManagedBy) Valid() bool {
	switch e {
	case Git:
		return true
	case Ui:
		return true
	default:
		return false
	}
}

// Defines values for ConfigurationVersion.
const (
	EmailBridgev1 ConfigurationVersion = "email-bridge/v1"
)

// Valid indicates whether the value is a known member of the ConfigurationVersion enum.
func (e ConfigurationVersion) Valid() bool {
	switch e {
	case EmailBridgev1:
		return true
	default:
		return false
	}
}

// Defines values for EndpointTlsMode.
const (
	Implicit EndpointTlsMode = "implicit"
	Starttls EndpointTlsMode = "starttls"
)

// Valid indicates whether the value is a known member of the EndpointTlsMode enum.
func (e EndpointTlsMode) Valid() bool {
	switch e {
	case Implicit:
		return true
	case Starttls:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	CONFLICT     ErrorCode = "CONFLICT"
	DENIED       ErrorCode = "DENIED"
	GATEREQUIRED ErrorCode = "GATE_REQUIRED"
	INVALID      ErrorCode = "INVALID"
	NOTFOUND     ErrorCode = "NOT_FOUND"
	UNAVAILABLE  ErrorCode = "UNAVAILABLE"
	UNSUPPORTED  ErrorCode = "UNSUPPORTED"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case CONFLICT:
		return true
	case DENIED:
		return true
	case GATEREQUIRED:
		return true
	case INVALID:
		return true
	case NOTFOUND:
		return true
	case UNAVAILABLE:
		return true
	case UNSUPPORTED:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	NotReady HealthStatus = "not_ready"
	Ready    HealthStatus = "ready"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case NotReady:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for MailboxFolder.
const (
	INBOX MailboxFolder = "INBOX"
)

// Valid indicates whether the value is a known member of the MailboxFolder enum.
func (e MailboxFolder) Valid() bool {
	switch e {
	case INBOX:
		return true
	default:
		return false
	}
}

// Defines values for MessageStatusStatus.
const (
	Accepted  MessageStatusStatus = "accepted"
	Deleted   MessageStatusStatus = "deleted"
	Delivered MessageStatusStatus = "delivered"
	Failed    MessageStatusStatus = "failed"
	Unknown   MessageStatusStatus = "unknown"
)

// Valid indicates whether the value is a known member of the MessageStatusStatus enum.
func (e MessageStatusStatus) Valid() bool {
	switch e {
	case Accepted:
		return true
	case Deleted:
		return true
	case Delivered:
		return true
	case Failed:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for Operation.
const (
	OperationDelete    Operation = "delete"
	OperationDownload  Operation = "download"
	OperationFetch     Operation = "fetch"
	OperationForward   Operation = "forward"
	OperationHealth    Operation = "health"
	OperationList      Operation = "list"
	OperationMailboxes Operation = "mailboxes"
	OperationMark      Operation = "mark"
	OperationReceipt   Operation = "receipt"
	OperationReply     Operation = "reply"
	OperationReplyAll  Operation = "reply_all"
	OperationSearch    Operation = "search"
	OperationSend      Operation = "send"
)

// Valid indicates whether the value is a known member of the Operation enum.
func (e Operation) Valid() bool {
	switch e {
	case OperationDelete:
		return true
	case OperationDownload:
		return true
	case OperationFetch:
		return true
	case OperationForward:
		return true
	case OperationHealth:
		return true
	case OperationList:
		return true
	case OperationMailboxes:
		return true
	case OperationMark:
		return true
	case OperationReceipt:
		return true
	case OperationReply:
		return true
	case OperationReplyAll:
		return true
	case OperationSearch:
		return true
	case OperationSend:
		return true
	default:
		return false
	}
}

// Defines values for Policy.
const (
	Allow     Policy = "allow"
	Deny      Policy = "deny"
	HumanGate Policy = "human_gate"
)

// Valid indicates whether the value is a known member of the Policy enum.
func (e Policy) Valid() bool {
	switch e {
	case Allow:
		return true
	case Deny:
		return true
	case HumanGate:
		return true
	default:
		return false
	}
}

// Attachment defines model for Attachment.
type Attachment struct {
	ContentBase64 string `json:"content_base64"`
	ContentType   string `json:"content_type"`
	Filename      string `json:"filename"`
}

// AuthorizationDecision defines model for AuthorizationDecision.
type AuthorizationDecision struct {
	ActorId               string    `json:"actor_id"`
	AgentId               string    `json:"agent_id"`
	AgentScope            Scope     `json:"agent_scope"`
	Allowed               bool      `json:"allowed"`
	ConfigurationRevision int64     `json:"configuration_revision"`
	ConnectionId          string    `json:"connection_id"`
	ConnectionScope       Scope     `json:"connection_scope"`
	CredentialGeneration  int64     `json:"credential_generation"`
	EffectKey             string    `json:"effect_key"`
	ExpiresAt             int64     `json:"expires_at"`
	GateApproved          bool      `json:"gate_approved"`
	GrantId               string    `json:"grant_id"`
	InputSha256           string    `json:"input_sha256"`
	MailboxId             string    `json:"mailbox_id"`
	Operation             Operation `json:"operation"`
	Policy                Policy    `json:"policy"`
	ResourceScope         Scope     `json:"resource_scope"`
	TenantId              string    `json:"tenant_id"`
	UserScope             Scope     `json:"user_scope"`
}

// AuthorizationRequest defines model for AuthorizationRequest.
type AuthorizationRequest struct {
	CallerSpiffeId        string    `json:"caller_spiffe_id"`
	ConfigurationRevision int64     `json:"configuration_revision"`
	EffectKey             string    `json:"effect_key"`
	InputSha256           string    `json:"input_sha256"`
	InvocationToken       string    `json:"invocation_token"`
	MailboxId             string    `json:"mailbox_id"`
	Operation             Operation `json:"operation"`
	Sender                string    `json:"sender"`
}

// Command defines model for Command.
type Command struct {
	AttachmentIndex int          `json:"attachment_index,omitempty"`
	Cursor          string       `json:"cursor,omitempty"`
	EffectKey       string       `json:"effect_key,omitempty"`
	Folder          string       `json:"folder,omitempty"`
	MailboxId       string       `json:"mailbox_id"`
	Message         MessageInput `json:"message,omitempty"`
	Operation       Operation    `json:"operation"`
	Query           string       `json:"query,omitempty"`
	ReceiptId       string       `json:"receipt_id,omitempty"`
	Uid             string       `json:"uid,omitempty"`
}

// Configuration defines model for Configuration.
type Configuration struct {
	Mailboxes []Mailbox              `json:"mailboxes"`
	ManagedBy ConfigurationManagedBy `json:"managed_by"`
	Revision  int64                  `json:"revision"`
	Source    string                 `json:"source"`
	Version   ConfigurationVersion   `json:"version"`
}

// ConfigurationManagedBy defines model for Configuration.ManagedBy.
type ConfigurationManagedBy string

// ConfigurationVersion defines model for Configuration.Version.
type ConfigurationVersion string

// Descriptor defines model for Descriptor.
type Descriptor struct {
	Generation int64  `json:"generation"`
	Name       string `json:"name"`
}

// Endpoint defines model for Endpoint.
type Endpoint struct {
	Ca         Descriptor      `json:"ca"`
	Host       string          `json:"host"`
	Password   Descriptor      `json:"password"`
	Port       int             `json:"port"`
	ServerName string          `json:"server_name"`
	TlsMode    EndpointTlsMode `json:"tls_mode"`
	Username   Descriptor      `json:"username"`
}

// EndpointTlsMode defines model for Endpoint.TlsMode.
type EndpointTlsMode string

// Error defines model for Error.
type Error struct {
	Code ErrorCode `json:"code"`
}

// ErrorCode defines model for Error.Code.
type ErrorCode string

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Limits defines model for Limits.
type Limits struct {
	AttachmentBytes int `json:"attachment_bytes"`
	MaxAttachments  int `json:"max_attachments"`
	MaxRecipients   int `json:"max_recipients"`
	MessageBytes    int `json:"message_bytes"`
	PageSize        int `json:"page_size"`
	ScanMessages    int `json:"scan_messages"`
	TimeoutSeconds  int `json:"timeout_seconds"`
}

// MailHeader defines model for MailHeader.
type MailHeader struct {
	From    string `json:"from"`
	Size    int    `json:"size"`
	Subject string `json:"subject"`
	To      string `json:"to"`
	Uid     string `json:"uid"`
}

// Mailbox defines model for Mailbox.
type Mailbox struct {
	ConnectionId string            `json:"connection_id"`
	Enabled      bool              `json:"enabled"`
	EnvelopeFrom string            `json:"envelope_from"`
	Folder       MailboxFolder     `json:"folder"`
	HelloName    string            `json:"hello_name"`
	Id           string            `json:"id"`
	Limits       Limits            `json:"limits"`
	Policies     []OperationPolicy `json:"policies"`
	Pop          Endpoint          `json:"pop"`
	Recipients   []string          `json:"recipients"`
	Revision     int64             `json:"revision"`
	Sender       string            `json:"sender"`
	Smtp         Endpoint          `json:"smtp"`
	TenantId     string            `json:"tenant_id"`
}

// MailboxFolder defines model for Mailbox.Folder.
type MailboxFolder string

// MessageInput defines model for MessageInput.
type MessageInput struct {
	Attachments []Attachment `json:"attachments,omitempty"`
	Bcc         []string     `json:"bcc,omitempty"`
	BodyText    string       `json:"body_text"`
	Cc          []string     `json:"cc,omitempty"`
	From        string       `json:"from"`
	SourceUid   string       `json:"source_uid,omitempty"`
	Subject     string       `json:"subject"`
	To          string       `json:"to"`
}

// MessageStatus defines model for MessageStatus.
type MessageStatus struct {
	MessageId string              `json:"message_id"`
	Status    MessageStatusStatus `json:"status"`
}

// MessageStatusStatus defines model for MessageStatus.Status.
type MessageStatusStatus string

// Operation defines model for Operation.
type Operation string

// OperationPolicy defines model for OperationPolicy.
type OperationPolicy struct {
	Operation Operation `json:"operation"`
	Policy    Policy    `json:"policy"`
}

// Policy defines model for Policy.
type Policy string

// Result defines model for Result.
type Result struct {
	Attachments        []Attachment `json:"attachments,omitempty"`
	BodyText           string       `json:"body_text,omitempty"`
	FolderSupport      bool         `json:"folder_support,omitempty"`
	Headers            []MailHeader `json:"headers,omitempty"`
	Mailboxes          []string     `json:"mailboxes,omitempty"`
	MessageId          string       `json:"message_id,omitempty"`
	NextCursor         string       `json:"next_cursor,omitempty"`
	ReadStateSupported bool         `json:"read_state_supported,omitempty"`
	Status             string       `json:"status"`
}

// Scope defines model for Scope.
type Scope struct {
	MailboxId  string      `json:"mailbox_id"`
	Operations []Operation `json:"operations"`
	Recipients []string    `json:"recipients"`
	Sender     string      `json:"sender"`
}

// bridgeTokenContextKey is the context key for bridgeToken security scheme
type bridgeTokenContextKey string

// GetHealthParams defines parameters for GetHealth.
type GetHealthParams struct {
	Sender string `form:"sender" json:"sender"`
}

// SendMessageParams defines parameters for SendMessage.
type SendMessageParams struct {
	Sender         string `form:"sender" json:"sender"`
	IdempotencyKey string `json:"Idempotency-Key"`
}

// ReconcileMessageParams defines parameters for ReconcileMessage.
type ReconcileMessageParams struct {
	Sender string `form:"sender" json:"sender"`
}

// GetMessageStatusParams defines parameters for GetMessageStatus.
type GetMessageStatusParams struct {
	Sender string `form:"sender" json:"sender"`
}

// ResolveEmailAuthorizationJSONRequestBody defines body for ResolveEmailAuthorization for application/json ContentType.
type ResolveEmailAuthorizationJSONRequestBody = AuthorizationRequest

// ExecuteMailboxOperationJSONRequestBody defines body for ExecuteMailboxOperation for application/json ContentType.
type ExecuteMailboxOperationJSONRequestBody = Command

// SendMessageJSONRequestBody defines body for SendMessage for application/json ContentType.
type SendMessageJSONRequestBody = MessageInput

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ResolveEmailAuthorizationWithBody request with any body
	ResolveEmailAuthorizationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ResolveEmailAuthorization(ctx context.Context, body ResolveEmailAuthorizationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, params *GetHealthParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ExecuteMailboxOperationWithBody request with any body
	ExecuteMailboxOperationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ExecuteMailboxOperation(ctx context.Context, body ExecuteMailboxOperationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SendMessageWithBody request with any body
	SendMessageWithBody(ctx context.Context, params *SendMessageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SendMessage(ctx context.Context, params *SendMessageParams, body SendMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ReconcileMessage request
	ReconcileMessage(ctx context.Context, effectKey string, params *ReconcileMessageParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetMessageStatus request
	GetMessageStatus(ctx context.Context, messageId string, params *GetMessageStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ResolveEmailAuthorizationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewResolveEmailAuthorizationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ResolveEmailAuthorization(ctx context.Context, body ResolveEmailAuthorizationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewResolveEmailAuthorizationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, params *GetHealthParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExecuteMailboxOperationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExecuteMailboxOperationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ExecuteMailboxOperation(ctx context.Context, body ExecuteMailboxOperationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExecuteMailboxOperationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendMessageWithBody(ctx context.Context, params *SendMessageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendMessageRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SendMessage(ctx context.Context, params *SendMessageParams, body SendMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSendMessageRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ReconcileMessage(ctx context.Context, effectKey string, params *ReconcileMessageParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReconcileMessageRequest(c.Server, effectKey, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetMessageStatus(ctx context.Context, messageId string, params *GetMessageStatusParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetMessageStatusRequest(c.Server, messageId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewResolveEmailAuthorizationRequest calls the generic ResolveEmailAuthorization builder with application/json body
func NewResolveEmailAuthorizationRequest(server string, body ResolveEmailAuthorizationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewResolveEmailAuthorizationRequestWithBody(server, "application/json", bodyReader)
}

// NewResolveEmailAuthorizationRequestWithBody generates requests for ResolveEmailAuthorization with any type of body
func NewResolveEmailAuthorizationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/email-authorizations/resolve")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string, params *GetHealthParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sender", params.Sender, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewExecuteMailboxOperationRequest calls the generic ExecuteMailboxOperation builder with application/json body
func NewExecuteMailboxOperationRequest(server string, body ExecuteMailboxOperationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewExecuteMailboxOperationRequestWithBody(server, "application/json", bodyReader)
}

// NewExecuteMailboxOperationRequestWithBody generates requests for ExecuteMailboxOperation with any type of body
func NewExecuteMailboxOperationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/mailbox-operations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSendMessageRequest calls the generic SendMessage builder with application/json body
func NewSendMessageRequest(server string, params *SendMessageParams, body SendMessageJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSendMessageRequestWithBody(server, params, "application/json", bodyReader)
}

// NewSendMessageRequestWithBody generates requests for SendMessage with any type of body
func NewSendMessageRequestWithBody(server string, params *SendMessageParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/messages")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sender", params.Sender, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Idempotency-Key", params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Idempotency-Key", headerParam0)

	}

	return req, nil
}

// NewReconcileMessageRequest generates requests for ReconcileMessage
func NewReconcileMessageRequest(server string, effectKey string, params *ReconcileMessageParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "effect_key", effectKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/messages/by-idempotency-key/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sender", params.Sender, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetMessageStatusRequest generates requests for GetMessageStatus
func NewGetMessageStatusRequest(server string, messageId string, params *GetMessageStatusParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "message_id", messageId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/messages/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sender", params.Sender, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ResolveEmailAuthorizationWithBodyWithResponse request with any body
	ResolveEmailAuthorizationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ResolveEmailAuthorizationResponse, error)

	ResolveEmailAuthorizationWithResponse(ctx context.Context, body ResolveEmailAuthorizationJSONRequestBody, reqEditors ...RequestEditorFn) (*ResolveEmailAuthorizationResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, params *GetHealthParams, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// ExecuteMailboxOperationWithBodyWithResponse request with any body
	ExecuteMailboxOperationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExecuteMailboxOperationResponse, error)

	ExecuteMailboxOperationWithResponse(ctx context.Context, body ExecuteMailboxOperationJSONRequestBody, reqEditors ...RequestEditorFn) (*ExecuteMailboxOperationResponse, error)

	// SendMessageWithBodyWithResponse request with any body
	SendMessageWithBodyWithResponse(ctx context.Context, params *SendMessageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendMessageResponse, error)

	SendMessageWithResponse(ctx context.Context, params *SendMessageParams, body SendMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*SendMessageResponse, error)

	// ReconcileMessageWithResponse request
	ReconcileMessageWithResponse(ctx context.Context, effectKey string, params *ReconcileMessageParams, reqEditors ...RequestEditorFn) (*ReconcileMessageResponse, error)

	// GetMessageStatusWithResponse request
	GetMessageStatusWithResponse(ctx context.Context, messageId string, params *GetMessageStatusParams, reqEditors ...RequestEditorFn) (*GetMessageStatusResponse, error)
}

type ResolveEmailAuthorizationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AuthorizationDecision
}

// Status returns HTTPResponse.Status
func (r ResolveEmailAuthorizationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ResolveEmailAuthorizationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ResolveEmailAuthorizationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Health
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetHealthResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ExecuteMailboxOperationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Result
}

// Status returns HTTPResponse.Status
func (r ExecuteMailboxOperationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExecuteMailboxOperationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ExecuteMailboxOperationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SendMessageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *MessageStatus
}

// Status returns HTTPResponse.Status
func (r SendMessageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SendMessageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SendMessageResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ReconcileMessageResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MessageStatus
}

// Status returns HTTPResponse.Status
func (r ReconcileMessageResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ReconcileMessageResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ReconcileMessageResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetMessageStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MessageStatus
}

// Status returns HTTPResponse.Status
func (r GetMessageStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetMessageStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetMessageStatusResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ResolveEmailAuthorizationWithBodyWithResponse request with arbitrary body returning *ResolveEmailAuthorizationResponse
func (c *ClientWithResponses) ResolveEmailAuthorizationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ResolveEmailAuthorizationResponse, error) {
	rsp, err := c.ResolveEmailAuthorizationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseResolveEmailAuthorizationResponse(rsp)
}

func (c *ClientWithResponses) ResolveEmailAuthorizationWithResponse(ctx context.Context, body ResolveEmailAuthorizationJSONRequestBody, reqEditors ...RequestEditorFn) (*ResolveEmailAuthorizationResponse, error) {
	rsp, err := c.ResolveEmailAuthorization(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseResolveEmailAuthorizationResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, params *GetHealthParams, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// ExecuteMailboxOperationWithBodyWithResponse request with arbitrary body returning *ExecuteMailboxOperationResponse
func (c *ClientWithResponses) ExecuteMailboxOperationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ExecuteMailboxOperationResponse, error) {
	rsp, err := c.ExecuteMailboxOperationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExecuteMailboxOperationResponse(rsp)
}

func (c *ClientWithResponses) ExecuteMailboxOperationWithResponse(ctx context.Context, body ExecuteMailboxOperationJSONRequestBody, reqEditors ...RequestEditorFn) (*ExecuteMailboxOperationResponse, error) {
	rsp, err := c.ExecuteMailboxOperation(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExecuteMailboxOperationResponse(rsp)
}

// SendMessageWithBodyWithResponse request with arbitrary body returning *SendMessageResponse
func (c *ClientWithResponses) SendMessageWithBodyWithResponse(ctx context.Context, params *SendMessageParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SendMessageResponse, error) {
	rsp, err := c.SendMessageWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendMessageResponse(rsp)
}

func (c *ClientWithResponses) SendMessageWithResponse(ctx context.Context, params *SendMessageParams, body SendMessageJSONRequestBody, reqEditors ...RequestEditorFn) (*SendMessageResponse, error) {
	rsp, err := c.SendMessage(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSendMessageResponse(rsp)
}

// ReconcileMessageWithResponse request returning *ReconcileMessageResponse
func (c *ClientWithResponses) ReconcileMessageWithResponse(ctx context.Context, effectKey string, params *ReconcileMessageParams, reqEditors ...RequestEditorFn) (*ReconcileMessageResponse, error) {
	rsp, err := c.ReconcileMessage(ctx, effectKey, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseReconcileMessageResponse(rsp)
}

// GetMessageStatusWithResponse request returning *GetMessageStatusResponse
func (c *ClientWithResponses) GetMessageStatusWithResponse(ctx context.Context, messageId string, params *GetMessageStatusParams, reqEditors ...RequestEditorFn) (*GetMessageStatusResponse, error) {
	rsp, err := c.GetMessageStatus(ctx, messageId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetMessageStatusResponse(rsp)
}

// ParseResolveEmailAuthorizationResponse parses an HTTP response from a ResolveEmailAuthorizationWithResponse call
func ParseResolveEmailAuthorizationResponse(rsp *http.Response) (*ResolveEmailAuthorizationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ResolveEmailAuthorizationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AuthorizationDecision
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Health
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseExecuteMailboxOperationResponse parses an HTTP response from a ExecuteMailboxOperationWithResponse call
func ParseExecuteMailboxOperationResponse(rsp *http.Response) (*ExecuteMailboxOperationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExecuteMailboxOperationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Result
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseSendMessageResponse parses an HTTP response from a SendMessageWithResponse call
func ParseSendMessageResponse(rsp *http.Response) (*SendMessageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SendMessageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest MessageStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	}

	return response, nil
}

// ParseReconcileMessageResponse parses an HTTP response from a ReconcileMessageWithResponse call
func ParseReconcileMessageResponse(rsp *http.Response) (*ReconcileMessageResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ReconcileMessageResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MessageStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetMessageStatusResponse parses an HTTP response from a GetMessageStatusWithResponse call
func ParseGetMessageStatusResponse(rsp *http.Response) (*GetMessageStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetMessageStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MessageStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
