#!/usr/bin/env sh
set -eu

generated_dir=services/external/control-api-gateway/internal/transport/websocket/generated
typescript_generated_dir=services/staff/control-center/src/shared/api/generated/asyncapi

for generated_file in "$generated_dir"/*.go "$typescript_generated_dir"/*.ts; do
  if [ "$(sed -n '1p' "$generated_file")" != '// Code generated by generate-asyncapi.mjs. DO NOT EDIT.' ]; then
    echo "AsyncAPI model is missing the generated-file marker: $generated_file" >&2
    exit 1
  fi
done

if find "$generated_dir" -maxdepth 1 -type f -iname 'anonymous_schema_*.go' | grep -q .; then
  echo "anonymous AsyncAPI model file is forbidden" >&2
  exit 1
fi
if rg -q 'AnonymousSchema' "$generated_dir"; then
  echo "anonymous AsyncAPI model symbol is forbidden" >&2
  exit 1
fi
if rg -q 'func \([^)]*\) (UnmarshalJSON|MarshalJSON)\(' "$generated_dir"; then
  echo "generated AsyncAPI JSON codec is forbidden; use the strict runtime boundary" >&2
  exit 1
fi
for required in \
  resume_envelope.go snapshot_envelope.go event_envelope.go \
  resync_envelope.go heartbeat_envelope.go problem_envelope.go \
  run_graph.go run_node.go run_node_type.go run_node_state.go \
  run_edge.go run_edge_type.go run_event.go run_event_type.go run_state.go \
  next_action.go resync_reason.go problem_code.go; do
  if [ ! -f "$generated_dir/$required" ]; then
    echo "named AsyncAPI model is missing: $required" >&2
    exit 1
  fi
done

if ! rg -q 'Type[[:space:]]+RunEventType[[:space:]]+`json:"type"`' "$generated_dir/run_event.go"; then
  echo "RunEvent.type lost its Go JSON wire mapping" >&2
  exit 1
fi
if rg -q 'ReservedType|reservedType' "$generated_dir" "$typescript_generated_dir"; then
  echo "RunEvent.type must not be renamed by a target-language generator" >&2
  exit 1
fi
if ! rg -q '^[[:space:]]+type: RunEventType;' "$typescript_generated_dir/RunEvent.ts"; then
  echo "RunEvent.type lost its TypeScript wire mapping" >&2
  exit 1
fi
if ! rg -q '^type RunStream interface \{' "$generated_dir/run_stream.go" ||
  ! rg -q '^[[:space:]]+isRunStream\(\)' "$generated_dir/run_stream.go"; then
  echo "RunStream must remain a closed Go union without embedded JSON fields" >&2
  exit 1
fi
