apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kodex-system
resources: [../../../base/artifact-retention]
labels:
  - pairs: {kodex.dev/environment: staging}
    includeSelectors: false
    includeTemplates: true
patches: null
