apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mattercodex-system
resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - poddisruptionbudget.yaml
  - networkpolicy.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
  - dashboard.yaml
configMapGenerator:
  - name: egress-gateway-policy
    files:
      - policy.json=policy.json
generatorOptions:
  disableNameSuffixHash: true
patches:
  - target:
      group: ""
      version: v1
      kind: ConfigMap
      name: egress-gateway-policy
    patch: |-
      - op: add
        path: /immutable
        value: true
