package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	contracts := flag.String("contracts", "../../../contracts/integrations/v1/definitions", "каталог shipped definitions")
	output := flag.String("output", "shipped_gen.go", "generated Go file")
	flag.Parse()
	entries, err := filepath.Glob(filepath.Join(*contracts, "*.yaml"))
	if err != nil || len(entries) == 0 {
		fatal("discover shipped integration definitions", err)
	}
	sort.Strings(entries)
	var source strings.Builder
	source.WriteString("// Code generated by packagegen; DO NOT EDIT.\n\npackage integrationpackage\n\nvar shippedYAML = map[string]string{\n")
	for _, path := range entries {
		raw, readErr := os.ReadFile(path)
		if readErr != nil {
			fatal("read shipped integration definition", readErr)
		}
		source.WriteString("\t" + strconv.Quote(filepath.Base(path)) + ": " + strconv.Quote(string(raw)) + ",\n")
	}
	source.WriteString("}\n")
	if err := os.WriteFile(*output, []byte(source.String()), 0o644); err != nil {
		fatal("write generated shipped integration definitions", err)
	}
}

func fatal(message string, err error) {
	if err == nil {
		err = fmt.Errorf("no input files")
	}
	_, _ = fmt.Fprintf(os.Stderr, "%s: %v\n", message, err)
	os.Exit(1)
}
