apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: automation-scheduler
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: automation-scheduler
      app.kubernetes.io/component: scheduler-job
