apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: automation-scheduler
  labels:
    app.kubernetes.io/name: automation-scheduler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: automation-scheduler
      app.kubernetes.io/component: scheduler-job
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 5s
    - port: authority-metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 5s
