apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - serviceaccounts.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - issuer-networkpolicy.yaml
  - monitoring.yaml
  - poddisruptionbudget.yaml
components:
  - ../../components/internal-rpc-authority-session-archive-issuer
transformers:
  - controller-namespace-transformer.yaml
