apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - foundation.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: mattercodex
      mattercodex.dev/environment: direct-production
    includeSelectors: false
    includeTemplates: true
