\set ON_ERROR_STOP on

CREATE ROLE control_plane_owner
    NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT
    NOREPLICATION NOBYPASSRLS;
CREATE ROLE control_plane_runtime
    NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT
    NOREPLICATION NOBYPASSRLS;
CREATE ROLE control_plane_migrator
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT
    NOREPLICATION NOBYPASSRLS;
CREATE ROLE control_plane_runtime_g1
    LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT
    NOREPLICATION NOBYPASSRLS;
GRANT control_plane_owner TO control_plane_migrator
    WITH INHERIT FALSE, SET TRUE, ADMIN FALSE;
GRANT control_plane_runtime TO control_plane_runtime_g1
    WITH INHERIT TRUE, SET TRUE, ADMIN FALSE;
CREATE DATABASE control_plane OWNER control_plane_owner;

CREATE ROLE internal_rpc_authority_owner
    NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT
    NOREPLICATION NOBYPASSRLS;
CREATE ROLE internal_rpc_authority_migrator
    LOGIN NOSUPERUSER NOCREATEDB CREATEROLE NOINHERIT
    NOREPLICATION NOBYPASSRLS;
CREATE ROLE internal_rpc_authority_readback_owner
    NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT
    NOREPLICATION NOBYPASSRLS;
GRANT internal_rpc_authority_owner TO internal_rpc_authority_migrator
    WITH INHERIT FALSE, SET TRUE, ADMIN TRUE;
GRANT pg_signal_backend TO internal_rpc_authority_migrator
    WITH INHERIT FALSE, SET TRUE, ADMIN TRUE;
GRANT internal_rpc_authority_readback_owner
    TO internal_rpc_authority_migrator
    WITH INHERIT FALSE, SET TRUE, ADMIN TRUE;
CREATE DATABASE internal_rpc_authority OWNER internal_rpc_authority_owner;

REVOKE CONNECT ON DATABASE control_plane FROM PUBLIC;
REVOKE CONNECT ON DATABASE internal_rpc_authority FROM PUBLIC;
GRANT CONNECT, TEMPORARY ON DATABASE control_plane
    TO control_plane_migrator, control_plane_runtime_g1;
GRANT CONNECT, CREATE, TEMPORARY ON DATABASE internal_rpc_authority
    TO internal_rpc_authority_migrator;

\connect control_plane
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA public
    TO control_plane_owner, control_plane_migrator;
CREATE TABLE public.goose_db_version (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp NOT NULL DEFAULT now()
);
ALTER TABLE public.goose_db_version OWNER TO control_plane_owner;
ALTER SEQUENCE public.goose_db_version_id_seq OWNER TO control_plane_owner;
INSERT INTO public.goose_db_version (version_id, is_applied) VALUES (0, true);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.goose_db_version
    TO control_plane_migrator;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.goose_db_version_id_seq
    TO control_plane_migrator;

\connect internal_rpc_authority
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA public
    TO internal_rpc_authority_owner, internal_rpc_authority_migrator;
CREATE TABLE public.goose_db_version (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp NOT NULL DEFAULT now()
);
ALTER TABLE public.goose_db_version OWNER TO internal_rpc_authority_owner;
ALTER SEQUENCE public.goose_db_version_id_seq
    OWNER TO internal_rpc_authority_owner;
INSERT INTO public.goose_db_version (version_id, is_applied) VALUES (0, true);
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.goose_db_version
    TO internal_rpc_authority_migrator;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.goose_db_version_id_seq
    TO internal_rpc_authority_migrator;
