apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kodex-system
resources:
  - configmap.yaml
  - deployment.yaml
  - serviceaccount.yaml
  - service.yaml
  - poddisruptionbudget.yaml
  - servicemonitor.yaml
  - networkpolicy.yaml
  - dependency-ingress.yaml
  - key-delivery-rbac.yaml
  - certificate.yaml
  - prometheusrule.yaml
components:
  - ../../components/internal-rpc-authority-stt-tts-service-issuer
  - ../../components/internal-rpc-authority-stt-tts-service-verifier
patches: null
