apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: stt-tts-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: stt-tts-service
      app.kubernetes.io/component: internal-service
