apiVersion: v1
kind: Service
metadata:
  name: stt-tts-service
  labels:
    app.kubernetes.io/name: stt-tts-service
    app.kubernetes.io/component: internal-service
spec:
  selector:
    app.kubernetes.io/name: stt-tts-service
    app.kubernetes.io/component: internal-service
  ports:
    - {name: grpc, port: 8443, targetPort: grpc, protocol: TCP}
    - {name: metrics, port: 9090, targetPort: metrics, protocol: TCP}
