apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kodex-system
resources:
  - serviceaccount.yaml
  - postgresql-ca.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - servicemonitor.yaml
  - prometheusrule.yaml
