#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PROJECT_ROOT="$(cd "${ROOT_DIR}/.." && pwd)"
CONFIG_FILE="${KODEX_BOOTSTRAP_CONFIG_FILE:-${ROOT_DIR}/host/config.env}"

log() { echo "[$(date -Is)] $*"; }
die() { echo "ERROR: $*" >&2; exit 1; }

escape_squote() {
  printf "%s" "$1" | sed "s/'/'\\''/g"
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "Missing required command: $1"
}

is_ipv4() {
  [[ "$1" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]
}

resolve_ipv4() {
  local host="$1"
  getent ahostsv4 "$host" | awk '{print $1}' | sort -u
}

wait_for_dns_match() {
  local domain="$1"
  local target="$2"
  local timeout_s="$3"
  local interval_s="$4"
  local domain_ips=""
  local target_ips=""
  local deadline=$((SECONDS + timeout_s))

  if is_ipv4 "$target"; then
    target_ips="$target"
  else
    target_ips="$(resolve_ipv4 "$target" || true)"
  fi
  [ -n "$target_ips" ] || die "Unable to resolve target host IPv4: $target"

  while [ "$SECONDS" -lt "$deadline" ]; do
    domain_ips="$(resolve_ipv4 "$domain" || true)"
    if [ -n "$domain_ips" ] && grep -Fxf <(printf '%s\n' "$domain_ips") <(printf '%s\n' "$target_ips") >/dev/null; then
      log "DNS check passed: ${domain} -> $(printf '%s' "$domain_ips" | paste -sd ',' -)"
      return 0
    fi
    log "Waiting DNS: ${domain} should resolve to target host ${target} (timeout in $((deadline - SECONDS))s)"
    sleep "$interval_s"
  done

  die "DNS check failed: ${domain} does not resolve to target host ${target}. Domain IPs='${domain_ips:-<empty>}' Target IPs='${target_ips}'"
}

prompt_if_empty() {
  local var_name="$1"
  local prompt_text="$2"
  local secret="${3:-false}"
  if [ -z "${!var_name:-}" ]; then
    if [ "$secret" = "true" ]; then
      read -r -s -p "$prompt_text: " "$var_name"
      echo
    else
      read -r -p "$prompt_text: " "$var_name"
    fi
  fi
}

require_cmd ssh
require_cmd scp
require_cmd sed
require_cmd getent
require_cmd awk
require_cmd paste
require_cmd sort
require_cmd tar

if [ -f "$CONFIG_FILE" ]; then
  # shellcheck disable=SC1090
  source "$CONFIG_FILE"
fi

TARGET_PORT="${TARGET_PORT:-22}"
TARGET_ROOT_USER="${TARGET_ROOT_USER:-root}"
TARGET_ROOT_SSH_KEY="${TARGET_ROOT_SSH_KEY:-${HOME}/.ssh/id_rsa}"
OPERATOR_USER="${OPERATOR_USER:-codex}"
OPERATOR_SSH_PUBKEY_PATH="${OPERATOR_SSH_PUBKEY_PATH:-${HOME}/.ssh/id_rsa.pub}"
KODEX_PRODUCTION_NAMESPACE="${KODEX_PRODUCTION_NAMESPACE:-kodex-prod}"

prompt_if_empty TARGET_HOST "Target host (IPv4/FQDN)"
prompt_if_empty KODEX_GITHUB_REPO "Platform GitHub repo (owner/name)"
prompt_if_empty KODEX_GITHUB_PAT "GitHub fine-grained token" true
prompt_if_empty KODEX_GIT_BOT_TOKEN "KODEX_GIT_BOT_TOKEN (required)" true
prompt_if_empty KODEX_GIT_BOT_USERNAME "KODEX_GIT_BOT_USERNAME"
prompt_if_empty KODEX_GIT_BOT_MAIL "KODEX_GIT_BOT_MAIL"
prompt_if_empty KODEX_OPENAI_API_KEY "KODEX_OPENAI_API_KEY (optional; leave empty to use Codex device auth)" true
prompt_if_empty KODEX_BOOTSTRAP_OWNER_EMAIL "KODEX_BOOTSTRAP_OWNER_EMAIL (required)"
prompt_if_empty KODEX_GITHUB_OAUTH_CLIENT_ID "KODEX_GITHUB_OAUTH_CLIENT_ID (required)"
prompt_if_empty KODEX_GITHUB_OAUTH_CLIENT_SECRET "KODEX_GITHUB_OAUTH_CLIENT_SECRET (required)" true
prompt_if_empty KODEX_PRODUCTION_DOMAIN "Production domain (required)"
KODEX_AI_DOMAIN="${KODEX_AI_DOMAIN:-ai.${KODEX_PRODUCTION_DOMAIN}}"
prompt_if_empty KODEX_AI_DOMAIN "AI domain (required)"
prompt_if_empty KODEX_LETSENCRYPT_EMAIL "Let's Encrypt contact email (required)"

KODEX_FIRST_PROJECT_GITHUB_REPO="${KODEX_FIRST_PROJECT_GITHUB_REPO:-$KODEX_GITHUB_REPO}"
KODEX_GITHUB_WEBHOOK_URL="${KODEX_GITHUB_WEBHOOK_URL:-https://${KODEX_PRODUCTION_DOMAIN}/api/v1/webhooks/github}"
KODEX_GITHUB_WEBHOOK_EVENTS="${KODEX_GITHUB_WEBHOOK_EVENTS:-push,pull_request,issues,issue_comment,pull_request_review,pull_request_review_comment}"
KODEX_BOOTSTRAP_ALLOWED_EMAILS="${KODEX_BOOTSTRAP_ALLOWED_EMAILS:-}"
KODEX_BOOTSTRAP_PLATFORM_ADMIN_EMAILS="${KODEX_BOOTSTRAP_PLATFORM_ADMIN_EMAILS:-}"
KODEX_GIT_BOT_USERNAME="${KODEX_GIT_BOT_USERNAME:-codex-bot}"
KODEX_GIT_BOT_MAIL="${KODEX_GIT_BOT_MAIL:-codex-bot@kodex.local}"
KODEX_PROJECT_DB_ADMIN_HOST="${KODEX_PROJECT_DB_ADMIN_HOST:-postgres}"
KODEX_PROJECT_DB_ADMIN_PORT="${KODEX_PROJECT_DB_ADMIN_PORT:-5432}"
KODEX_PROJECT_DB_ADMIN_USER="${KODEX_PROJECT_DB_ADMIN_USER:-}"
KODEX_PROJECT_DB_ADMIN_PASSWORD="${KODEX_PROJECT_DB_ADMIN_PASSWORD:-}"
KODEX_PROJECT_DB_ADMIN_SSLMODE="${KODEX_PROJECT_DB_ADMIN_SSLMODE:-disable}"
KODEX_PROJECT_DB_ADMIN_DATABASE="${KODEX_PROJECT_DB_ADMIN_DATABASE:-postgres}"
KODEX_PROJECT_DB_LIFECYCLE_ALLOWED_ENVS="${KODEX_PROJECT_DB_LIFECYCLE_ALLOWED_ENVS:-dev,production,prod}"
KODEX_OPENAI_API_KEY="${KODEX_OPENAI_API_KEY:-}"
KODEX_RUN_INTAKE_LABEL="${KODEX_RUN_INTAKE_LABEL:-run:intake}"
KODEX_RUN_INTAKE_REVISE_LABEL="${KODEX_RUN_INTAKE_REVISE_LABEL:-run:intake:revise}"
KODEX_RUN_VISION_LABEL="${KODEX_RUN_VISION_LABEL:-run:vision}"
KODEX_RUN_VISION_REVISE_LABEL="${KODEX_RUN_VISION_REVISE_LABEL:-run:vision:revise}"
KODEX_RUN_PRD_LABEL="${KODEX_RUN_PRD_LABEL:-run:prd}"
KODEX_RUN_PRD_REVISE_LABEL="${KODEX_RUN_PRD_REVISE_LABEL:-run:prd:revise}"
KODEX_RUN_ARCH_LABEL="${KODEX_RUN_ARCH_LABEL:-run:arch}"
KODEX_RUN_ARCH_REVISE_LABEL="${KODEX_RUN_ARCH_REVISE_LABEL:-run:arch:revise}"
KODEX_RUN_DESIGN_LABEL="${KODEX_RUN_DESIGN_LABEL:-run:design}"
KODEX_RUN_DESIGN_REVISE_LABEL="${KODEX_RUN_DESIGN_REVISE_LABEL:-run:design:revise}"
KODEX_RUN_PLAN_LABEL="${KODEX_RUN_PLAN_LABEL:-run:plan}"
KODEX_RUN_PLAN_REVISE_LABEL="${KODEX_RUN_PLAN_REVISE_LABEL:-run:plan:revise}"
KODEX_RUN_DEV_LABEL="${KODEX_RUN_DEV_LABEL:-run:dev}"
KODEX_RUN_DEV_REVISE_LABEL="${KODEX_RUN_DEV_REVISE_LABEL:-run:dev:revise}"
KODEX_RUN_DEBUG_LABEL="${KODEX_RUN_DEBUG_LABEL:-run:debug}"
KODEX_RUN_DOC_AUDIT_LABEL="${KODEX_RUN_DOC_AUDIT_LABEL:-run:doc-audit}"
KODEX_RUN_QA_LABEL="${KODEX_RUN_QA_LABEL:-run:qa}"
KODEX_RUN_RELEASE_LABEL="${KODEX_RUN_RELEASE_LABEL:-run:release}"
KODEX_RUN_POSTDEPLOY_LABEL="${KODEX_RUN_POSTDEPLOY_LABEL:-run:postdeploy}"
KODEX_RUN_OPS_LABEL="${KODEX_RUN_OPS_LABEL:-run:ops}"
KODEX_RUN_SELF_IMPROVE_LABEL="${KODEX_RUN_SELF_IMPROVE_LABEL:-run:self-improve}"
KODEX_RUN_RETHINK_LABEL="${KODEX_RUN_RETHINK_LABEL:-run:rethink}"
KODEX_MODE_DISCUSSION_LABEL="${KODEX_MODE_DISCUSSION_LABEL:-mode:discussion}"
KODEX_STATE_BLOCKED_LABEL="${KODEX_STATE_BLOCKED_LABEL:-state:blocked}"
KODEX_STATE_IN_REVIEW_LABEL="${KODEX_STATE_IN_REVIEW_LABEL:-state:in-review}"
KODEX_STATE_APPROVED_LABEL="${KODEX_STATE_APPROVED_LABEL:-state:approved}"
KODEX_STATE_SUPERSEDED_LABEL="${KODEX_STATE_SUPERSEDED_LABEL:-state:superseded}"
KODEX_STATE_ABANDONED_LABEL="${KODEX_STATE_ABANDONED_LABEL:-state:abandoned}"
KODEX_NEED_INPUT_LABEL="${KODEX_NEED_INPUT_LABEL:-need:input}"
KODEX_NEED_PM_LABEL="${KODEX_NEED_PM_LABEL:-need:pm}"
KODEX_NEED_SA_LABEL="${KODEX_NEED_SA_LABEL:-need:sa}"
KODEX_NEED_QA_LABEL="${KODEX_NEED_QA_LABEL:-need:qa}"
KODEX_NEED_SRE_LABEL="${KODEX_NEED_SRE_LABEL:-need:sre}"
KODEX_NEED_EM_LABEL="${KODEX_NEED_EM_LABEL:-need:em}"
KODEX_NEED_KM_LABEL="${KODEX_NEED_KM_LABEL:-need:km}"
KODEX_NEED_REVIEWER_LABEL="${KODEX_NEED_REVIEWER_LABEL:-need:reviewer}"
KODEX_AI_MODEL_GPT_5_4_LABEL="${KODEX_AI_MODEL_GPT_5_4_LABEL:-[ai-model-gpt-5.4]}"
KODEX_AI_MODEL_GPT_5_3_CODEX_LABEL="${KODEX_AI_MODEL_GPT_5_3_CODEX_LABEL:-[ai-model-gpt-5.3-codex]}"
KODEX_AI_MODEL_GPT_5_3_CODEX_SPARK_LABEL="${KODEX_AI_MODEL_GPT_5_3_CODEX_SPARK_LABEL:-[ai-model-gpt-5.3-codex-spark]}"
KODEX_AI_MODEL_GPT_5_2_CODEX_LABEL="${KODEX_AI_MODEL_GPT_5_2_CODEX_LABEL:-[ai-model-gpt-5.2-codex]}"
KODEX_AI_MODEL_GPT_5_1_CODEX_MAX_LABEL="${KODEX_AI_MODEL_GPT_5_1_CODEX_MAX_LABEL:-[ai-model-gpt-5.1-codex-max]}"
KODEX_AI_MODEL_GPT_5_2_LABEL="${KODEX_AI_MODEL_GPT_5_2_LABEL:-[ai-model-gpt-5.2]}"
KODEX_AI_MODEL_GPT_5_1_CODEX_MINI_LABEL="${KODEX_AI_MODEL_GPT_5_1_CODEX_MINI_LABEL:-[ai-model-gpt-5.1-codex-mini]}"
KODEX_AI_REASONING_LOW_LABEL="${KODEX_AI_REASONING_LOW_LABEL:-[ai-reasoning-low]}"
KODEX_AI_REASONING_MEDIUM_LABEL="${KODEX_AI_REASONING_MEDIUM_LABEL:-[ai-reasoning-medium]}"
KODEX_AI_REASONING_HIGH_LABEL="${KODEX_AI_REASONING_HIGH_LABEL:-[ai-reasoning-high]}"
KODEX_AI_REASONING_EXTRA_HIGH_LABEL="${KODEX_AI_REASONING_EXTRA_HIGH_LABEL:-[ai-reasoning-extra-high]}"
KODEX_INTERNAL_REGISTRY_SERVICE="${KODEX_INTERNAL_REGISTRY_SERVICE:-kodex-registry}"
KODEX_INTERNAL_REGISTRY_PORT="${KODEX_INTERNAL_REGISTRY_PORT:-5000}"
KODEX_INTERNAL_REGISTRY_STORAGE_SIZE="${KODEX_INTERNAL_REGISTRY_STORAGE_SIZE:-20Gi}"
KODEX_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY="${KODEX_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY:-kodex/api-gateway}"
KODEX_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY="${KODEX_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY:-kodex/control-plane}"
KODEX_WORKER_INTERNAL_IMAGE_REPOSITORY="${KODEX_WORKER_INTERNAL_IMAGE_REPOSITORY:-kodex/worker}"
KODEX_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY="${KODEX_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY:-kodex/agent-runner}"
KODEX_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY="${KODEX_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY:-kodex/web-console}"
KODEX_INTERNAL_REGISTRY_HOST="${KODEX_INTERNAL_REGISTRY_HOST:-127.0.0.1:${KODEX_INTERNAL_REGISTRY_PORT}}"
KODEX_INSTALL_LONGHORN="${KODEX_INSTALL_LONGHORN:-false}"
KODEX_PLATFORM_DEPLOYMENT_REPLICAS="${KODEX_PLATFORM_DEPLOYMENT_REPLICAS:-2}"
KODEX_WORKER_REPLICAS="${KODEX_WORKER_REPLICAS:-3}"
KODEX_WORKER_POLL_INTERVAL="${KODEX_WORKER_POLL_INTERVAL:-5s}"
KODEX_WORKER_CLAIM_LIMIT="${KODEX_WORKER_CLAIM_LIMIT:-10}"
KODEX_WORKER_RUNNING_CHECK_LIMIT="${KODEX_WORKER_RUNNING_CHECK_LIMIT:-200}"
KODEX_WORKER_SLOTS_PER_PROJECT="${KODEX_WORKER_SLOTS_PER_PROJECT:-2}"
KODEX_WORKER_SLOT_LEASE_TTL="${KODEX_WORKER_SLOT_LEASE_TTL:-10m}"
KODEX_INGRESS_HOST_NETWORK="${KODEX_INGRESS_HOST_NETWORK:-true}"
KODEX_FIREWALL_ENABLED="${KODEX_FIREWALL_ENABLED:-true}"
KODEX_NETWORK_POLICY_BASELINE="${KODEX_NETWORK_POLICY_BASELINE:-true}"
KODEX_PLATFORM_MCP_PORT="${KODEX_PLATFORM_MCP_PORT:-8081}"
KODEX_K8S_API_CIDR="${KODEX_K8S_API_CIDR:-}"
KODEX_K8S_API_PORT="${KODEX_K8S_API_PORT:-6443}"
KODEX_DNS_WAIT_TIMEOUT="${KODEX_DNS_WAIT_TIMEOUT:-900}"
KODEX_DNS_WAIT_INTERVAL="${KODEX_DNS_WAIT_INTERVAL:-10}"
KODEX_NODE_DISCOVERY_TIMEOUT="${KODEX_NODE_DISCOVERY_TIMEOUT:-300}"
KODEX_NODE_READY_TIMEOUT="${KODEX_NODE_READY_TIMEOUT:-1200s}"
KODEX_INGRESS_READY_TIMEOUT="${KODEX_INGRESS_READY_TIMEOUT:-1200s}"
KODEX_CERT_MANAGER_READY_TIMEOUT="${KODEX_CERT_MANAGER_READY_TIMEOUT:-1200s}"
KODEX_ROLLOUT_TIMEOUT="${KODEX_ROLLOUT_TIMEOUT:-1800s}"
KODEX_WAIT_ROLLOUT="${KODEX_WAIT_ROLLOUT:-true}"
KODEX_LETSENCRYPT_SERVER="${KODEX_LETSENCRYPT_SERVER:-https://acme-v02.api.letsencrypt.org/directory}"
KODEX_KANIKO_TIMEOUT="${KODEX_KANIKO_TIMEOUT:-1800s}"
KODEX_KANIKO_CACHE_ENABLED="${KODEX_KANIKO_CACHE_ENABLED:-false}"
KODEX_KANIKO_CACHE_REPO="${KODEX_KANIKO_CACHE_REPO:-${KODEX_INTERNAL_REGISTRY_HOST}/kodex/kaniko-cache}"
KODEX_KANIKO_CACHE_TTL="${KODEX_KANIKO_CACHE_TTL:-168h}"
KODEX_KANIKO_CACHE_COMPRESSED="${KODEX_KANIKO_CACHE_COMPRESSED:-false}"
KODEX_KANIKO_CACHE_COPY_LAYERS="${KODEX_KANIKO_CACHE_COPY_LAYERS:-true}"
KODEX_KANIKO_SNAPSHOT_MODE="${KODEX_KANIKO_SNAPSHOT_MODE:-redo}"
KODEX_KANIKO_SINGLE_SNAPSHOT="${KODEX_KANIKO_SINGLE_SNAPSHOT:-true}"
KODEX_KANIKO_USE_NEW_RUN="${KODEX_KANIKO_USE_NEW_RUN:-true}"
KODEX_KANIKO_VERBOSITY="${KODEX_KANIKO_VERBOSITY:-info}"
KODEX_KANIKO_CLEANUP="${KODEX_KANIKO_CLEANUP:-true}"
KODEX_KANIKO_CPU_REQUEST="${KODEX_KANIKO_CPU_REQUEST:-4}"
KODEX_KANIKO_MEMORY_REQUEST="${KODEX_KANIKO_MEMORY_REQUEST:-8Gi}"
KODEX_KANIKO_CPU_LIMIT="${KODEX_KANIKO_CPU_LIMIT:-16}"
KODEX_KANIKO_MEMORY_LIMIT="${KODEX_KANIKO_MEMORY_LIMIT:-32Gi}"
KODEX_KANIKO_MAX_PARALLEL="${KODEX_KANIKO_MAX_PARALLEL:-${KODEX_KANIKO_MATRIX_MAX_PARALLEL:-4}}"
KODEX_IMAGE_MIRROR_ENABLED="${KODEX_IMAGE_MIRROR_ENABLED:-true}"
KODEX_IMAGE_MIRROR_TOOL_IMAGE="${KODEX_IMAGE_MIRROR_TOOL_IMAGE:-gcr.io/go-containerregistry/crane:debug}"
KODEX_IMAGE_MIRROR_PLATFORM="${KODEX_IMAGE_MIRROR_PLATFORM:-linux/amd64}"
KODEX_REGISTRY_CLEANUP_KEEP_TAGS="${KODEX_REGISTRY_CLEANUP_KEEP_TAGS:-5}"
KODEX_KANIKO_CLONE_IMAGE="${KODEX_KANIKO_CLONE_IMAGE:-}"
KODEX_KANIKO_EXECUTOR_IMAGE="${KODEX_KANIKO_EXECUTOR_IMAGE:-}"
KODEX_BUSYBOX_IMAGE="${KODEX_BUSYBOX_IMAGE:-}"
KODEX_POSTGRES_IMAGE="${KODEX_POSTGRES_IMAGE:-}"
KODEX_OAUTH2_PROXY_IMAGE="${KODEX_OAUTH2_PROXY_IMAGE:-}"
KODEX_REGISTRY_IMAGE="${KODEX_REGISTRY_IMAGE:-}"
KODEX_CODEGEN_CHECK_IMAGE="${KODEX_CODEGEN_CHECK_IMAGE:-}"
TARGET_PORT="${TARGET_PORT:-22}"
TARGET_ROOT_USER="${TARGET_ROOT_USER:-root}"
KODEX_LEARNING_MODE_DEFAULT="${KODEX_LEARNING_MODE_DEFAULT:-true}"
KODEX_SSH_PORT="${KODEX_SSH_PORT:-$TARGET_PORT}"
KODEX_API_GATEWAY_IMAGE="${KODEX_API_GATEWAY_IMAGE:-${KODEX_INTERNAL_REGISTRY_HOST}/${KODEX_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY}:latest}"
KODEX_CONTROL_PLANE_IMAGE="${KODEX_CONTROL_PLANE_IMAGE:-${KODEX_INTERNAL_REGISTRY_HOST}/${KODEX_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY}:latest}"
KODEX_WORKER_IMAGE="${KODEX_WORKER_IMAGE:-${KODEX_INTERNAL_REGISTRY_HOST}/${KODEX_WORKER_INTERNAL_IMAGE_REPOSITORY}:latest}"
KODEX_AGENT_RUNNER_IMAGE="${KODEX_AGENT_RUNNER_IMAGE:-${KODEX_INTERNAL_REGISTRY_HOST}/${KODEX_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY}:latest}"
KODEX_WEB_CONSOLE_IMAGE="${KODEX_WEB_CONSOLE_IMAGE:-${KODEX_INTERNAL_REGISTRY_HOST}/${KODEX_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY}:latest}"
KODEX_WORKER_K8S_NAMESPACE="${KODEX_WORKER_K8S_NAMESPACE:-$KODEX_PRODUCTION_NAMESPACE}"
KODEX_WORKER_JOB_IMAGE="${KODEX_WORKER_JOB_IMAGE:-$KODEX_AGENT_RUNNER_IMAGE}"
KODEX_WORKER_JOB_COMMAND="${KODEX_WORKER_JOB_COMMAND:-/usr/local/bin/kodex-agent-runner}"
KODEX_WORKER_JOB_TTL_SECONDS="${KODEX_WORKER_JOB_TTL_SECONDS:-600}"
KODEX_WORKER_JOB_BACKOFF_LIMIT="${KODEX_WORKER_JOB_BACKOFF_LIMIT:-0}"
KODEX_WORKER_JOB_ACTIVE_DEADLINE_SECONDS="${KODEX_WORKER_JOB_ACTIVE_DEADLINE_SECONDS:-18000}"
KODEX_WORKER_RUN_NAMESPACE_PREFIX="${KODEX_WORKER_RUN_NAMESPACE_PREFIX:-codex-issue}"
KODEX_WORKER_RUN_NAMESPACE_CLEANUP="${KODEX_WORKER_RUN_NAMESPACE_CLEANUP:-true}"
KODEX_WORKER_RUN_SERVICE_ACCOUNT="${KODEX_WORKER_RUN_SERVICE_ACCOUNT:-codex-runner}"
KODEX_WORKER_RUN_ROLE_NAME="${KODEX_WORKER_RUN_ROLE_NAME:-codex-runner}"
KODEX_WORKER_RUN_ROLE_BINDING_NAME="${KODEX_WORKER_RUN_ROLE_BINDING_NAME:-codex-runner}"
KODEX_WORKER_RUN_RESOURCE_QUOTA_NAME="${KODEX_WORKER_RUN_RESOURCE_QUOTA_NAME:-codex-run-quota}"
KODEX_WORKER_RUN_LIMIT_RANGE_NAME="${KODEX_WORKER_RUN_LIMIT_RANGE_NAME:-codex-run-limits}"
KODEX_WORKER_RUN_CREDENTIALS_SECRET_NAME="${KODEX_WORKER_RUN_CREDENTIALS_SECRET_NAME:-codex-run-credentials}"
KODEX_WORKER_RUN_QUOTA_PODS="${KODEX_WORKER_RUN_QUOTA_PODS:-20}"
if [ -z "${KODEX_AGENT_DEFAULT_MODEL:-}" ]; then
  KODEX_AGENT_DEFAULT_MODEL="gpt-5.4"
fi
KODEX_AGENT_DEFAULT_REASONING_EFFORT="${KODEX_AGENT_DEFAULT_REASONING_EFFORT:-high}"
KODEX_AGENT_DEFAULT_LOCALE="${KODEX_AGENT_DEFAULT_LOCALE:-ru}"
KODEX_AGENT_BASE_BRANCH="${KODEX_AGENT_BASE_BRANCH:-main}"
KODEX_CONTROL_PLANE_GRPC_TARGET="${KODEX_CONTROL_PLANE_GRPC_TARGET:-kodex-control-plane.${KODEX_PRODUCTION_NAMESPACE}.svc.cluster.local:9090}"
KODEX_CONTROL_PLANE_MCP_BASE_URL="${KODEX_CONTROL_PLANE_MCP_BASE_URL:-http://kodex-control-plane.${KODEX_PRODUCTION_NAMESPACE}.svc.cluster.local:8081/mcp}"
KODEX_PUBLIC_BASE_URL="${KODEX_PUBLIC_BASE_URL:-}"
KODEX_JWT_TTL="${KODEX_JWT_TTL:-15m}"
KODEX_MCP_TOKEN_TTL="${KODEX_MCP_TOKEN_TTL:-24h}"
KODEX_RUN_HEAVY_FIELDS_RETENTION_DAYS="${KODEX_RUN_HEAVY_FIELDS_RETENTION_DAYS:-7}"
KODEX_RUN_AGENT_LOGS_RETENTION_DAYS="${KODEX_RUN_AGENT_LOGS_RETENTION_DAYS:-$KODEX_RUN_HEAVY_FIELDS_RETENTION_DAYS}"

[ -f "$TARGET_ROOT_SSH_KEY" ] || die "SSH private key not found: $TARGET_ROOT_SSH_KEY"
[ -f "$OPERATOR_SSH_PUBKEY_PATH" ] || die "Operator public key not found: $OPERATOR_SSH_PUBKEY_PATH"
OPERATOR_SSH_PUBKEY="$(cat "$OPERATOR_SSH_PUBKEY_PATH")"

[ -n "${KODEX_PRODUCTION_DOMAIN:-}" ] || die "KODEX_PRODUCTION_DOMAIN is required"
[ -n "${KODEX_LETSENCRYPT_EMAIL:-}" ] || die "KODEX_LETSENCRYPT_EMAIL is required"
[ -n "${KODEX_GIT_BOT_TOKEN:-}" ] || die "KODEX_GIT_BOT_TOKEN is required"
if [ -z "${KODEX_OPENAI_API_KEY:-}" ]; then
  log "NOTE: KODEX_OPENAI_API_KEY is empty. Agent runs will use Codex device auth on first use (see run logs)."
fi
case "$KODEX_DNS_WAIT_TIMEOUT" in
  ''|*[!0-9]*) die "KODEX_DNS_WAIT_TIMEOUT must be integer seconds";;
esac
case "$KODEX_DNS_WAIT_INTERVAL" in
  ''|*[!0-9]*) die "KODEX_DNS_WAIT_INTERVAL must be integer seconds";;
esac
wait_for_dns_match "$KODEX_PRODUCTION_DOMAIN" "$TARGET_HOST" "$KODEX_DNS_WAIT_TIMEOUT" "$KODEX_DNS_WAIT_INTERVAL"

if [ -z "$KODEX_PUBLIC_BASE_URL" ]; then
  KODEX_PUBLIC_BASE_URL="https://${KODEX_PRODUCTION_DOMAIN}"
fi

if [ -z "$KODEX_K8S_API_CIDR" ]; then
  if is_ipv4 "$TARGET_HOST"; then
    KODEX_K8S_API_CIDR="${TARGET_HOST}/32"
  else
    resolved_ip="$(resolve_ipv4 "$TARGET_HOST" | head -n1 || true)"
    [ -n "$resolved_ip" ] || die "Unable to resolve TARGET_HOST IPv4 for KODEX_K8S_API_CIDR: $TARGET_HOST"
    KODEX_K8S_API_CIDR="${resolved_ip}/32"
  fi
fi

KODEX_POSTGRES_DB="kodex"
KODEX_POSTGRES_USER="kodex"
KODEX_POSTGRES_PASSWORD="${KODEX_POSTGRES_PASSWORD:-}"
KODEX_APP_SECRET_KEY="${KODEX_APP_SECRET_KEY:-}"
KODEX_TOKEN_ENCRYPTION_KEY="${KODEX_TOKEN_ENCRYPTION_KEY:-}"
KODEX_MCP_TOKEN_SIGNING_KEY="${KODEX_MCP_TOKEN_SIGNING_KEY:-}"
KODEX_JWT_SIGNING_KEY="${KODEX_JWT_SIGNING_KEY:-}"
KODEX_GITHUB_WEBHOOK_SECRET="${KODEX_GITHUB_WEBHOOK_SECRET:-}"
KODEX_PROJECT_DB_ADMIN_HOST="${KODEX_PROJECT_DB_ADMIN_HOST:-postgres}"
KODEX_PROJECT_DB_ADMIN_PORT="${KODEX_PROJECT_DB_ADMIN_PORT:-5432}"
KODEX_PROJECT_DB_ADMIN_USER="${KODEX_PROJECT_DB_ADMIN_USER:-$KODEX_POSTGRES_USER}"
KODEX_PROJECT_DB_ADMIN_PASSWORD="${KODEX_PROJECT_DB_ADMIN_PASSWORD:-$KODEX_POSTGRES_PASSWORD}"
KODEX_PROJECT_DB_ADMIN_SSLMODE="${KODEX_PROJECT_DB_ADMIN_SSLMODE:-disable}"
KODEX_PROJECT_DB_ADMIN_DATABASE="${KODEX_PROJECT_DB_ADMIN_DATABASE:-postgres}"

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

REMOTE_DIR="/root/kodex-bootstrap"
REMOTE_ENV="${REMOTE_DIR}/bootstrap.env"
REMOTE_REPO_ARCHIVE="${REMOTE_DIR}/repo-src.tgz"
REPO_ARCHIVE="${TMP_DIR}/repo-src.tgz"

log "Pack local repository snapshot from ${PROJECT_ROOT}"
tar \
  --exclude='.git' \
  --exclude='services/staff/web-console/node_modules' \
  --exclude='services/staff/web-console/dist' \
  -czf "${REPO_ARCHIVE}" \
  -C "${PROJECT_ROOT}" \
  .

cat > "${TMP_DIR}/bootstrap.env" <<ENV
OPERATOR_USER='$(escape_squote "$OPERATOR_USER")'
OPERATOR_SSH_PUBKEY='$(escape_squote "$OPERATOR_SSH_PUBKEY")'
KODEX_GITHUB_REPO='$(escape_squote "$KODEX_GITHUB_REPO")'
KODEX_FIRST_PROJECT_GITHUB_REPO='$(escape_squote "$KODEX_FIRST_PROJECT_GITHUB_REPO")'
KODEX_GITHUB_PAT='$(escape_squote "$KODEX_GITHUB_PAT")'
KODEX_REMOTE_REPO_ARCHIVE='$(escape_squote "$REMOTE_REPO_ARCHIVE")'
KODEX_GIT_BOT_TOKEN='$(escape_squote "$KODEX_GIT_BOT_TOKEN")'
KODEX_GIT_BOT_USERNAME='$(escape_squote "$KODEX_GIT_BOT_USERNAME")'
KODEX_GIT_BOT_MAIL='$(escape_squote "$KODEX_GIT_BOT_MAIL")'
KODEX_OPENAI_API_KEY='$(escape_squote "$KODEX_OPENAI_API_KEY")'
KODEX_CONTEXT7_API_KEY='$(escape_squote "${KODEX_CONTEXT7_API_KEY:-}")'
KODEX_PUBLIC_BASE_URL='$(escape_squote "$KODEX_PUBLIC_BASE_URL")'
KODEX_BOOTSTRAP_OWNER_EMAIL='$(escape_squote "$KODEX_BOOTSTRAP_OWNER_EMAIL")'
KODEX_BOOTSTRAP_ALLOWED_EMAILS='$(escape_squote "${KODEX_BOOTSTRAP_ALLOWED_EMAILS:-}")'
KODEX_BOOTSTRAP_PLATFORM_ADMIN_EMAILS='$(escape_squote "${KODEX_BOOTSTRAP_PLATFORM_ADMIN_EMAILS:-}")'
KODEX_GITHUB_OAUTH_CLIENT_ID='$(escape_squote "$KODEX_GITHUB_OAUTH_CLIENT_ID")'
KODEX_GITHUB_OAUTH_CLIENT_SECRET='$(escape_squote "$KODEX_GITHUB_OAUTH_CLIENT_SECRET")'
KODEX_JWT_SIGNING_KEY='$(escape_squote "$KODEX_JWT_SIGNING_KEY")'
KODEX_JWT_TTL='$(escape_squote "$KODEX_JWT_TTL")'
KODEX_MCP_TOKEN_SIGNING_KEY='$(escape_squote "$KODEX_MCP_TOKEN_SIGNING_KEY")'
KODEX_MCP_TOKEN_TTL='$(escape_squote "$KODEX_MCP_TOKEN_TTL")'
KODEX_RUN_HEAVY_FIELDS_RETENTION_DAYS='$(escape_squote "$KODEX_RUN_HEAVY_FIELDS_RETENTION_DAYS")'
KODEX_RUN_AGENT_LOGS_RETENTION_DAYS='$(escape_squote "$KODEX_RUN_AGENT_LOGS_RETENTION_DAYS")'
KODEX_PRODUCTION_NAMESPACE='$(escape_squote "$KODEX_PRODUCTION_NAMESPACE")'
KODEX_PRODUCTION_DOMAIN='$(escape_squote "$KODEX_PRODUCTION_DOMAIN")'
KODEX_AI_DOMAIN='$(escape_squote "$KODEX_AI_DOMAIN")'
KODEX_LETSENCRYPT_EMAIL='$(escape_squote "$KODEX_LETSENCRYPT_EMAIL")'
KODEX_LETSENCRYPT_SERVER='$(escape_squote "$KODEX_LETSENCRYPT_SERVER")'
KODEX_API_GATEWAY_IMAGE='$(escape_squote "$KODEX_API_GATEWAY_IMAGE")'
KODEX_CONTROL_PLANE_IMAGE='$(escape_squote "$KODEX_CONTROL_PLANE_IMAGE")'
KODEX_WORKER_IMAGE='$(escape_squote "$KODEX_WORKER_IMAGE")'
KODEX_AGENT_RUNNER_IMAGE='$(escape_squote "$KODEX_AGENT_RUNNER_IMAGE")'
KODEX_WEB_CONSOLE_IMAGE='$(escape_squote "$KODEX_WEB_CONSOLE_IMAGE")'
KODEX_PLATFORM_DEPLOYMENT_REPLICAS='$(escape_squote "$KODEX_PLATFORM_DEPLOYMENT_REPLICAS")'
KODEX_GITHUB_WEBHOOK_URL='$(escape_squote "$KODEX_GITHUB_WEBHOOK_URL")'
KODEX_GITHUB_WEBHOOK_EVENTS='$(escape_squote "$KODEX_GITHUB_WEBHOOK_EVENTS")'
KODEX_RUN_INTAKE_LABEL='$(escape_squote "$KODEX_RUN_INTAKE_LABEL")'
KODEX_RUN_INTAKE_REVISE_LABEL='$(escape_squote "$KODEX_RUN_INTAKE_REVISE_LABEL")'
KODEX_RUN_VISION_LABEL='$(escape_squote "$KODEX_RUN_VISION_LABEL")'
KODEX_RUN_VISION_REVISE_LABEL='$(escape_squote "$KODEX_RUN_VISION_REVISE_LABEL")'
KODEX_RUN_PRD_LABEL='$(escape_squote "$KODEX_RUN_PRD_LABEL")'
KODEX_RUN_PRD_REVISE_LABEL='$(escape_squote "$KODEX_RUN_PRD_REVISE_LABEL")'
KODEX_RUN_ARCH_LABEL='$(escape_squote "$KODEX_RUN_ARCH_LABEL")'
KODEX_RUN_ARCH_REVISE_LABEL='$(escape_squote "$KODEX_RUN_ARCH_REVISE_LABEL")'
KODEX_RUN_DESIGN_LABEL='$(escape_squote "$KODEX_RUN_DESIGN_LABEL")'
KODEX_RUN_DESIGN_REVISE_LABEL='$(escape_squote "$KODEX_RUN_DESIGN_REVISE_LABEL")'
KODEX_RUN_PLAN_LABEL='$(escape_squote "$KODEX_RUN_PLAN_LABEL")'
KODEX_RUN_PLAN_REVISE_LABEL='$(escape_squote "$KODEX_RUN_PLAN_REVISE_LABEL")'
KODEX_RUN_DEV_LABEL='$(escape_squote "$KODEX_RUN_DEV_LABEL")'
KODEX_RUN_DEV_REVISE_LABEL='$(escape_squote "$KODEX_RUN_DEV_REVISE_LABEL")'
KODEX_RUN_DEBUG_LABEL='$(escape_squote "$KODEX_RUN_DEBUG_LABEL")'
KODEX_RUN_DOC_AUDIT_LABEL='$(escape_squote "$KODEX_RUN_DOC_AUDIT_LABEL")'
KODEX_RUN_QA_LABEL='$(escape_squote "$KODEX_RUN_QA_LABEL")'
KODEX_RUN_RELEASE_LABEL='$(escape_squote "$KODEX_RUN_RELEASE_LABEL")'
KODEX_RUN_POSTDEPLOY_LABEL='$(escape_squote "$KODEX_RUN_POSTDEPLOY_LABEL")'
KODEX_RUN_OPS_LABEL='$(escape_squote "$KODEX_RUN_OPS_LABEL")'
KODEX_RUN_SELF_IMPROVE_LABEL='$(escape_squote "$KODEX_RUN_SELF_IMPROVE_LABEL")'
KODEX_RUN_RETHINK_LABEL='$(escape_squote "$KODEX_RUN_RETHINK_LABEL")'
KODEX_MODE_DISCUSSION_LABEL='$(escape_squote "$KODEX_MODE_DISCUSSION_LABEL")'
KODEX_STATE_BLOCKED_LABEL='$(escape_squote "$KODEX_STATE_BLOCKED_LABEL")'
KODEX_STATE_IN_REVIEW_LABEL='$(escape_squote "$KODEX_STATE_IN_REVIEW_LABEL")'
KODEX_STATE_APPROVED_LABEL='$(escape_squote "$KODEX_STATE_APPROVED_LABEL")'
KODEX_STATE_SUPERSEDED_LABEL='$(escape_squote "$KODEX_STATE_SUPERSEDED_LABEL")'
KODEX_STATE_ABANDONED_LABEL='$(escape_squote "$KODEX_STATE_ABANDONED_LABEL")'
KODEX_NEED_INPUT_LABEL='$(escape_squote "$KODEX_NEED_INPUT_LABEL")'
KODEX_NEED_PM_LABEL='$(escape_squote "$KODEX_NEED_PM_LABEL")'
KODEX_NEED_SA_LABEL='$(escape_squote "$KODEX_NEED_SA_LABEL")'
KODEX_NEED_QA_LABEL='$(escape_squote "$KODEX_NEED_QA_LABEL")'
KODEX_NEED_SRE_LABEL='$(escape_squote "$KODEX_NEED_SRE_LABEL")'
KODEX_NEED_EM_LABEL='$(escape_squote "$KODEX_NEED_EM_LABEL")'
KODEX_NEED_KM_LABEL='$(escape_squote "$KODEX_NEED_KM_LABEL")'
KODEX_NEED_REVIEWER_LABEL='$(escape_squote "$KODEX_NEED_REVIEWER_LABEL")'
KODEX_AI_MODEL_GPT_5_4_LABEL='$(escape_squote "$KODEX_AI_MODEL_GPT_5_4_LABEL")'
KODEX_AI_MODEL_GPT_5_3_CODEX_LABEL='$(escape_squote "$KODEX_AI_MODEL_GPT_5_3_CODEX_LABEL")'
KODEX_AI_MODEL_GPT_5_3_CODEX_SPARK_LABEL='$(escape_squote "$KODEX_AI_MODEL_GPT_5_3_CODEX_SPARK_LABEL")'
KODEX_AI_MODEL_GPT_5_2_CODEX_LABEL='$(escape_squote "$KODEX_AI_MODEL_GPT_5_2_CODEX_LABEL")'
KODEX_AI_MODEL_GPT_5_1_CODEX_MAX_LABEL='$(escape_squote "$KODEX_AI_MODEL_GPT_5_1_CODEX_MAX_LABEL")'
KODEX_AI_MODEL_GPT_5_2_LABEL='$(escape_squote "$KODEX_AI_MODEL_GPT_5_2_LABEL")'
KODEX_AI_MODEL_GPT_5_1_CODEX_MINI_LABEL='$(escape_squote "$KODEX_AI_MODEL_GPT_5_1_CODEX_MINI_LABEL")'
KODEX_AI_REASONING_LOW_LABEL='$(escape_squote "$KODEX_AI_REASONING_LOW_LABEL")'
KODEX_AI_REASONING_MEDIUM_LABEL='$(escape_squote "$KODEX_AI_REASONING_MEDIUM_LABEL")'
KODEX_AI_REASONING_HIGH_LABEL='$(escape_squote "$KODEX_AI_REASONING_HIGH_LABEL")'
KODEX_AI_REASONING_EXTRA_HIGH_LABEL='$(escape_squote "$KODEX_AI_REASONING_EXTRA_HIGH_LABEL")'
KODEX_INTERNAL_REGISTRY_SERVICE='$(escape_squote "$KODEX_INTERNAL_REGISTRY_SERVICE")'
KODEX_INTERNAL_REGISTRY_PORT='$(escape_squote "$KODEX_INTERNAL_REGISTRY_PORT")'
KODEX_INTERNAL_REGISTRY_STORAGE_SIZE='$(escape_squote "$KODEX_INTERNAL_REGISTRY_STORAGE_SIZE")'
KODEX_INTERNAL_REGISTRY_HOST='$(escape_squote "$KODEX_INTERNAL_REGISTRY_HOST")'
KODEX_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY='$(escape_squote "$KODEX_API_GATEWAY_INTERNAL_IMAGE_REPOSITORY")'
KODEX_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY='$(escape_squote "$KODEX_CONTROL_PLANE_INTERNAL_IMAGE_REPOSITORY")'
KODEX_WORKER_INTERNAL_IMAGE_REPOSITORY='$(escape_squote "$KODEX_WORKER_INTERNAL_IMAGE_REPOSITORY")'
KODEX_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY='$(escape_squote "$KODEX_AGENT_RUNNER_INTERNAL_IMAGE_REPOSITORY")'
KODEX_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY='$(escape_squote "$KODEX_WEB_CONSOLE_INTERNAL_IMAGE_REPOSITORY")'
KODEX_INSTALL_LONGHORN='$(escape_squote "$KODEX_INSTALL_LONGHORN")'
KODEX_WORKER_REPLICAS='$(escape_squote "$KODEX_WORKER_REPLICAS")'
KODEX_WORKER_POLL_INTERVAL='$(escape_squote "$KODEX_WORKER_POLL_INTERVAL")'
KODEX_WORKER_CLAIM_LIMIT='$(escape_squote "$KODEX_WORKER_CLAIM_LIMIT")'
KODEX_WORKER_RUNNING_CHECK_LIMIT='$(escape_squote "$KODEX_WORKER_RUNNING_CHECK_LIMIT")'
KODEX_WORKER_SLOTS_PER_PROJECT='$(escape_squote "$KODEX_WORKER_SLOTS_PER_PROJECT")'
KODEX_WORKER_SLOT_LEASE_TTL='$(escape_squote "$KODEX_WORKER_SLOT_LEASE_TTL")'
KODEX_WORKER_K8S_NAMESPACE='$(escape_squote "$KODEX_WORKER_K8S_NAMESPACE")'
KODEX_WORKER_JOB_IMAGE='$(escape_squote "$KODEX_WORKER_JOB_IMAGE")'
KODEX_WORKER_JOB_COMMAND='$(escape_squote "$KODEX_WORKER_JOB_COMMAND")'
KODEX_WORKER_JOB_TTL_SECONDS='$(escape_squote "$KODEX_WORKER_JOB_TTL_SECONDS")'
KODEX_WORKER_JOB_BACKOFF_LIMIT='$(escape_squote "$KODEX_WORKER_JOB_BACKOFF_LIMIT")'
KODEX_WORKER_JOB_ACTIVE_DEADLINE_SECONDS='$(escape_squote "$KODEX_WORKER_JOB_ACTIVE_DEADLINE_SECONDS")'
KODEX_WORKER_RUN_NAMESPACE_PREFIX='$(escape_squote "$KODEX_WORKER_RUN_NAMESPACE_PREFIX")'
KODEX_WORKER_RUN_NAMESPACE_CLEANUP='$(escape_squote "$KODEX_WORKER_RUN_NAMESPACE_CLEANUP")'
KODEX_WORKER_RUN_SERVICE_ACCOUNT='$(escape_squote "$KODEX_WORKER_RUN_SERVICE_ACCOUNT")'
KODEX_WORKER_RUN_ROLE_NAME='$(escape_squote "$KODEX_WORKER_RUN_ROLE_NAME")'
KODEX_WORKER_RUN_ROLE_BINDING_NAME='$(escape_squote "$KODEX_WORKER_RUN_ROLE_BINDING_NAME")'
KODEX_WORKER_RUN_RESOURCE_QUOTA_NAME='$(escape_squote "$KODEX_WORKER_RUN_RESOURCE_QUOTA_NAME")'
KODEX_WORKER_RUN_LIMIT_RANGE_NAME='$(escape_squote "$KODEX_WORKER_RUN_LIMIT_RANGE_NAME")'
KODEX_WORKER_RUN_CREDENTIALS_SECRET_NAME='$(escape_squote "$KODEX_WORKER_RUN_CREDENTIALS_SECRET_NAME")'
KODEX_WORKER_RUN_QUOTA_PODS='$(escape_squote "$KODEX_WORKER_RUN_QUOTA_PODS")'
KODEX_AGENT_DEFAULT_MODEL='$(escape_squote "$KODEX_AGENT_DEFAULT_MODEL")'
KODEX_AGENT_DEFAULT_REASONING_EFFORT='$(escape_squote "$KODEX_AGENT_DEFAULT_REASONING_EFFORT")'
KODEX_AGENT_DEFAULT_LOCALE='$(escape_squote "$KODEX_AGENT_DEFAULT_LOCALE")'
KODEX_AGENT_BASE_BRANCH='$(escape_squote "$KODEX_AGENT_BASE_BRANCH")'
KODEX_CONTROL_PLANE_GRPC_TARGET='$(escape_squote "$KODEX_CONTROL_PLANE_GRPC_TARGET")'
KODEX_CONTROL_PLANE_MCP_BASE_URL='$(escape_squote "$KODEX_CONTROL_PLANE_MCP_BASE_URL")'
KODEX_KANIKO_CACHE_ENABLED='$(escape_squote "$KODEX_KANIKO_CACHE_ENABLED")'
KODEX_KANIKO_CACHE_REPO='$(escape_squote "$KODEX_KANIKO_CACHE_REPO")'
KODEX_KANIKO_CACHE_TTL='$(escape_squote "$KODEX_KANIKO_CACHE_TTL")'
KODEX_KANIKO_CACHE_COMPRESSED='$(escape_squote "$KODEX_KANIKO_CACHE_COMPRESSED")'
KODEX_KANIKO_CACHE_COPY_LAYERS='$(escape_squote "$KODEX_KANIKO_CACHE_COPY_LAYERS")'
KODEX_KANIKO_SNAPSHOT_MODE='$(escape_squote "$KODEX_KANIKO_SNAPSHOT_MODE")'
KODEX_KANIKO_SINGLE_SNAPSHOT='$(escape_squote "$KODEX_KANIKO_SINGLE_SNAPSHOT")'
KODEX_KANIKO_USE_NEW_RUN='$(escape_squote "$KODEX_KANIKO_USE_NEW_RUN")'
KODEX_KANIKO_VERBOSITY='$(escape_squote "$KODEX_KANIKO_VERBOSITY")'
KODEX_KANIKO_CLEANUP='$(escape_squote "$KODEX_KANIKO_CLEANUP")'
KODEX_KANIKO_CPU_REQUEST='$(escape_squote "$KODEX_KANIKO_CPU_REQUEST")'
KODEX_KANIKO_MEMORY_REQUEST='$(escape_squote "$KODEX_KANIKO_MEMORY_REQUEST")'
KODEX_KANIKO_CPU_LIMIT='$(escape_squote "$KODEX_KANIKO_CPU_LIMIT")'
KODEX_KANIKO_MEMORY_LIMIT='$(escape_squote "$KODEX_KANIKO_MEMORY_LIMIT")'
KODEX_KANIKO_MAX_PARALLEL='$(escape_squote "$KODEX_KANIKO_MAX_PARALLEL")'
KODEX_IMAGE_MIRROR_ENABLED='$(escape_squote "$KODEX_IMAGE_MIRROR_ENABLED")'
KODEX_IMAGE_MIRROR_TOOL_IMAGE='$(escape_squote "$KODEX_IMAGE_MIRROR_TOOL_IMAGE")'
KODEX_IMAGE_MIRROR_PLATFORM='$(escape_squote "$KODEX_IMAGE_MIRROR_PLATFORM")'
KODEX_REGISTRY_CLEANUP_KEEP_TAGS='$(escape_squote "$KODEX_REGISTRY_CLEANUP_KEEP_TAGS")'
KODEX_KANIKO_CLONE_IMAGE='$(escape_squote "$KODEX_KANIKO_CLONE_IMAGE")'
KODEX_KANIKO_EXECUTOR_IMAGE='$(escape_squote "$KODEX_KANIKO_EXECUTOR_IMAGE")'
KODEX_BUSYBOX_IMAGE='$(escape_squote "$KODEX_BUSYBOX_IMAGE")'
KODEX_POSTGRES_IMAGE='$(escape_squote "$KODEX_POSTGRES_IMAGE")'
KODEX_OAUTH2_PROXY_IMAGE='$(escape_squote "$KODEX_OAUTH2_PROXY_IMAGE")'
KODEX_REGISTRY_IMAGE='$(escape_squote "$KODEX_REGISTRY_IMAGE")'
KODEX_CODEGEN_CHECK_IMAGE='$(escape_squote "$KODEX_CODEGEN_CHECK_IMAGE")'
KODEX_RUN_DEV_LABEL='$(escape_squote "$KODEX_RUN_DEV_LABEL")'
KODEX_RUN_DEV_REVISE_LABEL='$(escape_squote "$KODEX_RUN_DEV_REVISE_LABEL")'
KODEX_RUN_DEBUG_LABEL='$(escape_squote "$KODEX_RUN_DEBUG_LABEL")'
KODEX_INGRESS_HOST_NETWORK='$(escape_squote "$KODEX_INGRESS_HOST_NETWORK")'
KODEX_FIREWALL_ENABLED='$(escape_squote "$KODEX_FIREWALL_ENABLED")'
KODEX_SSH_PORT='$(escape_squote "$KODEX_SSH_PORT")'
KODEX_NETWORK_POLICY_BASELINE='$(escape_squote "$KODEX_NETWORK_POLICY_BASELINE")'
KODEX_PLATFORM_MCP_PORT='$(escape_squote "$KODEX_PLATFORM_MCP_PORT")'
KODEX_K8S_API_CIDR='$(escape_squote "$KODEX_K8S_API_CIDR")'
KODEX_K8S_API_PORT='$(escape_squote "$KODEX_K8S_API_PORT")'
KODEX_DNS_WAIT_TIMEOUT='$(escape_squote "$KODEX_DNS_WAIT_TIMEOUT")'
KODEX_DNS_WAIT_INTERVAL='$(escape_squote "$KODEX_DNS_WAIT_INTERVAL")'
KODEX_NODE_DISCOVERY_TIMEOUT='$(escape_squote "$KODEX_NODE_DISCOVERY_TIMEOUT")'
KODEX_NODE_READY_TIMEOUT='$(escape_squote "$KODEX_NODE_READY_TIMEOUT")'
KODEX_INGRESS_READY_TIMEOUT='$(escape_squote "$KODEX_INGRESS_READY_TIMEOUT")'
KODEX_CERT_MANAGER_READY_TIMEOUT='$(escape_squote "$KODEX_CERT_MANAGER_READY_TIMEOUT")'
KODEX_ROLLOUT_TIMEOUT='$(escape_squote "$KODEX_ROLLOUT_TIMEOUT")'
KODEX_WAIT_ROLLOUT='$(escape_squote "$KODEX_WAIT_ROLLOUT")'
KODEX_KANIKO_TIMEOUT='$(escape_squote "$KODEX_KANIKO_TIMEOUT")'
KODEX_LEARNING_MODE_DEFAULT='$(escape_squote "$KODEX_LEARNING_MODE_DEFAULT")'
KODEX_POSTGRES_DB='$(escape_squote "$KODEX_POSTGRES_DB")'
KODEX_POSTGRES_USER='$(escape_squote "$KODEX_POSTGRES_USER")'
KODEX_POSTGRES_PASSWORD='$(escape_squote "$KODEX_POSTGRES_PASSWORD")'
KODEX_PROJECT_DB_ADMIN_HOST='$(escape_squote "$KODEX_PROJECT_DB_ADMIN_HOST")'
KODEX_PROJECT_DB_ADMIN_PORT='$(escape_squote "$KODEX_PROJECT_DB_ADMIN_PORT")'
KODEX_PROJECT_DB_ADMIN_USER='$(escape_squote "$KODEX_PROJECT_DB_ADMIN_USER")'
KODEX_PROJECT_DB_ADMIN_PASSWORD='$(escape_squote "$KODEX_PROJECT_DB_ADMIN_PASSWORD")'
KODEX_PROJECT_DB_ADMIN_SSLMODE='$(escape_squote "$KODEX_PROJECT_DB_ADMIN_SSLMODE")'
KODEX_PROJECT_DB_ADMIN_DATABASE='$(escape_squote "$KODEX_PROJECT_DB_ADMIN_DATABASE")'
KODEX_PROJECT_DB_LIFECYCLE_ALLOWED_ENVS='$(escape_squote "$KODEX_PROJECT_DB_LIFECYCLE_ALLOWED_ENVS")'
KODEX_APP_SECRET_KEY='$(escape_squote "$KODEX_APP_SECRET_KEY")'
KODEX_TOKEN_ENCRYPTION_KEY='$(escape_squote "$KODEX_TOKEN_ENCRYPTION_KEY")'
KODEX_GITHUB_WEBHOOK_SECRET='$(escape_squote "$KODEX_GITHUB_WEBHOOK_SECRET")'
ENV

log "Copy remote bootstrap scripts to ${TARGET_ROOT_USER}@${TARGET_HOST}:${REMOTE_DIR}"
ssh -i "$TARGET_ROOT_SSH_KEY" -p "$TARGET_PORT" "${TARGET_ROOT_USER}@${TARGET_HOST}" "mkdir -p '${REMOTE_DIR}'"
scp -i "$TARGET_ROOT_SSH_KEY" -P "$TARGET_PORT" -r "${ROOT_DIR}/remote" "${TARGET_ROOT_USER}@${TARGET_HOST}:${REMOTE_DIR}/"
scp -i "$TARGET_ROOT_SSH_KEY" -P "$TARGET_PORT" "${TMP_DIR}/bootstrap.env" "${TARGET_ROOT_USER}@${TARGET_HOST}:${REMOTE_ENV}"
scp -i "$TARGET_ROOT_SSH_KEY" -P "$TARGET_PORT" "${REPO_ARCHIVE}" "${TARGET_ROOT_USER}@${TARGET_HOST}:${REMOTE_REPO_ARCHIVE}"

log "Run remote bootstrap"
ssh -i "$TARGET_ROOT_SSH_KEY" -p "$TARGET_PORT" "${TARGET_ROOT_USER}@${TARGET_HOST}" \
  "bash '${REMOTE_DIR}/remote/bootstrap_production.sh' '${REMOTE_ENV}'"

log "Bootstrap completed"
log "Next: verify pods/ingress and webhook-triggered runtime deploy flow"
