apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: control-plane
          env:
            - name: CONTROL_PLANE_NATS_REPLICAS
              value: "3"
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: "2"
              memory: 1Gi
