apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mattercodex-system
resources:
  - ../../../base/control-plane
patches:
  - path: deployment-patch.yaml
  - path: poddisruptionbudget-patch.yaml
labels:
  - pairs:
      mattercodex.dev/environment: production
    includeSelectors: false
    includeTemplates: true
