apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: internal-rpc-authority-restore-role-trust
spec:
  provider: vault
  parameters:
    roleName: internal-rpc-authority-restore-controller
    audience: vault
    vaultAddress: https://vault.mattercodex-system.svc:8200
    vaultTLSServerName: vault.mattercodex-system.svc.cluster.local
    vaultSkipTLSVerify: "false"
    objects: |
      - objectName: "manifest-trust.jws"
        secretPath: "secret/data/internal-rpc-authority/restore/trust"
        secretKey: "manifest-trust.jws"
        filePermission: 288
      - objectName: "restore-role-trust.jws"
        secretPath: "secret/data/internal-rpc-authority/restore/trust"
        secretKey: "restore-role-trust.jws"
        filePermission: 288
