apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: role-image-builder-internal-rpc-authority-issuer
  labels:
    app.kubernetes.io/name: internal-rpc-authority
    app.kubernetes.io/component: issuer
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: role-image-builder
      mattercodex.dev/internal-rpc-authority-issuer: enabled
  podMetricsEndpoints:
    - port: authority-metrics
      path: /metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 5s
