-- name: provider_operation__insert :one
INSERT INTO provider_hub_operations (
    id,
    command_id,
    actor_id,
    external_account_id,
    provider_slug,
    operation_type,
    target_ref,
    status,
    result_ref,
    error_code,
    error_message,
    rate_limit_snapshot_id,
    started_at,
    finished_at,
    version,
    created_at,
    updated_at
) VALUES (
    @id,
    @command_id,
    @actor_id,
    @external_account_id,
    @provider_slug,
    @operation_type,
    @target_ref,
    @status,
    @result_ref,
    @error_code,
    @error_message,
    @rate_limit_snapshot_id,
    @started_at,
    @finished_at,
    @version,
    @created_at,
    @updated_at
)
ON CONFLICT (operation_type, command_id) WHERE command_id <> '' DO UPDATE SET
    updated_at = provider_hub_operations.updated_at
RETURNING
    id,
    command_id,
    actor_id,
    external_account_id,
    provider_slug,
    operation_type,
    target_ref,
    status,
    result_ref,
    error_code,
    error_message,
    rate_limit_snapshot_id,
    started_at,
    finished_at,
    version,
    created_at,
    updated_at;
