-- name: work_item_projection__upsert :one
INSERT INTO provider_hub_work_item_projections (
    id,
    provider_slug,
    provider_work_item_id,
    project_id,
    repository_id,
    repository_full_name,
    kind,
    number,
    url,
    title,
    state,
    work_item_type,
    labels_json,
    assignees_json,
    milestone,
    project_fields_json,
    watermark_status,
    watermark_json,
    body_digest,
    provider_updated_at,
    synced_at,
    drift_status,
    version,
    created_at,
    updated_at
) VALUES (
    @id,
    @provider_slug,
    @provider_work_item_id,
    @project_id,
    @repository_id,
    @repository_full_name,
    @kind,
    @number,
    @url,
    @title,
    @state,
    @work_item_type,
    @labels_json,
    @assignees_json,
    @milestone,
    @project_fields_json,
    @watermark_status,
    @watermark_json,
    @body_digest,
    @provider_updated_at,
    @synced_at,
    @drift_status,
    @version,
    @created_at,
    @updated_at
)
ON CONFLICT (provider_slug, provider_work_item_id) DO UPDATE SET
    project_id = COALESCE(EXCLUDED.project_id, provider_hub_work_item_projections.project_id),
    repository_id = COALESCE(EXCLUDED.repository_id, provider_hub_work_item_projections.repository_id),
    repository_full_name = EXCLUDED.repository_full_name,
    kind = EXCLUDED.kind,
    number = EXCLUDED.number,
    url = EXCLUDED.url,
    title = EXCLUDED.title,
    state = EXCLUDED.state,
    work_item_type = EXCLUDED.work_item_type,
    labels_json = EXCLUDED.labels_json,
    assignees_json = EXCLUDED.assignees_json,
    milestone = EXCLUDED.milestone,
    project_fields_json = EXCLUDED.project_fields_json,
    watermark_status = EXCLUDED.watermark_status,
    watermark_json = EXCLUDED.watermark_json,
    body_digest = EXCLUDED.body_digest,
    provider_updated_at = EXCLUDED.provider_updated_at,
    synced_at = EXCLUDED.synced_at,
    drift_status = EXCLUDED.drift_status,
    version = provider_hub_work_item_projections.version + 1,
    updated_at = EXCLUDED.updated_at
RETURNING
    id,
    provider_slug,
    provider_work_item_id,
    project_id,
    repository_id,
    repository_full_name,
    kind,
    number,
    url,
    title,
    state,
    work_item_type,
    labels_json,
    assignees_json,
    milestone,
    project_fields_json,
    watermark_status,
    watermark_json,
    body_digest,
    provider_updated_at,
    synced_at,
    drift_status,
    version,
    created_at,
    updated_at;
