// Code generated by cmd/asyncapi-event-contracts from specs/asyncapi/provider-hub.v1.yaml; DO NOT EDIT.

package provider

const SchemaVersion = 1

const (
	EventWebhookReceived              = "provider.webhook.received"
	EventWebhookNormalized            = "provider.webhook.normalized"
	EventWorkItemSynced               = "provider.work_item.synced"
	EventWorkItemDriftDetected        = "provider.work_item.drift_detected"
	EventCommentSynced                = "provider.comment.synced"
	EventRelationshipSynced           = "provider.relationship.synced"
	EventSyncCursorAdvanced           = "provider.sync_cursor.advanced"
	EventAccountRuntimeStateChanged   = "provider.account_runtime_state.changed"
	EventLimitSnapshotRecorded        = "provider.limit_snapshot.recorded"
	EventOperationCompleted           = "provider.operation.completed"
	EventOperationFailed              = "provider.operation.failed"
	EventRepositoryBootstrapRequired  = "provider.repository.bootstrap_required"
	EventRepositoryAdoptionRequired   = "provider.repository.adoption_required"
	EventRepositoryBootstrapCompleted = "provider.repository.bootstrap_completed"
	EventRepositoryAdoptionPRCreated  = "provider.repository.adoption_pr_created"
)

const (
	AggregateAccountRuntimeState = "account_runtime_state"
	AggregateComment             = "comment"
	AggregateLimitSnapshot       = "limit_snapshot"
	AggregateProviderEvent       = "provider_event"
	AggregateProviderOperation   = "provider_operation"
	AggregateRelationship        = "relationship"
	AggregateRepository          = "repository"
	AggregateSyncCursor          = "sync_cursor"
	AggregateWebhookEvent        = "webhook_event"
	AggregateWorkItem            = "work_item"
)

// Payload is the generated common payload envelope for domain events.
type Payload struct {
	AdoptionPRRef                 string `json:"adoption_pr_ref,omitempty"`
	BootstrapMode                 string `json:"bootstrap_mode,omitempty"`
	CommentProjectionID           string `json:"comment_projection_id,omitempty"`
	DeliveryID                    string `json:"delivery_id,omitempty"`
	DriftStatus                   string `json:"drift_status,omitempty"`
	ErrorCode                     string `json:"error_code,omitempty"`
	EventName                     string `json:"event_name,omitempty"`
	ExternalAccountID             string `json:"external_account_id,omitempty"`
	Kind                          string `json:"kind,omitempty"`
	LimitClass                    string `json:"limit_class,omitempty"`
	LimitSnapshotID               string `json:"limit_snapshot_id,omitempty"`
	Number                        int64  `json:"number,omitempty"`
	OperationType                 string `json:"operation_type,omitempty"`
	ProjectID                     string `json:"project_id,omitempty"`
	ProviderAccountRuntimeStateID string `json:"provider_account_runtime_state_id,omitempty"`
	ProviderCommentID             string `json:"provider_comment_id,omitempty"`
	ProviderEventID               string `json:"provider_event_id,omitempty"`
	ProviderOperationID           string `json:"provider_operation_id,omitempty"`
	ProviderRepositoryID          string `json:"provider_repository_id,omitempty"`
	ProviderSlug                  string `json:"provider_slug,omitempty"`
	ProviderWorkItemID            string `json:"provider_work_item_id,omitempty"`
	RelationshipID                string `json:"relationship_id,omitempty"`
	RelationshipType              string `json:"relationship_type,omitempty"`
	RepositoryFullName            string `json:"repository_full_name,omitempty"`
	RepositoryID                  string `json:"repository_id,omitempty"`
	ResultRef                     string `json:"result_ref,omitempty"`
	ReviewState                   string `json:"review_state,omitempty"`
	ScopeRef                      string `json:"scope_ref,omitempty"`
	ScopeType                     string `json:"scope_type,omitempty"`
	Source                        string `json:"source,omitempty"`
	Status                        string `json:"status,omitempty"`
	SyncCursorID                  string `json:"sync_cursor_id,omitempty"`
	Version                       int64  `json:"version,omitempty"`
	WatermarkStatus               string `json:"watermark_status,omitempty"`
	WebhookEventID                string `json:"webhook_event_id,omitempty"`
	WorkItemProjectionID          string `json:"work_item_projection_id,omitempty"`
}
