/** @type {import('@hey-api/openapi-ts').UserConfig} */
export default {
  input: "../../../contracts/openapi/control-api-gateway/v1/openapi.yaml",
  output: {
    clean: true,
    header: ["// This file is auto-generated by @hey-api/openapi-ts"],
    path: "src/shared/api/generated/openapi",
    tsConfigPath: "tsconfig.app.json",
  },
  plugins: ["@hey-api/typescript", "@hey-api/client-fetch", "@hey-api/sdk"],
};
