apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: internal-rpc-authority-control-plane-manifest-trust
spec:
  provider: vault
  parameters:
    roleName: internal-rpc-authority-control-plane
    audience: vault
    objects: |
      - objectName: "bundle.jws"
        secretPath: "kv/data/kodex/internal-rpc-authority/control-plane/verifier/manifest-trust"
        secretKey: "manifest-trust.jws"
        filePermission: 292
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: internal-rpc-authority-control-plane-resolver-key
spec:
  provider: vault
  parameters:
    roleName: internal-rpc-authority-control-plane
    audience: vault
    objects: |
      - objectName: "private.jwk"
        secretPath: "kv/data/kodex/internal-rpc-authority/control-plane/resolver/proof-private"
        secretKey: "private.jwk"
        filePermission: 292
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: internal-rpc-authority-control-plane-resolver-trust
spec:
  provider: vault
  parameters:
    roleName: internal-rpc-authority-control-plane
    audience: vault
    objects: |
      - objectName: "jwks.json"
        secretPath: "kv/data/kodex/internal-rpc-authority/control-plane/resolver/proof-trust"
        secretKey: "proof-trust.jwk"
        filePermission: 292
