server_name: kodex-nats
port: 4222
http_port: 8222
operator: __NATS_OPERATOR_JWT__
system_account: __NATS_SYSTEM_ACCOUNT__
resolver: MEMORY
resolver_preload: {
  __NATS_SYSTEM_ACCOUNT__: __NATS_SYSTEM_ACCOUNT_JWT__,
  __NATS_APPLICATION_ACCOUNT__: __NATS_APPLICATION_ACCOUNT_JWT__
}
tls {
  cert_file: "/var/run/tls/tls.crt"
  key_file: "/var/run/tls/tls.key"
  ca_file: "/var/run/tls/ca.crt"
  verify: true
  timeout: 2
}
jetstream {
  store_dir: "/data/jetstream"
  max_mem_store: 512Mi
  max_file_store: 32Gi
}
