-- name: RuntimeExecutionInsert :exec
INSERT INTO control_plane.runtime_executions (
    id, organization_id, project_id, process_id, session_id, thread_id,
    role_id, turn_id, attempt, runtime_revision_id,
    runtime_revision_version, runtime_revision_sha256,
    immutable_input_sha256, resource_class, cluster_access_profile,
    workload_id, workload_spiffe_id, grant_generation, version, fence,
    state, lease_id, lease_token_sha256, lease_expires_at,
    terminal_outcome, terminal_reference, terminal_sha256,
    archive_reference, archive_sha256, archive_object_key, archive_version_id,
    archive_kms_key_arn, archive_object_lock_mode, archive_provenance_sha256,
    restore_proof_reference,
    restore_proof_sha256, restore_verifier_workload_id,
    restore_verifier_spiffe_id, restore_verifier_generation,
    cleanup_authorization_id, cleanup_authorization_expires_at,
    cleanup_authorization_state, cleanup_authorization_generation,
    cleanup_consumed_at,
    cleanup_pvc_name, cleanup_pvc_uid, cleanup_pvc_resource_version,
    cleanup_claimed_at, cleanup_eligible_at, cleanup_not_found_at,
    cleanup_deletion_proof_sha256,
    restore_source_execution_id, restore_source_archive_reference,
    restore_source_archive_sha256, restore_source_runtime_revision_sha256,
    restore_source_immutable_input_sha256, restore_source_proof_sha256,
    restore_source_version, restore_source_archive_object_key,
    restore_source_archive_version_id, restore_source_archive_kms_key_arn,
    restore_source_archive_object_lock_mode, restore_source_archive_retain_until,
    restore_source_retention_policy_id, restore_source_retention_policy_version,
    restore_source_provenance_sha256,
    effective_runtime_sha256, agent_session_key, agent_session_id,
    agent_session_turn_id, agent_run_id, agent_binding_sha256,
    retention_policy_id, retention_policy_version, pvc_retention_seconds,
    archive_retention_seconds, archive_retain_until, pvc_cleanup_eligible_at,
    capacity_observation_expires_at, reschedule_after,
    restore_assignment_state, restore_assignment_generation,
    restore_target_pvc_name, restore_target_pvc_uid, restore_target_pvc_resource_version,
    rehydrate_proof_reference, rehydrate_proof_sha256,
    credential_snapshot_sha256, workload_ticket_sha256,
    provider_binding_id, provider_binding_version, provider_binding_sha256,
    codex_session_id, codex_archive_relative_path, codex_archive_sha256,
    codex_archive_provenance, codex_delivery_recovery_source_execution_id,
    materializations,
    created_at, updated_at
) VALUES (
    @id, @organization_id, @project_id, @process_id, @session_id, @thread_id,
    @role_id, @turn_id, @attempt, @runtime_revision_id,
    @runtime_revision_version, @runtime_revision_sha256,
    @immutable_input_sha256, @resource_class, @cluster_access_profile,
    @workload_id, @workload_spiffe_id, @grant_generation, @version, @fence,
    @state, nullif(@lease_id, '')::uuid, nullif(@lease_token_sha256, ''),
    nullif(@lease_expires_at, 'epoch'::timestamptz),
    nullif(@terminal_outcome, ''), nullif(@terminal_reference, ''),
    nullif(@terminal_sha256, ''), nullif(@archive_reference, ''),
    nullif(@archive_sha256, ''), nullif(@archive_object_key, ''),
    nullif(@archive_version_id, ''), nullif(@archive_kms_key_arn, ''),
    nullif(@archive_object_lock_mode, ''), nullif(@archive_provenance_sha256, ''),
    nullif(@restore_proof_reference, ''),
    nullif(@restore_proof_sha256, ''), nullif(@restore_verifier_workload_id, ''),
    nullif(@restore_verifier_spiffe_id, ''), nullif(@restore_verifier_generation, 0),
    nullif(@cleanup_authorization_id, '')::uuid,
    nullif(@cleanup_authorization_expires_at, 'epoch'::timestamptz),
    @cleanup_authorization_state, @cleanup_authorization_generation,
    nullif(@cleanup_consumed_at, 'epoch'::timestamptz),
    nullif(@cleanup_pvc_name, ''), nullif(@cleanup_pvc_uid, '')::uuid,
    nullif(@cleanup_pvc_resource_version, ''),
    nullif(@cleanup_claimed_at, 'epoch'::timestamptz),
    nullif(@cleanup_eligible_at, 'epoch'::timestamptz),
    nullif(@cleanup_not_found_at, 'epoch'::timestamptz),
    nullif(@cleanup_deletion_proof_sha256, ''),
    nullif(@restore_source_execution_id, '')::uuid,
    nullif(@restore_source_archive_reference, ''),
    nullif(@restore_source_archive_sha256, ''),
    nullif(@restore_source_runtime_revision_sha256, ''),
    nullif(@restore_source_immutable_input_sha256, ''),
    nullif(@restore_source_proof_sha256, ''),
    nullif(@restore_source_version, 0), nullif(@restore_source_archive_object_key, ''),
    nullif(@restore_source_archive_version_id, ''),
    nullif(@restore_source_archive_kms_key_arn, ''),
    nullif(@restore_source_archive_object_lock_mode, ''),
    nullif(@restore_source_archive_retain_until, 'epoch'::timestamptz),
    nullif(@restore_source_retention_policy_id, ''),
    nullif(@restore_source_retention_policy_version, 0),
    nullif(@restore_source_provenance_sha256, ''),
    @effective_runtime_sha256, @agent_session_key, @agent_session_id,
    @agent_session_turn_id, @agent_run_id, @agent_binding_sha256,
    @retention_policy_id, @retention_policy_version, @pvc_retention_seconds,
    @archive_retention_seconds, nullif(@archive_retain_until, 'epoch'::timestamptz), @pvc_cleanup_eligible_at,
    @capacity_observation_expires_at, @reschedule_after,
    @restore_assignment_state, @restore_assignment_generation,
    nullif(@restore_target_pvc_name, ''), nullif(@restore_target_pvc_uid, '')::uuid,
    nullif(@restore_target_pvc_resource_version, ''),
    nullif(@rehydrate_proof_reference, ''), nullif(@rehydrate_proof_sha256, ''),
    @credential_snapshot_sha256, @workload_ticket_sha256,
    @provider_binding_id, @provider_binding_version, @provider_binding_sha256,
    nullif(@codex_session_id, ''), nullif(@codex_archive_relative_path, ''),
    nullif(@codex_archive_sha256, ''), nullif(@codex_archive_provenance, ''),
    nullif(@codex_delivery_recovery_source_execution_id, '')::uuid, @materializations,
    @created_at, @updated_at
);
