SELECT id, organization_id, project_id, process_id, session_id, thread_id,
       role_id, turn_id, attempt, runtime_revision_id,
       runtime_revision_version, runtime_revision_sha256,
       immutable_input_sha256, resource_class, cluster_access_profile,
       workload_id, workload_spiffe_id, grant_generation, version, fence,
       state, coalesce(lease_id::text, ''), coalesce(lease_token_sha256, ''),
       coalesce(lease_expires_at, 'epoch'::timestamptz),
       coalesce(terminal_outcome, ''), coalesce(terminal_reference, ''),
       coalesce(terminal_sha256, ''), coalesce(archive_reference, ''),
       coalesce(archive_sha256, ''), coalesce(restore_proof_reference, ''),
       coalesce(restore_proof_sha256, ''),
       coalesce(restore_verifier_workload_id, ''),
       coalesce(restore_verifier_spiffe_id, ''),
       coalesce(restore_verifier_generation, 0),
       coalesce(cleanup_authorization_id::text, ''),
       coalesce(cleanup_authorization_expires_at, 'epoch'::timestamptz),
       cleanup_authorization_state, cleanup_authorization_generation,
       coalesce(cleanup_consumed_at, 'epoch'::timestamptz),
       coalesce(cleanup_pvc_name, ''), coalesce(cleanup_pvc_uid::text, ''),
       coalesce(cleanup_pvc_resource_version, ''),
       coalesce(cleanup_claimed_at, 'epoch'::timestamptz),
       coalesce(cleanup_eligible_at, 'epoch'::timestamptz),
       coalesce(cleanup_not_found_at, 'epoch'::timestamptz),
       coalesce(cleanup_deletion_proof_sha256, ''),
       coalesce(restore_source_execution_id::text, ''),
       coalesce(restore_source_archive_reference, ''),
       coalesce(restore_source_archive_sha256, ''),
       coalesce(restore_source_runtime_revision_sha256, ''),
       coalesce(restore_source_immutable_input_sha256, ''),
       coalesce(restore_source_proof_sha256, ''),
       created_at, updated_at
FROM control_plane.runtime_executions
WHERE turn_id = @turn_id AND attempt = @attempt
FOR UPDATE;
