-- name: RuntimeExecutionGetByTurn :one
SELECT id, organization_id, project_id, process_id, session_id, thread_id,
       role_id, turn_id, attempt, runtime_revision_id,
       runtime_revision_version, runtime_revision_sha256,
       immutable_input_sha256, resource_class, cluster_access_profile,
       workload_id, workload_spiffe_id, grant_generation, version, fence,
       state, coalesce(lease_id::text, ''), coalesce(lease_token_sha256, ''),
       coalesce(lease_expires_at, 'epoch'::timestamptz),
       coalesce(terminal_outcome, ''), coalesce(terminal_reference, ''),
       coalesce(terminal_sha256, ''), coalesce(archive_reference, ''),
       coalesce(archive_sha256, ''), coalesce(archive_object_key, ''),
       coalesce(archive_version_id, ''), coalesce(archive_kms_key_arn, ''),
       coalesce(archive_object_lock_mode, ''), coalesce(archive_provenance_sha256, ''),
       coalesce(restore_proof_reference, ''),
       coalesce(restore_proof_sha256, ''),
       coalesce(restore_verifier_workload_id, ''),
       coalesce(restore_verifier_spiffe_id, ''),
       coalesce(restore_verifier_generation, 0),
       coalesce(cleanup_authorization_id::text, ''),
       coalesce(cleanup_authorization_expires_at, 'epoch'::timestamptz),
       cleanup_authorization_state, cleanup_authorization_generation,
       coalesce(cleanup_consumed_at, 'epoch'::timestamptz),
       coalesce(cleanup_pvc_name, ''), coalesce(cleanup_pvc_uid::text, ''),
       coalesce(cleanup_pvc_resource_version, ''),
       coalesce(cleanup_claimed_at, 'epoch'::timestamptz),
       coalesce(cleanup_eligible_at, 'epoch'::timestamptz),
       coalesce(cleanup_not_found_at, 'epoch'::timestamptz),
       coalesce(cleanup_deletion_proof_sha256, ''),
       coalesce(restore_source_execution_id::text, ''),
       coalesce(restore_source_archive_reference, ''),
       coalesce(restore_source_archive_sha256, ''),
       coalesce(restore_source_runtime_revision_sha256, ''),
       coalesce(restore_source_immutable_input_sha256, ''),
       coalesce(restore_source_proof_sha256, ''),
       coalesce(restore_source_version, 0),
       coalesce(restore_source_archive_object_key, ''),
       coalesce(restore_source_archive_version_id, ''),
       coalesce(restore_source_archive_kms_key_arn, ''),
       coalesce(restore_source_archive_object_lock_mode, ''),
       coalesce(restore_source_archive_retain_until, 'epoch'::timestamptz),
       coalesce(restore_source_retention_policy_id, ''),
       coalesce(restore_source_retention_policy_version, 0),
       coalesce(restore_source_provenance_sha256, ''),
       effective_runtime_sha256, agent_session_key, agent_session_id,
       agent_session_turn_id, agent_run_id, agent_binding_sha256,
       retention_policy_id, retention_policy_version, pvc_retention_seconds,
       archive_retention_seconds, coalesce(archive_retain_until, 'epoch'::timestamptz), pvc_cleanup_eligible_at,
       capacity_observation_expires_at, reschedule_after,
       restore_assignment_state, restore_assignment_generation,
       coalesce(restore_target_pvc_name, ''), coalesce(restore_target_pvc_uid::text, ''),
       coalesce(restore_target_pvc_resource_version, ''),
       coalesce(rehydrate_proof_reference, ''), coalesce(rehydrate_proof_sha256, ''),
       credential_snapshot_sha256, workload_ticket_sha256,
       coalesce(provider_binding_id::text, ''), coalesce(provider_binding_version, 0),
       coalesce(provider_binding_sha256, ''), coalesce(codex_session_id, ''),
       coalesce(codex_archive_relative_path, ''), coalesce(codex_archive_sha256, ''),
       coalesce(codex_archive_provenance, ''),
       coalesce(codex_delivery_recovery_source_execution_id::text, ''), materializations,
       created_at, updated_at
FROM control_plane.runtime_executions
WHERE turn_id = @turn_id AND attempt = @attempt;
