INSERT INTO control_plane.runtime_executions (
    id, organization_id, project_id, process_id, session_id, thread_id,
    role_id, turn_id, attempt, runtime_revision_id,
    runtime_revision_version, runtime_revision_sha256,
    immutable_input_sha256, resource_class, cluster_access_profile,
    workload_id, workload_spiffe_id, grant_generation, version, fence,
    state, lease_id, lease_token_sha256, lease_expires_at,
    terminal_outcome, terminal_reference, terminal_sha256,
    archive_reference, archive_sha256, restore_proof_reference,
    restore_proof_sha256, restore_verifier_workload_id,
    restore_verifier_spiffe_id, restore_verifier_generation,
    cleanup_authorization_id, cleanup_authorization_expires_at,
    cleanup_authorization_state, cleanup_authorization_generation,
    cleanup_consumed_at,
    cleanup_pvc_name, cleanup_pvc_uid, cleanup_pvc_resource_version,
    cleanup_claimed_at, cleanup_eligible_at, cleanup_not_found_at,
    cleanup_deletion_proof_sha256,
    restore_source_execution_id, restore_source_archive_reference,
    restore_source_archive_sha256, restore_source_runtime_revision_sha256,
    restore_source_immutable_input_sha256, restore_source_proof_sha256,
    created_at, updated_at
) VALUES (
    @id, @organization_id, @project_id, @process_id, @session_id, @thread_id,
    @role_id, @turn_id, @attempt, @runtime_revision_id,
    @runtime_revision_version, @runtime_revision_sha256,
    @immutable_input_sha256, @resource_class, @cluster_access_profile,
    @workload_id, @workload_spiffe_id, @grant_generation, @version, @fence,
    @state, nullif(@lease_id, '')::uuid, nullif(@lease_token_sha256, ''),
    nullif(@lease_expires_at, 'epoch'::timestamptz),
    nullif(@terminal_outcome, ''), nullif(@terminal_reference, ''),
    nullif(@terminal_sha256, ''), nullif(@archive_reference, ''),
    nullif(@archive_sha256, ''), nullif(@restore_proof_reference, ''),
    nullif(@restore_proof_sha256, ''), nullif(@restore_verifier_workload_id, ''),
    nullif(@restore_verifier_spiffe_id, ''), nullif(@restore_verifier_generation, 0),
    nullif(@cleanup_authorization_id, '')::uuid,
    nullif(@cleanup_authorization_expires_at, 'epoch'::timestamptz),
    @cleanup_authorization_state, @cleanup_authorization_generation,
    nullif(@cleanup_consumed_at, 'epoch'::timestamptz),
    nullif(@cleanup_pvc_name, ''), nullif(@cleanup_pvc_uid, '')::uuid,
    nullif(@cleanup_pvc_resource_version, ''),
    nullif(@cleanup_claimed_at, 'epoch'::timestamptz),
    nullif(@cleanup_eligible_at, 'epoch'::timestamptz),
    nullif(@cleanup_not_found_at, 'epoch'::timestamptz),
    nullif(@cleanup_deletion_proof_sha256, ''),
    nullif(@restore_source_execution_id, '')::uuid,
    nullif(@restore_source_archive_reference, ''),
    nullif(@restore_source_archive_sha256, ''),
    nullif(@restore_source_runtime_revision_sha256, ''),
    nullif(@restore_source_immutable_input_sha256, ''),
    nullif(@restore_source_proof_sha256, ''),
    @created_at, @updated_at
);
