-- name: ScheduleOccurrenceSave
INSERT INTO control_plane.schedule_occurrences (
    id,
    schedule_id,
    organization_id,
    project_id,
    scheduled_for,
    target_resource_id,
    target_kind,
    target_version,
    effective_input_sha256,
    prompt_profile_id,
    prompt_revision,
    runtime_revision_id,
    session_policy,
    room_id,
    notification_policy,
    maximum_execution_duration_ms,
    coalesce,
    overlap_policy,
    maximum_attempts,
    initial_backoff_ms,
    maximum_backoff_ms,
    dead_letter_at,
    state,
    attempt,
    available_at,
    outcome,
    result_artifact_id,
    updated_at
) VALUES (
    @id::uuid,
    @schedule_id::uuid,
    @organization_id::uuid,
    @project_id::uuid,
    @scheduled_for,
    @target_resource_id::uuid,
    @target_kind,
    @target_version,
    @effective_input_sha256,
    @prompt_profile_id::uuid,
    @prompt_revision,
    @runtime_revision_id::uuid,
    @session_policy,
    nullif(@room_id, '')::uuid,
    @notification_policy,
    @maximum_execution_duration_ms,
    @coalesce,
    @overlap_policy,
    @maximum_attempts,
    @initial_backoff_ms,
    @maximum_backoff_ms,
    @dead_letter_at,
    @state,
    @attempt,
    @available_at,
    nullif(@outcome, ''),
    nullif(@result_artifact_id, '')::uuid,
    @updated_at
)
ON CONFLICT (schedule_id, scheduled_for) DO NOTHING
