apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [../../../base/control-api-gateway]
patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
  - path: vault-pki-patch.yaml
labels:
  - pairs: {mattercodex.dev/environment: staging}
    includeSelectors: false
    includeTemplates: true
