apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: artifact-retention
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: artifact-retention
      app.kubernetes.io/component: retention-job
