apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: staff-control-center
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: staff-control-center
      app.kubernetes.io/component: staff-frontend
