apiVersion: v1
kind: Service
metadata:
  name: staff-control-center
  labels:
    app.kubernetes.io/name: staff-control-center
spec:
  selector:
    app.kubernetes.io/name: staff-control-center
    app.kubernetes.io/component: staff-frontend
  ports:
    - {name: http, port: 8080, targetPort: http, protocol: TCP}
