apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: staff-control-center
spec:
  serverName: staff-control-center.kodex-system.svc.cluster.local
  insecureSkipVerify: false
  rootCAsSecrets:
    - staff-control-center-backend-tls
  certificatesSecrets:
    - staff-control-center-ingress-client-tls
