apiVersion: v1
kind: Secret
metadata:
  name: kodex-postgres
  namespace: {{ envOr "KODEX_PRODUCTION_NAMESPACE" "" }}
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: kodex
type: Opaque
stringData:
  KODEX_POSTGRES_DB: "{{ envOr "KODEX_POSTGRES_DB" "kodex" }}"
  KODEX_POSTGRES_USER: "{{ envOr "KODEX_POSTGRES_USER" "kodex" }}"
  KODEX_POSTGRES_PASSWORD: "{{ envOr "KODEX_POSTGRES_PASSWORD" "" }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: kodex-platform-runtime
  namespace: {{ envOr "KODEX_PRODUCTION_NAMESPACE" "" }}
  labels:
    app.kubernetes.io/name: kodex-platform-runtime
    app.kubernetes.io/part-of: kodex
type: Opaque
stringData:
  KODEX_ACCESS_MANAGER_GRPC_AUTH_TOKEN: "{{ envOr "KODEX_ACCESS_MANAGER_GRPC_AUTH_TOKEN" "" }}"
  KODEX_PROJECT_CATALOG_GRPC_AUTH_TOKEN: "{{ envOr "KODEX_PROJECT_CATALOG_GRPC_AUTH_TOKEN" "" }}"
  KODEX_PACKAGE_HUB_GRPC_AUTH_TOKEN: "{{ envOr "KODEX_PACKAGE_HUB_GRPC_AUTH_TOKEN" "" }}"
  KODEX_PROVIDER_HUB_GRPC_AUTH_TOKEN: "{{ envOr "KODEX_PROVIDER_HUB_GRPC_AUTH_TOKEN" "" }}"
  KODEX_AGENT_MANAGER_GRPC_AUTH_TOKEN: "{{ envOr "KODEX_AGENT_MANAGER_GRPC_AUTH_TOKEN" "" }}"
  KODEX_GOVERNANCE_MANAGER_GRPC_AUTH_TOKEN: "{{ envOr "KODEX_GOVERNANCE_MANAGER_GRPC_AUTH_TOKEN" "" }}"
  KODEX_INTERACTION_HUB_GRPC_AUTH_TOKEN: "{{ envOr "KODEX_INTERACTION_HUB_GRPC_AUTH_TOKEN" "" }}"
  KODEX_GITHUB_WEBHOOK_SECRET: "{{ envOr "KODEX_GITHUB_WEBHOOK_SECRET" "" }}"
  KODEX_EXTERNAL_CALLBACK_SECRET: "{{ envOr "KODEX_EXTERNAL_CALLBACK_SECRET" "" }}"
  KODEX_FLEET_MANAGER_GRPC_AUTH_TOKEN: "{{ envOr "KODEX_FLEET_MANAGER_GRPC_AUTH_TOKEN" "" }}"
  KODEX_FLEET_MANAGER_ACCESS_MANAGER_GRPC_AUTH_TOKEN: "{{ envOr "KODEX_FLEET_MANAGER_ACCESS_MANAGER_GRPC_AUTH_TOKEN" "" }}"
  KODEX_FLEET_MANAGER_SECRET_RESOLVER_VAULT_TOKEN: "{{ envOr "KODEX_FLEET_MANAGER_SECRET_RESOLVER_VAULT_TOKEN" "" }}"
  KODEX_PACKAGE_HUB_ACCESS_MANAGER_GRPC_AUTH_TOKEN: "{{ envOr "KODEX_PACKAGE_HUB_ACCESS_MANAGER_GRPC_AUTH_TOKEN" "" }}"
  KODEX_PACKAGE_HUB_VAULT_TOKEN: "{{ envOr "KODEX_PACKAGE_HUB_VAULT_TOKEN" "" }}"
  KODEX_PROVIDER_HUB_ACCESS_MANAGER_GRPC_AUTH_TOKEN: "{{ envOr "KODEX_PROVIDER_HUB_ACCESS_MANAGER_GRPC_AUTH_TOKEN" "" }}"
  KODEX_PROVIDER_HUB_VAULT_TOKEN: "{{ envOr "KODEX_PROVIDER_HUB_VAULT_TOKEN" "" }}"
  KODEX_GOVERNANCE_MANAGER_ACCESS_MANAGER_GRPC_AUTH_TOKEN: "{{ envOr "KODEX_GOVERNANCE_MANAGER_ACCESS_MANAGER_GRPC_AUTH_TOKEN" "" }}"
  KODEX_INTEGRATION_GATEWAY_SECRET_RESOLVER_VAULT_TOKEN: "{{ envOr "KODEX_INTEGRATION_GATEWAY_SECRET_RESOLVER_VAULT_TOKEN" "" }}"
  KODEX_RUNTIME_MANAGER_GRPC_AUTH_TOKEN: "{{ envOr "KODEX_RUNTIME_MANAGER_GRPC_AUTH_TOKEN" "" }}"
  KODEX_RUNTIME_MANAGER_ACCESS_MANAGER_GRPC_AUTH_TOKEN: "{{ envOr "KODEX_RUNTIME_MANAGER_ACCESS_MANAGER_GRPC_AUTH_TOKEN" "" }}"
  KODEX_RUNTIME_MANAGER_FLEET_MANAGER_GRPC_AUTH_TOKEN: "{{ envOr "KODEX_RUNTIME_MANAGER_FLEET_MANAGER_GRPC_AUTH_TOKEN" "" }}"
  KODEX_AGENT_MANAGER_PACKAGE_HUB_GRPC_AUTH_TOKEN: "{{ envOr "KODEX_AGENT_MANAGER_PACKAGE_HUB_GRPC_AUTH_TOKEN" "" }}"
  KODEX_AGENT_MANAGER_PROJECT_CATALOG_GRPC_AUTH_TOKEN: "{{ envOr "KODEX_AGENT_MANAGER_PROJECT_CATALOG_GRPC_AUTH_TOKEN" "" }}"
  KODEX_AGENT_MANAGER_RUNTIME_MANAGER_GRPC_AUTH_TOKEN: "{{ envOr "KODEX_AGENT_MANAGER_RUNTIME_MANAGER_GRPC_AUTH_TOKEN" "" }}"
  KODEX_AGENT_MANAGER_PROVIDER_HUB_GRPC_AUTH_TOKEN: "{{ envOr "KODEX_AGENT_MANAGER_PROVIDER_HUB_GRPC_AUTH_TOKEN" "" }}"
  KODEX_ACCESS_MANAGER_DATABASE_DSN: "{{ envOr "KODEX_ACCESS_MANAGER_DATABASE_DSN" "" }}"
  KODEX_PROJECT_CATALOG_DATABASE_DSN: "{{ envOr "KODEX_PROJECT_CATALOG_DATABASE_DSN" "" }}"
  KODEX_PACKAGE_HUB_DATABASE_DSN: "{{ envOr "KODEX_PACKAGE_HUB_DATABASE_DSN" "" }}"
  KODEX_PACKAGE_HUB_EVENT_LOG_DATABASE_DSN: "{{ envOr "KODEX_PACKAGE_HUB_EVENT_LOG_DATABASE_DSN" "" }}"
  KODEX_PROVIDER_HUB_DATABASE_DSN: "{{ envOr "KODEX_PROVIDER_HUB_DATABASE_DSN" "" }}"
  KODEX_PROVIDER_HUB_EVENT_LOG_DATABASE_DSN: "{{ envOr "KODEX_PROVIDER_HUB_EVENT_LOG_DATABASE_DSN" "" }}"
  KODEX_GOVERNANCE_MANAGER_DATABASE_DSN: "{{ envOr "KODEX_GOVERNANCE_MANAGER_DATABASE_DSN" "" }}"
  KODEX_GOVERNANCE_MANAGER_EVENT_LOG_DATABASE_DSN: "{{ envOr "KODEX_GOVERNANCE_MANAGER_EVENT_LOG_DATABASE_DSN" "" }}"
  KODEX_FLEET_MANAGER_DATABASE_DSN: "{{ envOr "KODEX_FLEET_MANAGER_DATABASE_DSN" "" }}"
  KODEX_FLEET_MANAGER_EVENT_LOG_DATABASE_DSN: "{{ envOr "KODEX_FLEET_MANAGER_EVENT_LOG_DATABASE_DSN" "" }}"
  KODEX_RUNTIME_MANAGER_DATABASE_DSN: "{{ envOr "KODEX_RUNTIME_MANAGER_DATABASE_DSN" "" }}"
  KODEX_AGENT_MANAGER_DATABASE_DSN: "{{ envOr "KODEX_AGENT_MANAGER_DATABASE_DSN" "" }}"
  KODEX_AGENT_MANAGER_EVENT_LOG_DATABASE_DSN: "{{ envOr "KODEX_AGENT_MANAGER_EVENT_LOG_DATABASE_DSN" "" }}"
  KODEX_ACCESS_MANAGER_EVENT_LOG_DATABASE_DSN: "{{ envOr "KODEX_ACCESS_MANAGER_EVENT_LOG_DATABASE_DSN" "" }}"
  KODEX_RUNTIME_MANAGER_EVENT_LOG_DATABASE_DSN: "{{ envOr "KODEX_RUNTIME_MANAGER_EVENT_LOG_DATABASE_DSN" "" }}"
  KODEX_PLATFORM_EVENT_LOG_DATABASE_DSN: "{{ envOr "KODEX_PLATFORM_EVENT_LOG_DATABASE_DSN" "" }}"
