apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - networkpolicy.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: kodex
      kodex.dev/environment: staging
      kodex.dev/profile: web-only
      kodex.dev/local-profile: hot-reload
    includeSelectors: false
    includeTemplates: true
