/** @type {import('@hey-api/openapi-ts').UserConfig} */
export default {
  input: "specs/openapi/control-center.v1.yaml",
  output: {
    clean: true,
    header: [
      "// This file is auto-generated by @hey-api/openapi-ts",
      "// @ts-nocheck",
    ],
    path: "apps/control-center/src/generated",
    tsConfigPath: "apps/control-center/tsconfig.json",
  },
  plugins: ["@hey-api/typescript", "@hey-api/client-fetch", "@hey-api/sdk"],
};
