package service

const (
	reasonAllowlistEmail    = "allowlist_email"
	reasonAllowlistDomain   = "allowlist_domain"
	reasonAllowlistDisabled = "allowlist_disabled"
	reasonAllowlistMiss     = "allowlist_miss"
	reasonIdentityFound     = "identity_found"
	reasonIdentityLinked    = "identity_linked"
	reasonExplicitAllow     = "explicit_allow"
	reasonExplicitDeny      = "explicit_deny"
	reasonNoMatchingRule    = "no_matching_rule"
	reasonSubjectBlocked    = "subject_blocked"
)

const (
	accessEventOrganizationCreated           = "access.organization.created"
	accessEventGroupCreated                  = "access.group.created"
	accessEventMembershipCreated             = "access.membership.created"
	accessEventMembershipUpdated             = "access.membership.updated"
	accessEventMembershipDisabled            = "access.membership.disabled"
	accessEventAllowlistEntryCreated         = "access.allowlist_entry.created"
	accessEventUserCreated                   = "access.user.created"
	accessEventUserIdentityLinked            = "access.user.identity_linked"
	accessEventExternalProviderCreated       = "access.external_provider.created"
	accessEventExternalAccountCreated        = "access.external_account.created"
	accessEventExternalAccountBindingCreated = "access.external_account_binding.created"
	accessEventAccessActionCreated           = "access.access_action.created"
	accessEventAccessRuleCreated             = "access.access_rule.created"
	accessEventAccessDecisionRecorded        = "access.access_decision.recorded"
	accessAggregateOrganization              = "organization"
	accessAggregateGroup                     = "group"
	accessAggregateMembership                = "membership"
	accessAggregateAllowlistEntry            = "allowlist_entry"
	accessAggregateUser                      = "user"
	accessAggregateExternalProvider          = "external_provider"
	accessAggregateExternalAccount           = "external_account"
	accessAggregateExternalAccountBinding    = "external_account_binding"
	accessAggregateAccessAction              = "access_action"
	accessAggregateAccessRule                = "access_rule"
	accessAggregateAccessDecisionAudit       = "access_decision_audit"
	accessRuleScopeGlobal                    = "global"
	accessRuleScopeOrganization              = "organization"
	accessRuleScopeProject                   = "project"
	accessRuleScopeRepository                = "repository"
)
