package service

const (
	reasonAllowlistEmail       = "allowlist_email"
	reasonAllowlistDomain      = "allowlist_domain"
	reasonAllowlistDisabled    = "allowlist_disabled"
	reasonAllowlistMiss        = "allowlist_miss"
	reasonUserStatusChanged    = "user_status_changed"
	reasonAllowlistEntryClosed = "allowlist_entry_disabled"
	reasonIdentityFound        = "identity_found"
	reasonIdentityLinked       = "identity_linked"
	reasonExplicitAllow        = "explicit_allow"
	reasonExplicitDeny         = "explicit_deny"
	reasonNoMatchingRule       = "no_matching_rule"
	reasonActionNotFound       = "action_not_found"
	reasonActionDisabled       = "action_disabled"
	reasonResourceTypeMismatch = "resource_type_mismatch"
	reasonSubjectPending       = "subject_pending"
	reasonSubjectBlocked       = "subject_blocked"
)

const (
	accessEventOrganizationCreated           = "access.organization.created"
	accessEventGroupCreated                  = "access.group.created"
	accessEventMembershipCreated             = "access.membership.created"
	accessEventMembershipUpdated             = "access.membership.updated"
	accessEventMembershipDisabled            = "access.membership.disabled"
	accessEventAllowlistEntryCreated         = "access.allowlist_entry.created"
	accessEventAllowlistEntryUpdated         = "access.allowlist_entry.updated"
	accessEventAllowlistEntryDisabled        = "access.allowlist_entry.disabled"
	accessEventUserCreated                   = "access.user.created"
	accessEventUserStatusChanged             = "access.user.status_changed"
	accessEventUserIdentityLinked            = "access.user.identity_linked"
	accessEventExternalProviderCreated       = "access.external_provider.created"
	accessEventExternalProviderUpdated       = "access.external_provider.updated"
	accessEventExternalAccountCreated        = "access.external_account.created"
	accessEventExternalAccountBindingCreated = "access.external_account_binding.created"
	accessEventExternalAccountBindingUpdated = "access.external_account_binding.updated"
	accessEventAccessActionCreated           = "access.access_action.created"
	accessEventAccessActionUpdated           = "access.access_action.updated"
	accessEventAccessRuleCreated             = "access.access_rule.created"
	accessEventAccessRuleUpdated             = "access.access_rule.updated"
	accessEventAccessDecisionRecorded        = "access.access_decision.recorded"
	accessAggregateOrganization              = "organization"
	accessAggregateGroup                     = "group"
	accessAggregateMembership                = "membership"
	accessAggregateAllowlistEntry            = "allowlist_entry"
	accessAggregateUser                      = "user"
	accessAggregateExternalProvider          = "external_provider"
	accessAggregateExternalAccount           = "external_account"
	accessAggregateExternalAccountBinding    = "external_account_binding"
	accessAggregateAccessAction              = "access_action"
	accessAggregateAccessRule                = "access_rule"
	accessAggregateAccessDecisionAudit       = "access_decision_audit"
	accessOperationCreateOrganization        = "domain.Service.CreateOrganization"
	accessOperationCreateGroup               = "domain.Service.CreateGroup"
	accessOperationRegisterExternalAccount   = "domain.Service.RegisterExternalAccount"
	accessRuleScopeGlobal                    = "global"
	accessRuleScopeOrganization              = "organization"
	accessRuleScopeProject                   = "project"
	accessRuleScopeRepository                = "repository"
	accessActionExplainAccess                = "access.audit.explain"
	accessResourceAccessDecisionAudit        = "access_decision_audit"
)
